'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Authority}=require('../src/authority.js'),D=require('../src/domain.js'),G=require('../src/game.js');
function fixture(extra={}){let now=Date.parse('2026-10-05T12:00:00Z');const a=new Authority({paidEntryEnabled:true,eligibility:()=>true,now:()=>now,random:()=>0,...extra});a.addAccount('alice',{coins:1000,crowns:1000,rating:1500,games:30,verified:true});a.addAccount('bob',{coins:1000,crowns:1000,rating:2700,games:60,verified:true});a.account('alice').friends=['bob'];a.account('bob').friends=['alice'];return {a,advance:ms=>now+=ms,setTime:t=>now=t};}
const total=a=>[...a.accounts.values()].reduce((n,p)=>n+D.wealth(p),0);
function startDirect(a,id='m',terms={}){const q=a.offer(id,'alice','bob',{kind:'friend',amount:20,...terms});a.accept(id,'bob',q.termsHash);return a.matches.get(id);}
function finish(a,advance,id='m'){while(!a.matches.get(id).state.winner){const m=a.matches.get(id),move=G.legal(m.state)[0];advance(2000);a.move(id,m.symbols[m.state.turn],m.revision,'move:'+m.revision,move);}return a.matches.get(id).receipt;}
test('direct challenger alone reserves, loser/defender pays zero; 50% burn',()=>{const {a}=fixture(),before=total(a);const m=startDirect(a);assert.equal(a.account('alice').crowns,980);assert.equal(a.account('bob').crowns,1000);assert.equal(total(a),before);const r=a.resign(m.id,'alice');assert.equal(r.payout,10);assert.equal(r.burn,10);assert.equal(a.account('bob').crowns,1010);assert.equal(a.account('alice').reservedCrowns,0);assert.equal(total(a),before-100);});
test('challenger wins: recovers half, no minted pot or extra challenge bonus',()=>{const {a}=fixture();const m=startDirect(a);const r=a.resign(m.id,'bob');assert.equal(a.account('alice').crowns,990);assert.equal(a.account('bob').crowns,1000);assert.equal(r.bonus,0);assert.equal(r.rating.delta,23.98);assert.equal(a.account('bob').rating,2676.02);});
test('queue charges two equal Coin tickets and settles ratings + burn',()=>{const {a,advance}=fixture(),before=total(a);const q=a.offerQueue('m','alice','bob');a.accept('m','alice',q.termsHash);assert.equal(a.account('alice').coins,1000);a.accept('m','bob',q.termsHash);assert.equal(a.account('alice').coins,988);assert.equal(a.account('bob').coins,988);const r=finish(a,advance);assert.equal(r.burn,r.refunded?0:12);assert.equal(total(a),before-r.burn+r.bonus);assert(r.rating);});
test('free direct and free friend play never transfer funds or Elo',()=>{const {a,advance}=fixture();const before=total(a);startDirect(a,'m',{rated:false});const r=finish(a,advance);assert.equal(r.payout,0);assert.equal(r.burn,0);assert.equal(r.rating,null);assert.equal(total(a),before);assert.equal(a.account('alice').rating,1500);});
test('draw and operator void refund exact owners, not half to each on sponsored direct',()=>{for(const outcome of ['draw','void']){const {a}=fixture();const m=startDirect(a);if(outcome==='draw')a._settle(m,'DRAW','draw');else a.voidByOperator('m');assert.equal(a.account('alice').crowns,1000);assert.equal(a.account('bob').crowns,1000);assert.equal(m.escrow,0);assert.equal(a.burned.crowns,0);}});
test('reject/cancel/expire do not charge anything',()=>{for(const end of ['decline','cancel','expire']){const {a,advance}=fixture();a.offer('m','alice','bob',{kind:'friend',amount:20});if(end==='expire'){advance(600001);a.expire('m');}else a[end]('m',end==='cancel'?'alice':'bob');assert.equal(a.account('alice').crowns,1000);assert.equal(a.account('alice').reservedCrowns,0);}});
test('funds and eligibility are checked again at acceptance',()=>{const {a}=fixture();const q=a.offer('m','alice','bob',{kind:'friend',amount:20});a.account('alice').crowns=1;assert.throws(()=>a.accept('m','bob',q.termsHash),/INSUFFICIENT/);assert.equal(a.account('bob').crowns,1000);assert.equal(a.matches.get('m').escrow,0);});
test('counterfeit tiers ignored; funding and clock terms cannot silently change',()=>{const {a}=fixture();const q=a.offer('m','alice','bob',{kind:'leaderboard',from:'grandmaster',to:'wood'});assert.equal(q.terms.from,'gold');assert.equal(q.terms.to,'emerald');assert.throws(()=>a.accept('m','bob','wrong'),/TERMS_CHANGED/);a.account('alice').rating=1510;assert.throws(()=>a.accept('m','bob',q.termsHash),/REQUOTE/);});
test('only matchmaker can choose queued ranked pairings',()=>{const {a}=fixture();assert.throws(()=>a.offer('m','alice','bob',{mode:'queue'}),/MATCHMAKER_REQUIRED/);});
test('production defaults deny paid entries, allow free play',()=>{const {a}=fixture({paidEntryEnabled:false});assert.throws(()=>a.offerQueue('m','alice','bob'),/PAID_ENTRY/);assert.equal(a.offer('free','alice','bob',{rated:false}).quote.pool,0);});
test('jurisdiction/account gate independent of currency source and paid-entry flag',()=>{const {a}=fixture({eligibility:()=>false});assert.throws(()=>a.offer('m','alice','bob',{kind:'friend',amount:2}),/PAID_ENTRY/);});
test('one active match, no self challenge, blocked recipients and placements protected',()=>{const {a}=fixture();assert.throws(()=>a.offer('self','alice','alice',{}));a.account('alice').blocked.push('bob');assert.throws(()=>a.offer('blocked','alice','bob',{}));a.account('alice').blocked=[];a.account('alice').games=9;assert.throws(()=>a.offer('unplaced','alice','bob',{}),/PLACEMENTS/);a.account('alice').games=30;startDirect(a);a.addAccount('charlie',{verified:true,games:20});assert.throws(()=>a.offer('other','alice','charlie',{rated:false}),/ALREADY/);});
test('first-turn ownership and replay safety',()=>{const {a}=fixture();startDirect(a);assert.throws(()=>a.move('m','bob',0,'x',{b:4,c:2}),/NOT_YOUR_TURN/);const one=a.move('m','alice',0,'a',{b:4,c:2});assert.deepEqual(a.move('m','alice',0,'a',{b:4,c:2}),one);assert.equal(a.matches.get('m').revision,1);assert.throws(()=>a.move('m','alice',0,'a',{b:4,c:3}),/IDEMPOTENCY/);assert.throws(()=>a.move('m','bob',0,'b',{b:2,c:0}),/STALE/);});
test('stale/replayed terminal settlement cannot double-credit',()=>{const {a}=fixture();const m=startDirect(a);const r=a.resign('m','alice'),state=JSON.stringify(a.export());assert.deepEqual(a._settle(m,'O','resign'),r);assert.equal(JSON.stringify(a.export()),state);});
test('timer uses server deadline; expiry is loss, no bonus',()=>{const {a,advance}=fixture();startDirect(a);advance(30001);assert.throws(()=>a.move('m','alice',0,'late',{b:0,c:0}),/TIMER/);const r=a.timeout('m');assert.equal(r.winner,'bob');assert.equal(r.bonus,0);});
test('ranked direct repeat pairing limited, free rematch remains available',()=>{const {a}=fixture();startDirect(a);a.resign('m','alice');assert.throws(()=>a.offer('again','alice','bob',{kind:'friend',amount:2}),/PAIR/);assert.equal(a.offer('free','alice','bob',{rated:false}).quote.rated,false);});
test('verified store catalogue controls grants; replay and refund hold work',()=>{const {a}=fixture({verifyPurchase:(e,actor)=>({...e,valid:true,accountId:actor})});const evidence={store:'apple',transactionId:'tx1',productId:'crowns_100'};assert.equal(a.purchase('alice',evidence).crowns,100);assert.equal(a.purchase('alice',evidence).duplicate,true);assert.equal(a.account('alice').crowns,1100);assert.throws(()=>a.purchase('bob',evidence),/RECEIPT_REPLAY/);a.refundPurchase('apple','tx1');assert.throws(()=>a.convert('alice','crowns',1,'convert1'),/HELD/);assert.throws(()=>a.purchase('alice',evidence),/HELD/);});
test('unverified purchases and fabricated quantities rejected',()=>{const {a}=fixture();assert.throws(()=>a.purchase('alice',{amount:1000000}),/STORE_UNAVAILABLE/);const {a:b}=fixture({verifyPurchase:()=>({valid:false})});assert.throws(()=>b.purchase('alice',{}),/INVALID_RECEIPT/);});
test('complete online quests depend on server metrics, not a client completed flag',()=>{const {a,advance}=fixture();const q=a.offerQueue('m','alice','bob');a.accept('m','alice',q.termsHash);a.accept('m','bob',q.termsHash);finish(a,advance);assert.equal(a.claimQuest('alice','ranked'),6);assert.equal(a.claimQuest('alice','ranked'),0);assert.equal(a.claimQuest('alice','friend'),0);});
test('weekly reward uses closed-week season-qualified snapshots and credits once',()=>{const {a,setTime}=fixture(),start=D.weekStart('2026-10-05'),alice=a.account('alice');alice.season={id:D.season(start).id,startedAt:D.season(start).start,games:5,queueGames:3,opponents:['b','c','d'],wins:3,losses:2,draws:0,peakRating:alice.rating,lastRatedAt:start+3600000,qualifiedAt:start+3600000};alice.lastRatedAt=alice.season.lastRatedAt;alice.history=[0,1,2,3,4].map((d,i)=>({id:'h'+i,at:start+d*D.DAY+3600000,rated:true,qualified:true,activityQualified:true,queue:i<3,opponent:['b','c','d'][i%3]}));for(let d=0;d<7;d++){setTime(start+d*D.DAY+80000000);a.snapshotDay();}assert.throws(()=>a.payoutWeek('2026-10-05'),/NOT_FINISHED/);setTime(start+7*D.DAY);const r=a.payoutWeek('2026-10-05');assert.equal(r[0].amount,65);assert.equal(a.account('alice').coins,1065);a.payoutWeek('2026-10-05');assert.equal(a.account('alice').coins,1065);const restored=new Authority({state:a.export(),now:()=>start+8*D.DAY});restored.payoutWeek('2026-10-05');assert.equal(restored.account('alice').coins,1065);});
test('no late invented snapshot, no reward for unplaced or inactive players',()=>{const {a,setTime}=fixture();setTime(D.weekStart('2026-10-05'));assert.deepEqual(a.payoutWeek('2026-09-28'),[]);assert.equal(a.account('alice').coins,1000);});

test('season rollover archives the prior quarter without resetting Elo',()=>{const {a,setTime}=fixture(),alice=a.account('alice'),before=alice.rating;alice.season={id:'2026-Q4',startedAt:Date.parse('2026-10-01T00:00:00Z'),games:8,queueGames:5,opponents:['b','c','d'],wins:5,losses:2,draws:1,peakRating:before+30,lastRatedAt:Date.parse('2026-12-20T00:00:00Z'),qualifiedAt:Date.parse('2026-10-03T00:00:00Z')};setTime(Date.parse('2027-01-01T00:00:00Z'));const status=a.seasonStatus(alice);assert.equal(status.id,'2027-Q1');assert.equal(status.qualified,false);assert.equal(status.games,0);assert.equal(alice.rating,before);assert.equal(alice.seasonHistory.at(-1).id,'2026-Q4');assert.equal(alice.seasonHistory.at(-1).finishRating,before);});
test('season result counters use wins losses and draws fields',()=>{const {a}=fixture(),alice=a.account('alice');const s=a._season(alice);s.losses=2;const key={win:'wins',loss:'losses',draw:'draws'}.loss;s[key]++;assert.equal(s.losses,3);assert.equal(s.losss,undefined);});


test('verified store Crowns keep purchased provenance through currency conversion',()=>{
 const {a}=fixture({verifyPurchase:(e,actor)=>({...e,valid:true,accountId:actor})});
 const before=a.account('alice');assert.equal(before.purchasedCrowns,0);assert.equal(before.purchasedCoins,0);
 a.purchase('alice',{store:'apple',transactionId:'prov1',productId:'crowns_100'});
 assert.equal(a.account('alice').crowns,1100);assert.equal(a.account('alice').purchasedCrowns,100);
 a.convert('alice','crowns',50,'prov-convert');
 assert.equal(a.account('alice').purchasedCrowns,50);assert.equal(a.account('alice').purchasedCoins,500);
 assert.equal(a.account('alice').crowns,1050);assert.equal(a.account('alice').coins,1500);
});

test('money-purchased currency cannot fund competitive entry even after Crown to Coin conversion',()=>{
 const verifyPurchase=(e,actor)=>({...e,valid:true,accountId:actor}),a=new Authority({paidEntryEnabled:true,eligibility:()=>true,verifyPurchase,random:()=>0});
 a.addAccount('buyer',{coins:0,crowns:0,rating:1500,games:30,verified:true});
 a.addAccount('earned',{coins:1000,crowns:0,rating:1500,games:30,verified:true});
 a.purchase('buyer',{store:'google',transactionId:'restricted-entry',productId:'crowns_100'});
 a.convert('buyer','crowns',100,'restricted-convert');
 assert.equal(a.account('buyer').coins,1000);assert.equal(a.account('buyer').purchasedCoins,1000);
 assert.throws(()=>a.offerQueue('restricted','buyer','earned'),/COMPETITION_FUNDS_RESTRICTED/);
});

test('purchased balance may coexist with separately earned competitive funds without laundering',()=>{
 const verifyPurchase=(e,actor)=>({...e,valid:true,accountId:actor}),a=new Authority({paidEntryEnabled:true,eligibility:()=>true,verifyPurchase,random:()=>0});
 a.addAccount('mixed',{coins:100,crowns:0,rating:1500,games:30,verified:true});
 a.addAccount('earned',{coins:100,crowns:0,rating:1500,games:30,verified:true});
 a.purchase('mixed',{store:'apple',transactionId:'mixed-entry',productId:'crowns_100'});
 a.convert('mixed','crowns',100,'mixed-convert');
 const q=a.offerQueue('allowed-earned','mixed','earned');a.accept(q.id,'mixed',q.termsHash);a.accept(q.id,'earned',q.termsHash);
 assert.equal(a.account('mixed').purchasedCoins,1000);
 assert.equal(a.account('mixed').coins,1088);
 assert.equal(a.account('mixed').reservedCoins,12);
});
