'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {buildService}=require('../server/community-server'),{IdentityProviders}=require('../server/identity-provider'),{jwk,sign}=require('./helpers/identity-fixture');
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mega-account-http-'));let now=Date.now();const providers=new IdentityProviders({config:{google:{nativeAudiences:['test-native']},apple:{nativeAudiences:['test-native']}},now:()=>now,keysForTest:()=>[jwk]});const origin='http://localhost:0';const s=buildService({file:path.join(dir,'db.sqlite'),origin,providerInstance:providers,allowLocalHttp:true,storeOptions:{now:()=>now,paidEntryEnabled:true,eligibility:()=>true}});await new Promise(r=>s.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+s.server.address().port;let op=0;
 t.after(()=>{s.close();fs.rmSync(dir,{recursive:true,force:true});});
 function client(){let cookie='',csrf='';return {get cookie(){return cookie;},set cookie(v){cookie=v;},async request(p,b,extra={}){const r=await fetch(url+p,{method:b===undefined?'GET':'POST',headers:{...(cookie?{Cookie:cookie}:{}),...(b!==undefined?{Origin:origin,'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':'test-'+ ++op}:{}),...extra},body:b===undefined?undefined:JSON.stringify(b),redirect:'manual'});const sc=r.headers.get('set-cookie');if(sc)cookie=sc.split(';')[0];let data;try{data=await r.json();}catch{data={};}if(data.csrf)csrf=data.csrf;return {status:r.status,data,headers:r.headers};},async login(subject,p='google',intent='login'){await this.request('/api/account/session');const c=await this.request('/api/account/native/challenge',{provider:p,intent});assert.equal(c.status,200,JSON.stringify(c.data));const r=await this.request('/api/account/native/finish',{provider:p,state:c.data.state,idToken:sign(p,subject,c.data.nonce,now)});assert.equal(r.status,200,JSON.stringify(r.data));return r.data.profile;}};}
 return {...s,url,origin,client,advance:ms=>now+=ms,now:()=>now};}
test('real HTTP identity: guest, Google registration, Apple link and cross-device restore',async t=>{const f=await fixture(t),a=f.client(),b=f.client();const initial=await a.request('/api/account/session');assert.equal(initial.data.linked,false);assert.match(initial.headers.get('set-cookie'),/HttpOnly/);const p=await a.login('google-a');assert.match(p.tag,/^MEGA-/);const edit=await a.request('/api/account/profile',{username:'alice',displayName:'Alice',avatar:'ring'});assert.equal(edit.status,200);const linked=await a.login('apple-a','apple','link');assert.equal(linked.id,p.id);const recovered=await b.login('apple-a','apple');assert.equal(recovered.username,'alice');assert.equal(recovered.tag,p.tag);assert.equal(recovered.id,p.id);});
test('HTTP CSRF, malicious origins and spoofed JWTs are rejected',async t=>{const f=await fixture(t),a=f.client();await a.request('/api/account/session');assert.equal((await a.request('/api/account/start',{provider:'google'},{Origin:'https://evil.example'})).data.error,'ORIGIN_OR_CONTENT_TYPE');assert.equal((await a.request('/api/account/start',{provider:'google'},{'X-CSRF-Token':'bad'})).data.error,'CSRF_FAILED');const c=await a.request('/api/account/native/challenge',{provider:'google'});const bad=await a.request('/api/account/native/finish',{provider:'google',state:c.data.state,idToken:sign('google','bad','wrong',f.now())});assert.equal(bad.data.error,'INVALID_TOKEN_CLAIMS');assert.equal(f.store.read().accounts.size,0);});
test('two clients: search, friend request, accept, challenge, real moves, updated stats',async t=>{const f=await fixture(t),a=f.client(),b=f.client(),pa=await a.login('a'),pb=await b.login('b');await a.request('/api/account/profile',{username:'alice',displayName:'Alice'});await b.request('/api/account/profile',{username:'bob',displayName:'Bob'});assert.equal((await a.request('/api/community/search?q=BOB')).data[0].id,pb.id);await a.request('/api/community/friend',{action:'request',target:pb.tag});assert.equal((await b.request('/api/community/friends')).data.incoming[0].username,'alice');await b.request('/api/community/friend',{action:'accept',target:pa.id});await b.request('/api/community/presence',{foreground:true});assert.equal((await a.request('/api/community/friends')).data.friends[0].presence.state,'online');
 const m=(await a.request('/api/v1/offer',{id:'friend-game',opponent:pb.id,terms:{kind:'friend',rated:false}})).data;assert.equal(m.quote.pool,0);const invited=(await b.request('/api/v1/invitations')).data;assert.equal(invited[0].challengerName,'Alice');const accepted=(await b.request('/api/v1/accept',{id:m.id,termsHash:m.termsHash})).data;assert.equal(accepted.status,'PLAYING');const x=accepted.symbols.X===pa.id?a:b,o=x===a?b:a;
 const move=await x.request('/api/v1/move',{id:m.id,revision:0,move:{b:4,c:2}});assert.equal(move.status,200);assert.equal(move.data.state.required,2);assert.equal((await o.request('/api/v1/move',{id:m.id,revision:1,move:{b:2,c:4}})).status,200);await x.request('/api/v1/resign',{id:m.id});const stats=(await a.request('/api/community/profile/'+pb.id)).data.stats.friend;assert.equal(stats.games,1);assert.equal(stats.wins+stats.losses,1);assert.equal(f.store.read().account(pa.id).rating,600);assert.equal(f.store.read().account(pb.id).coins,100);
});
test('unfriending cancels an invitation and cannot be bypassed by direct JSON',async t=>{const f=await fixture(t),a=f.client(),b=f.client(),pa=await a.login('a'),pb=await b.login('b');assert.equal((await a.request('/api/v1/offer',{id:'bad',opponent:pb.id,terms:{kind:'friend',rated:false}})).data.error,'FRIENDSHIP_REQUIRED');await a.request('/api/community/friend',{action:'request',target:pb.id});await b.request('/api/community/friend',{action:'accept',target:pa.id});const m=(await a.request('/api/v1/offer',{id:'cancel-on-block',opponent:pb.id,terms:{kind:'friend',rated:false}})).data;await b.request('/api/community/friend',{action:'block',target:pa.id});assert.equal((await a.request('/api/v1/match/'+m.id)).data.status,'CANCELLED');assert.notEqual((await b.request('/api/v1/accept',{id:m.id,termsHash:m.termsHash})).status,200);});
test('both casual queued clients can discover, accept and play without exposing opponent beforehand',async t=>{const f=await fixture(t),a=f.client(),b=f.client(),pa=await a.login('a'),pb=await b.login('b');await a.request('/api/v1/queue',{mode:'casual'});const ready=(await b.request('/api/v1/queue',{mode:'casual'})).data;assert.equal(ready.state,'matched');const pending=(await a.request('/api/v1/match/'+ready.matchId)).data;assert.deepEqual(pending.players,[pa.id]);assert.equal(pending.opponentHidden,true);const first=(await a.request('/api/v1/accept',{id:ready.matchId,termsHash:pending.termsHash})).data;assert.equal(first.status,'OFFERED');assert.deepEqual(first.accepted,[pa.id]);const playing=(await b.request('/api/v1/accept',{id:ready.matchId,termsHash:pending.termsHash})).data;assert.equal(playing.status,'PLAYING');assert.equal(playing.players.length,2);assert.equal(playing.quote.rated,false);await a.request('/api/v1/resign',{id:ready.matchId});const again=await a.request('/api/v1/queue',{mode:'casual'});assert.equal(again.status,200);assert.equal(again.data.state,'searching');});
test('cloud CAS conflict and restore do not mint account wallet; logout revokes cookie',async t=>{const f=await fixture(t),a=f.client(),b=f.client(),p=await a.login('a');await b.login('a');const data=require('../src/domain').fresh();data.wallet.coins=12345;const save=await a.request('/api/account/save',{revision:0,practice:data});assert.equal(save.data.revision,1);assert.equal((await b.request('/api/account/save',{revision:0,practice:data})).data.error,'SAVE_CONFLICT');assert.equal((await b.request('/api/account/save')).data.practice.wallet.coins,12345);assert.equal((await a.request('/api/v1/profile')).data.wallet.coins,100);const oldCookie=a.cookie;await a.request('/api/account/logout',{allDevices:true});a.cookie=oldCookie;assert.equal((await a.request('/api/v1/profile')).status,401);assert.equal((await b.request('/api/v1/profile')).status,401);});
test('new online private room uses the same identity and CSRF session',async t=>{const f=await fixture(t),a=f.client(),b=f.client();await a.login('a');await b.login('b');const room=await a.request('/api/party/command',{type:'create',format:'duel',clock:180,increment:2});assert.equal(room.status,200,JSON.stringify(room.data));const joined=await b.request('/api/party/command',{type:'join',id:room.data.code});assert.equal(joined.status,200,JSON.stringify(joined.data));assert.equal(joined.data.players.length,2);});

test('web authorization code callback verifies nonce, rotates cookie and restores the profile',async t=>{const f=await fixture(t),a=f.client();await a.request('/api/account/session');const {IdentityProviders}=require('../server/identity-provider');const liveProviders=new IdentityProviders({config:{google:{clientId:'web-test',clientSecret:'test-secret'}},now:f.now,keysForTest:()=>[jwk],fetcher:async(url,options)=>{assert.equal(url,'https://oauth2.googleapis.com/token');const form=options.body;assert.equal(form.get('client_id'),'web-test');assert.equal(form.get('code'),'once');const nonce=f.community.db.prepare('SELECT nonce,verifier FROM signin_attempts ORDER BY rowid DESC').get();assert.equal(form.get('code_verifier'),nonce.verifier);return new Response(JSON.stringify({id_token:sign('google','web-a',nonce.nonce,f.now(),{aud:'web-test'})}),{status:200});}});
 // Swap only the provider instance on an isolated handler; identity verification still runs.
 const handler=require('../server/community-http').createCommunityHandler({community:f.community,store:f.store,providers:liveProviders,matchmaker:f.matchmaker,origin:f.origin,allowLocalHttp:true});f.server.removeAllListeners('request');f.server.on('request',handler);
 const started=await a.request('/api/account/start',{provider:'google',intent:'login'});assert.equal(started.status,200);const u=new URL(started.data.url);assert.ok(u.searchParams.get('code_challenge'));const previous=a.cookie;const cb=await a.request('/auth/callback/google?code=once&state='+u.searchParams.get('state'));assert.equal(cb.status,303);assert.equal(cb.headers.get('location'),'/?account=linked');assert.notEqual(a.cookie,previous);assert.equal((await a.request('/api/account/session')).data.linked,true);const retry=await a.request('/auth/callback/google?code=once&state='+u.searchParams.get('state'));assert.match(retry.headers.get('location'),/INVALID_AUTH_STATE/);
});
