'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {DurableStore}=require('../server/economy-store');
const {CommunityStore}=require('../server/community-store');
const {IdentityProviders,sha}=require('../server/identity-provider');
const D=require('../src/domain'),G=require('../src/game');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mega-social-'));let now=Date.parse('2026-10-05T12:00Z');const store=new DurableStore(path.join(dir,'db.sqlite'),{now:()=>now}),c=new CommunityStore({store,origin:'https://mega.example',now:()=>now});t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return {store,c,advance:ms=>now+=ms,now:()=>now};}
function login(c,subject,provider='google',existing=null,intent='login'){const boot=existing?{token:existing}:c.bootstrap();const p=c.start(boot.token,provider,intent,'native'),attempt=c.consume(boot.token,p.state,provider,'native');return c.finishVerified(boot.token,attempt,{provider,subject});}
test('anonymous session does not create a competitive account or cloud save',t=>{const {c,store}=fixture(t),s=c.bootstrap();assert.equal(s.actor,null);assert.equal(store.read().accounts.size,0);assert.throws(()=>c.requireLinked(s.token),/LINK_ACCOUNT_REQUIRED/);});
test('unique tags and normalized usernames are immutable across recovery',t=>{const {c}=fixture(t),a=login(c,'subject-a'),b=login(c,'subject-b');assert.notEqual(a.profile.tag,b.profile.tag);const edit=c.edit(a.actor,{username:'Alice_123',displayName:'Alice',avatar:'ring'});assert.equal(edit.username,'alice_123');assert.throws(()=>c.edit(b.actor,{username:'ALICE_123'}),/USERNAME_TAKEN/);assert.throws(()=>c.edit(b.actor,{username:'admin'}),/INVALID_USERNAME/);assert.throws(()=>c.edit(b.actor,{displayName:123}),/INVALID_DISPLAY_NAME/);const restored=login(c,'subject-a');assert.equal(restored.actor,a.actor);assert.equal(restored.profile.tag,a.profile.tag);assert.equal(restored.profile.username,edit.username);});
test('profile edits cannot supply rating, tag or balance',t=>{const {c,store}=fixture(t),a=login(c,'a');c.edit(a.actor,{username:'alice',rating:3000,tag:'FAKE',coins:999999});const p=c.profile(a.actor,a.actor);assert.equal(p.rating,600);assert.equal(p.tag,a.profile.tag);assert.equal(store.read().account(a.actor).coins,D.POLICY.startingCoins);});
test('auth attempts bind to browser, provider and one use; rotates session',t=>{const {c}=fixture(t),a=c.bootstrap(),b=c.bootstrap(),attempt=c.start(a.token,'google','login','native');assert.throws(()=>c.consume(b.token,attempt.state,'google','native'),/INVALID_AUTH_STATE/);assert.throws(()=>c.consume(a.token,attempt.state,'apple','native'),/INVALID_AUTH_STATE/);const accepted=c.consume(a.token,attempt.state,'google','native');assert.throws(()=>c.consume(a.token,attempt.state,'google','native'),/INVALID_AUTH_STATE/);const logged=c.finishVerified(a.token,accepted,{provider:'google',subject:'a'});assert.equal(c.session(a.token),null);assert.equal(c.session(logged.token).actor,logged.actor);assert.throws(()=>c.csrf(logged.token,'bad'),/CSRF_FAILED/);});
test('linking preserves identity; conflict never silently merges wallets',t=>{const {c,store}=fixture(t),a=login(c,'ga'),b=login(c,'ab','apple');const p=c.start(a.token,'apple','link','native'),attempt=c.consume(a.token,p.state,'apple','native');assert.throws(()=>c.finishVerified(a.token,attempt,{provider:'apple',subject:'ab'}),/ACCOUNT_LINKED_ELSEWHERE/);assert.equal(store.read().accounts.size,2);const linked=login(c,'aa','apple',a.token,'link');assert.equal(linked.actor,a.actor);assert.deepEqual(linked.profile.providers,['apple','google']);assert.equal(login(c,'aa','apple').actor,a.actor);assert.equal(store.read().account(a.actor).coins,D.POLICY.startingCoins);assert.equal(store.read().account(b.actor).coins,D.POLICY.startingCoins);});
test('cannot unlink last provider, sensitive relink requires recent login',t=>{const {c,advance}=fixture(t),a=login(c,'a');assert.throws(()=>c.unlink(a.token,'google'),/LAST_LOGIN_METHOD/);const b=login(c,'b','apple',a.token,'link');c.unlink(b.token,'google');assert.deepEqual(c.identities(a.actor).map(x=>x.provider),['apple']);advance(16*60000);assert.throws(()=>c.start(b.token,'google','link'),/REAUTH_REQUIRED/);});
test('search finds exact tag and case-insensitive username without private stats',t=>{const {c}=fixture(t),a=login(c,'a'),b=login(c,'b');c.edit(a.actor,{username:'alpha'});assert.equal(c.search(b.actor,a.profile.tag.toLowerCase())[0].id,a.actor);const results=c.search(b.actor,'ALP');assert.equal(results[0].username,'alpha');assert.equal(results[0].stats,undefined);assert.throws(()=>c.search(b.actor,'al'),/SEARCH_TOO_SHORT/);});
test('friend requests, acceptance, cancellation and block are consistent',t=>{const {c}=fixture(t),a=login(c,'a'),b=login(c,'b');c.social(a.actor,'req','request',b.profile.tag);c.social(a.actor,'req','request',b.profile.tag);assert.equal(c.friends(b.actor).incoming.length,1);c.social(b.actor,'accept','accept',a.actor);assert.equal(c.friends(a.actor).friends.length,1);assert.equal(c.profile(a.actor,b.actor).relation,'friend');assert.ok(c.profile(a.actor,b.actor).stats);assert.equal(c.profile(a.actor,b.actor).stats.tournament.entered,0);c.social(a.actor,'block','block',b.actor);assert.equal(c.friends(b.actor).friends.length,0);assert.throws(()=>c.profile(a.actor,b.actor),/PROFILE_NOT_FOUND/);assert.deepEqual(c.search(b.actor,a.profile.tag),[]);c.social(a.actor,'unblock','unblock',b.actor);assert.equal(c.profile(a.actor,b.actor).relation,'none');c.social(a.actor,'req2','request',b.actor);c.social(a.actor,'cancel','cancel',b.actor);assert.equal(c.friends(b.actor).incoming.length,0);});
test('presence lease expires and is private, multidevice aware, background-aware',t=>{const {c,advance,store}=fixture(t),a=login(c,'a'),b=login(c,'b');c.heartbeat(a.token,true);assert.equal(c.presence(a.actor,b.actor).state,'hidden');c.social(a.actor,'r','request',b.actor);c.social(b.actor,'a','accept',a.actor);assert.equal(c.presence(a.actor,b.actor).state,'online');c.heartbeat(a.token,false);assert.equal(c.presence(a.actor,b.actor).state,'away');const another=login(c,'a');c.heartbeat(another.token,true);assert.equal(c.presence(a.actor,b.actor).state,'online');const auth=store.read();auth.account(a.actor).activeMatch='match:1';c.write(auth);assert.equal(c.presence(a.actor,b.actor).state,'in-match');advance(46000);assert.equal(c.presence(a.actor,b.actor).state,'offline');});
test('save/restore is versioned and never restores paid currencies or Elo',t=>{const {c,store}=fixture(t),a=login(c,'a'),save=D.fresh();save.wallet.coins=999999;save.records.push({id:'local',mode:'bot',result:'win',activeSeconds:60});save.records.push({id:'forged',mode:'ranked',result:'win'});const s=c.save(a.actor,0,save);assert.equal(s.revision,1);assert.throws(()=>c.save(a.actor,0,save),/SAVE_CONFLICT/);const r=c.restore(a.actor);assert.equal(r.practice.records.length,1);assert.equal(r.practice.wallet.coins,999999);assert.equal(store.read().account(a.actor).coins,D.POLICY.startingCoins);assert.equal(store.read().account(a.actor).rating,600);});
test('sign-out all devices revokes old sessions',t=>{const {c}=fixture(t),a=login(c,'a'),b=login(c,'a');c.logout(a.token,true);assert.equal(c.session(a.token),null);assert.equal(c.session(b.token),null);});
const pair=crypto.generateKeyPairSync('rsa',{modulusLength:2048}),jwk={...pair.publicKey.export({format:'jwk'}),kid:'test-key',alg:'RS256',use:'sig'};
const jwt=(claims,header={alg:'RS256',kid:'test-key'})=>{const h=Buffer.from(JSON.stringify(header)).toString('base64url'),c=Buffer.from(JSON.stringify(claims)).toString('base64url'),p=h+'.'+c;return p+'.'+crypto.sign('RSA-SHA256',Buffer.from(p),pair.privateKey).toString('base64url');};
test('provider verifier checks real signature issuer audience expiration and nonce',async()=>{const now=Date.now(),sec=Math.floor(now/1000),p=new IdentityProviders({config:{google:{nativeAudiences:['app']}},now:()=>now,keysForTest:()=>[jwk]}),claims={iss:'https://accounts.google.com',aud:'app',sub:'123',nonce:'bound',iat:sec,exp:sec+100};assert.deepEqual(await p.verify('google',jwt(claims),'bound'),{provider:'google',subject:'123'});for(const patch of [{aud:'other'},{iss:'https://attacker.example'},{exp:sec-1},{iat:sec-700},{nonce:'other'}])await assert.rejects(p.verify('google',jwt({...claims,...patch}),'bound'),/INVALID_TOKEN_CLAIMS/);await assert.rejects(p.verify('google',jwt(claims,{alg:'none',kid:'test-key'}),'bound'),/INVALID_TOKEN_HEADER/);const bad=jwt(claims).split('.');bad[2]=Buffer.alloc(256).toString('base64url');await assert.rejects(p.verify('google',bad.join('.'),'bound'),/INVALID_SIGNATURE/);});
test('Google authorization uses PKCE, state/nonce; Apple code-only query does not request scopes',()=>{const p=new IdentityProviders({config:{google:{clientId:'google-web',clientSecret:'secret'},apple:{clientId:'apple-web',teamId:'team',keyId:'key',privateKey:'configured'}}}),a={state:'state',nonce:'nonce',verifier:'verifier'};const g=new URL(p.authorization('google',a,'https://mega.example/auth/callback/google'));assert.equal(g.searchParams.get('code_challenge'),sha('verifier'));assert.equal(g.searchParams.get('state'),'state');const apple=new URL(p.authorization('apple',a,'https://mega.example/auth/callback/apple'));assert.equal(apple.searchParams.get('response_mode'),'query');assert.equal(apple.searchParams.has('scope'),false);});
module.exports={pair,jwk,jwt};

test('cloud and provider mapping survive a new database connection',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mega-restore-')),file=path.join(dir,'db.sqlite');let store=new DurableStore(file),c=new CommunityStore({store,origin:'https://mega.example'});const a=login(c,'persist');c.edit(a.actor,{username:'persistent',displayName:'Saved player'});c.save(a.actor,0,D.fresh());store.close();store=new DurableStore(file);c=new CommunityStore({store,origin:'https://mega.example'});const restored=login(c,'persist');assert.equal(restored.actor,a.actor);assert.equal(restored.profile.username,'persistent');assert.equal(restored.profile.tag,a.profile.tag);assert.equal(c.restore(a.actor).revision,1);store.close();fs.rmSync(dir,{recursive:true,force:true});});
test('queued presence is derived from the scheduler hook, not heartbeat JSON',t=>{const {c}=fixture(t),a=login(c,'a');c.isQueued=actor=>actor===a.actor;c.heartbeat(a.token,true);assert.equal(c.presence(a.actor,a.actor).state,'queued');assert.throws(()=>c.heartbeat(a.token,'in-match'),/INVALID_PRESENCE/);});

test('reauthentication rotates a session but cannot switch the profile or add an identity',t=>{
 const {c,advance}=fixture(t),a=login(c,'alice'),b=login(c,'bob');advance(16*60000);
 assert.throws(()=>c.start(a.token,'apple','link','native'),/REAUTH_REQUIRED/);
 const started=c.start(a.token,'google','reauth','native'),attempt=c.consume(a.token,started.state,'google','native');
 assert.throws(()=>c.finishVerified(a.token,attempt,{provider:'google',subject:'bob'}),/REAUTH_ACCOUNT_MISMATCH/);
 assert.equal(c.requireLinked(a.token).actor,a.actor);assert.equal(c.identities(a.actor).length,1);
 const retry=c.start(a.token,'google','reauth','native'),good=c.consume(a.token,retry.state,'google','native');
 const verified=c.finishVerified(a.token,good,{provider:'google',subject:'alice'});
 assert.equal(verified.actor,a.actor);assert.equal(verified.profile.tag,a.profile.tag);assert.equal(c.session(a.token),null);
 assert.ok(c.start(verified.token,'apple','link','native').state);
 const anonymous=c.bootstrap();assert.throws(()=>c.start(anonymous.token,'google','reauth','native'),/LINK_ACCOUNT_REQUIRED/);
});

test('crossed friend requests settle to one friendship and no stale invitations',t=>{
 const {c}=fixture(t),a=login(c,'alice'),b=login(c,'bob');
 c.social(a.actor,'request-a','request',b.actor);c.social(b.actor,'request-b','request',a.actor);
 c.social(a.actor,'accept-b','accept',b.actor);
 for(const actor of [a.actor,b.actor]){const f=c.friends(actor);assert.equal(f.friends.length,1);assert.equal(f.incoming.length,0);assert.equal(f.outgoing.length,0);}
});

test('a held profile is not exposed through search or public profile statistics',t=>{
 const {c,store}=fixture(t),a=login(c,'alice'),b=login(c,'bob');c.edit(b.actor,{username:'bob_test',statsVisibility:'public'});
 const authority=store.read();authority.account(b.actor).hold=true;c.write(authority);
 assert.deepEqual(c.search(a.actor,'bob_test'),[]);assert.throws(()=>c.profile(a.actor,b.actor),/PROFILE_NOT_FOUND/);
});
