'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),M=require('../server/matchmaking.js');
function account(id,rating,{games=30,casualRating=rating,verified=true,friends=[],blocked=[],history=[],coins=1000}={}){return {id,rating,games,casualRating,casualGames:0,verified,friends,blocked,history,coins,crowns:1000,suspended:false,hold:false,activeMatch:null};}
function ticket(actor,joinedAt=0,region='iad',latencyMs=40){return {actor,mode:'ranked',joinedAt,region,latencyMs};}
test('ranked search starts tight and remains bounded',()=>{const a=account('a',1500);assert.equal(M.searchWindow('ranked',0,a),50);assert.equal(M.searchWindow('ranked',30,a),150);assert.equal(M.searchWindow('ranked',200,a),200);assert.equal(M.searchWindow('ranked',80,account('g',2700)),250);});
test('casual widens faster but remains bounded',()=>{assert.equal(M.searchWindow('casual',0,account('a',1500)),100);assert.equal(M.searchWindow('casual',40,account('a',1500)),350);});
test('ranked blocks friends, recent rematches and early cross-region',()=>{const now=100000,A=account('a',1500,{friends:['b']}),B=account('b',1520,{friends:['a']});assert.equal(M.compatibility(A,B,ticket('a',0),ticket('b',0),'ranked',now).reason,'FRIEND_QUEUE_BLOCK');A.friends=[];B.friends=[];A.history=[{opponent:'b',queue:true,rated:true,at:now-1000}];assert.equal(M.compatibility(A,B,ticket('a',now-10000),ticket('b',now-10000),'ranked',now).reason,'RECENT_OPPONENT');A.history=[];assert.equal(M.compatibility(A,B,ticket('a',now-10000,'iad'),ticket('b',now-10000,'sin'),'ranked',now).reason,'REGION_WAIT');});
test('placement accounts prefer placement pool',()=>{const now=60000,A=account('a',700,{games:3}),B=account('b',720,{games:40});assert.equal(M.compatibility(A,B,ticket('a',now-10000),ticket('b',now-10000),'ranked',now).reason,'PLACEMENT_POOL');assert.equal(M.compatibility(A,B,ticket('a',0),ticket('b',0),'ranked',now).ok,true);});
test('tournament cohort hard cap is 200',()=>{const map=new Map([['a',account('a',1500)],['b',account('b',1600)],['c',account('c',1801)]]),economy={accounts:map},rooms=[{id:'r1',table:'low',status:'LOBBY',created:0,expires:999999,players:[{id:'b'}]},{id:'r2',table:'low',status:'LOBBY',created:0,expires:999999,players:[{id:'c'}]}];assert.equal(M.selectTournamentRoom(rooms,economy,'a','low',70000).id,'r1');});
test('tournament seed is deterministic',()=>{const map=new Map([['a',account('a',1000)],['b',account('b',1400)],['c',account('c',1200)]]);assert.deepEqual(M.tournamentSeed(['a','b','c'],{accounts:map}),['b','c','a']);});
test('quality is symmetric',()=>{assert.equal(M.quality(1500,1500),1);assert.equal(M.quality(1500,1700),M.quality(1700,1500));});
