'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {DurableStore}=require('../server/economy-store.js'),{MonetizationStore}=require('../server/monetization-store.js'),{createAdMobVerifier}=require('../server/admob-ssv.js'),{migrate}=require('../server/production/migrations.js'),D=require('../src/domain.js'),M=require('../src/monetization.js');
function fixture(t,overrides={}){let now=Date.parse('2026-10-08T12:00:00Z');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mega-v35-')),file=path.join(dir,'db'),store=new DurableStore(file,{now:()=>now});migrate(store.db);for(const id of ['alice','bob'])store.run({actor:'test',scope:'operator'},id,{type:'provision',account:id,options:{verified:true,createdAt:now-3*M.DAY}});const keys=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'}),verifier=createAdMobVerifier({now:()=>now,fetchKeys:async()=>({keys:[{keyId:1,pem:keys.publicKey.export({type:'spki',format:'pem'})}]})});const receipts=new Map();const options={now:()=>now,eligible:()=>true,purchasesEnabled:true,verifyPurchase:async token=>receipts.get(token),adMode:'hybrid',adUnit:'test-unit',verifyAd:verifier,...overrides};const service=new MonetizationStore(store,options);t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return {store,service,file,options,receipts,time:n=>now=n,now:()=>now,write:fn=>{const a=store.read();fn(a);store.db.prepare('UPDATE state SET json=? WHERE id=1').run(JSON.stringify(a.export()));},signed:(ticket,id='ad1',extra={})=>{const q=new URLSearchParams({ad_unit:'test-unit',custom_data:ticket.ticket,reward_amount:'1',reward_item:'cosmetic_reward',timestamp:String(now),transaction_id:id,user_id:ticket.actor,...extra}).toString(),signature=crypto.sign('sha256',Buffer.from(q),keys.privateKey).toString('base64url');return q+'&signature='+signature+'&key_id=1';}};}
function casual(id,at,extra={}){return {id,at,mode:'casual',queue:true,rated:false,qualified:true,result:'win',reason:'line',activeSeconds:120,...extra};}
test('commercial functionality defaults off and never assumes an eligible audience',t=>{const f=fixture(t);const off=new MonetizationStore(f.store);assert.equal(off.status('alice').adMode,'off');assert.equal(off.status('alice').purchasesAvailable,false);assert.throws(()=>off.ticket('alice','x','credits'),/ADS_UNAVAILABLE/);const unknown=new MonetizationStore(f.store,{...f.options,eligible:async()=>true});assert.equal(unknown.status('alice').adMode,'off');});
test('SSV verifies exact raw signature, actor, ticket and reward; retries do not grant twice',async t=>{const f=fixture(t),before=D.wealth(f.store.read().account('alice')),ticket=f.service.ticket('alice','one','credits'),raw=f.signed(ticket);await assert.rejects(()=>f.service.callback(raw.replace('reward_amount=1','reward_amount=5')),/SIGNATURE/);await assert.rejects(()=>f.service.callback(f.signed(ticket,'wrong',{user_id:'bob'})),/TICKET/);assert.equal((await f.service.callback(raw)).credits,5);assert.equal((await f.service.callback(raw)).credits,5);assert.equal(f.service.status('alice').credits,5);assert.equal(D.wealth(f.store.read().account('alice')),before);await assert.rejects(()=>f.service.callback(f.signed(ticket,'different')),/TICKET_USED/);});
test('reward quota and cooldown survive restart and separate SQLite connections',async t=>{const f=fixture(t);for(let i=0;i<4;i++){const q=f.service.ticket('alice','ad'+i,'credits');await f.service.callback(f.signed(q,'provider'+i));assert.throws(()=>f.service.ticket('alice','early'+i,'credits'),/COOLDOWN/);f.time(f.now()+M.POLICY.rewardedGap);}const second=new DurableStore(f.file,{now:f.options.now});try{const s=new MonetizationStore(second,f.options);assert.equal(s.status('alice').credits,20);assert.throws(()=>s.ticket('alice','fifth','credits'),/DAILY_LIMIT/);}finally{second.close();}});
test('expired attempts cannot create unlimited delayed rewards across the daily quota',async t=>{const f=fixture(t),callbacks=[];for(let i=0;i<4;i++){const q=f.service.ticket('alice','slow'+i,'credits');callbacks.push(f.signed(q,'late'+i));f.time(f.now()+M.POLICY.ticketLifetime+1);}assert.throws(()=>f.service.ticket('alice','fifth','credits'),/DAILY_LIMIT/);for(const raw of callbacks)await f.service.callback(raw);assert.equal(f.service.status('alice').credits,20);});
test('boost is non-stackable, cosmetic-only, bounded, and applies by game start not finish',async t=>{const f=fixture(t),before=D.wealth(f.store.read().account('alice'));const q=f.service.ticket('alice','boost','boost');await f.service.callback(f.signed(q));const start=f.now();f.time(start+3*M.MINUTE);assert.throws(()=>f.service.ticket('alice','stack','boost'),/BOOST_ACTIVE/);f.time(start+20*M.MINUTE);f.write(a=>{a.account('alice').history=Array.from({length:6},(_,i)=>casual('c'+i,start+3*M.MINUTE));a.account('alice').history.push(casual('late-finish',start+11*M.MINUTE),casual('late-start',start+12*M.MINUTE),casual('ranked',start+3*M.MINUTE,{mode:'ranked',rated:true}));});const result=f.service.claim('alice','claim');assert.equal(result.base,10);assert.equal(result.bonus,10);assert.equal(result.credits,20);assert.equal(f.service.claim('alice','claim2').base,0);assert.equal(D.wealth(f.store.read().account('alice')),before);});
test('only real free queue history earns banked theme credits without changing competitive money',t=>{const f=fixture(t);f.write(a=>a.account('alice').history=[casual('valid',f.now()),casual('resign',f.now(),{reason:'resign'}),casual('short',f.now(),{qualified:false}),casual('direct',f.now(),{queue:false}),casual('future',f.now()+M.DAY)]);const before=D.wealth(f.store.read().account('alice'));assert.equal(f.service.claim('alice','c').credits,2);assert.equal(f.service.status('alice').credits,2);assert.equal(D.wealth(f.store.read().account('alice')),before);assert.equal(M.frame('copper'),null);});
test('verified Crown purchases grant only exact catalogue currency and cannot restore consumables',async t=>{const f=fixture(t);f.receipts.set('real',{valid:true,accountId:'alice',store:'apple',transactionId:'tx1',productId:'crowns_100'});await assert.rejects(()=>f.service.purchase('alice','fake',{valid:true,productId:'crowns_100',crowns:1e6}),/INVALID_RECEIPT/);await f.service.purchase('alice','p','real');assert.equal(f.store.read().account('alice').crowns,100);await assert.rejects(()=>f.service.purchase('alice','restore','real',true),/INVALID_PRODUCT/);f.receipts.set('second',{...f.receipts.get('real'),transactionId:'tx2'});await f.service.purchase('alice','p2','second');assert.equal(f.store.read().account('alice').crowns,200);await assert.rejects(()=>f.service.purchase('bob','steal','real'),/INVALID_RECEIPT/);});
test('Remove Ads survives restore and refund revokes only non-currency entitlement',async t=>{const f=fixture(t);f.receipts.set('r',{valid:true,accountId:'alice',store:'google',transactionId:'remove1',productId:'remove_ads'});await f.service.purchase('alice','buy','r');assert.equal(f.service.status('alice').removeAds,true);assert.throws(()=>f.service.automaticPermit('alice','permit'),/DISABLED/);f.service.refund('google','remove1');assert.equal(f.service.status('alice').removeAds,false);assert.equal(f.store.read().account('alice').hold,false);await assert.rejects(()=>f.service.purchase('alice','restore','r',true),/REFUNDED/);});
test('rewarded choices remain optional after Remove Ads; no ads during server matches',async t=>{const f=fixture(t);f.receipts.set('r',{valid:true,accountId:'alice',store:'google',transactionId:'remove1',productId:'remove_ads'});await f.service.purchase('alice','buy','r');assert(f.service.ticket('alice','r','credits').ticket);f.write(a=>a.account('bob').activeMatch='m');assert.throws(()=>f.service.ticket('bob','live','credits'),/MATCH_ACTIVE/);});
test('server automatic cap, conservative permits, and full-screen gap cannot be bypassed by refresh',t=>{const f=fixture(t);for(let i=0;i<6;i++){assert(f.service.automaticPermit('alice','p'+i).allowed);assert.throws(()=>f.service.automaticPermit('alice','fast'+i),/COOLDOWN/);f.time(f.now()+M.POLICY.fullScreenGap);}assert.throws(()=>f.service.automaticPermit('alice','seventh'),/DAILY_LIMIT/);});
test('callback cannot use stale, future, duplicate query parameters or wrong ad unit',async t=>{const f=fixture(t),q=f.service.ticket('alice','r','credits');await assert.rejects(()=>f.service.callback(f.signed(q,'wrong',{ad_unit:'other'})),/INVALID_AD_TICKET/);await assert.rejects(()=>f.service.callback(f.signed(q,'future',{timestamp:String(f.now()+M.DAY)})),/STALE/);await assert.rejects(()=>f.service.callback('user_id=x&user_id=y&signature=x&key_id=1'),/DUPLICATE/);f.time(f.now()+M.POLICY.ticketLifetime+1);await assert.rejects(()=>f.service.callback(f.signed(q,'late')),/TICKET/);});
test('boost uses exact authoritative match start at sub-second boundaries when available',async t=>{const f=fixture(t);const q=f.service.ticket('alice','b','boost');await f.service.callback(f.signed(q));const start=f.now(),end=start+M.POLICY.boostDuration;f.time(end+120000);f.write(a=>{const h=casual('boundary',end+60000,{activeSeconds:60});a.account('alice').history=[h];a.matches.set('boundary',{id:'boundary',started:end-500,commands:new Map()});});const result=f.service.claim('alice','c');assert.equal(result.base,2);assert.equal(result.bonus,2);});

test('rewarded and automatic ads are bound to the exact configured native platform unit',async t=>{
 const f=fixture(t,{adUnit:'',adUnits:{android:{rewarded:'android-reward',interstitial:'android-interstitial'},ios:{rewarded:'ios-reward',interstitial:'ios-interstitial'}}});
 const ticket=f.service.ticket('alice','platform-reward','credits','android');
 assert.equal(ticket.platform,'android');assert.equal(ticket.adUnit,'android-reward');
 await assert.rejects(()=>f.service.callback(f.signed(ticket,'wrong-platform',{ad_unit:'ios-reward'})),/INVALID_AD_TICKET/);
 const granted=await f.service.callback(f.signed(ticket,'right-platform',{ad_unit:'android-reward'}));assert.equal(granted.credits,5);
 assert.throws(()=>f.service.ticket('bob','unknown-platform','credits','web'),/ADS_UNAVAILABLE/);
 const permit=f.service.automaticPermit('bob','android-auto','android');assert.equal(permit.platform,'android');assert.equal(permit.adUnit,'android-interstitial');
});
