'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),M=require('../src/monetization.js');
const now=Date.parse('2026-10-08T12:00:00Z');
function ready(){const p=M.startSession(M.startSession(null,now-2*M.DAY),now);for(let i=0;i<5;i++)M.noteGame(p,{id:'g'+i,mode:'bot',reason:'line',result:'win',moves:40,activeSeconds:120});return p;}
const context={adMode:'hybrid',entitlementsKnown:true,removeAds:false,consentReady:true,adReady:true,transition:'result_to_home',gameMode:'bot',safe:true};
test('ad eligibility needs both game count and active time after onboarding',()=>{const p=ready();assert(M.interstitialAllowed(p,context,now));for(const [k,v] of [['sessions',1],['totalGames',4],['gamesSinceAd',2],['activeSinceAd',479999],['firstSeenAt',now],['sessionAds',2],['dayAds',6],['lastFullScreenAt',now-60000]])assert.equal(M.interstitialAllowed({...p,[k]:v},context,now),false,k);});
test('live, queued, hidden, unknown-consent and ad-free contexts never show automatic ads',()=>{for(const k of ['playing','onlineMatch','queued','partyOpen','hidden','modalOpen','removeAds'])assert.equal(M.interstitialAllowed(ready(),{...context,[k]:true},now),false,k);for(const k of ['entitlementsKnown','consentReady','adReady','safe'])assert.equal(M.interstitialAllowed(ready(),{...context,[k]:false},now),false,k);for(const mode of ['ranked','casual','local','tournament','friend'])assert.equal(M.interstitialAllowed(ready(),{...context,gameMode:mode},now),false);});
test('normal result required; duplicate, practice, short, timeout and resign cannot advance exposure',()=>{const p=ready(),before=JSON.stringify(p);for(const r of [{id:'g1'},{id:'new',practice:true},{id:'new',reason:'resign'},{id:'new',reason:'timeout'},{id:'new',moves:2},{id:'new',activeSeconds:2}])assert.equal(M.noteGame(p,{mode:'bot',reason:'line',result:'win',moves:40,activeSeconds:120,...r}),false);assert.equal(JSON.stringify(p),before);});
test('rewarded ads suppress subsequent full screen ads and automatic ads reset cadence',()=>{const p=ready();M.noteFullScreen(p,'rewarded',now);assert.equal(M.interstitialAllowed(p,context,now+7*M.MINUTE),false);assert(M.interstitialAllowed(p,context,now+8*M.MINUTE));M.noteFullScreen(p,'interstitial',now+8*M.MINUTE);assert.equal(p.gamesSinceAd,0);assert.equal(p.activeSinceAd,0);assert.equal(p.dayAds,1);assert.equal(p.sessionAds,1);});
test('purchase catalogue is explicit, non-recurring and cannot buy skill',()=>{for(const p of M.PRODUCTS){assert(!('elo' in p));assert(!('multiplier' in p));assert(['consumable','non-consumable'].includes(p.type));}assert.equal(M.packInfo('starter_100').coinEquivalent,1000);assert.equal(M.product('remove_ads').removeAds,true);assert.equal(M.product('wheel'),null);assert.equal(M.FRAMES.filter(f=>f.id!=='classic'&&f.credits!==null).length,3);});
test('cohort assignment is stable and invalid configuration fails closed',()=>{assert.equal(M.cohort('alice','experiment'),M.cohort('alice','experiment'));assert.equal(M.cohort('alice'),'off');assert.throws(()=>M.cohort('alice','invalid'),/INVALID_AD_MODE/);});
test('boost uses server match start and permits finishing after expiry, never ranked or short games',()=>{const b={startedAt:now,endsAt:now+10*M.MINUTE},h={id:'m',mode:'casual',queue:true,rated:false,qualified:true,reason:'line',result:'win',at:now+11*M.MINUTE,activeSeconds:120};assert(M.boostApplies(h,b));assert.equal(M.boostApplies({...h,at:now+12*M.MINUTE},b),false);assert.equal(M.boostApplies({...h,mode:'ranked',rated:true},b),false);assert.equal(M.boostApplies({...h,qualified:false},b),false);});
test('revenue is a dimensionally valid assumption model, not impressions times CPM',()=>{const r=M.revenueScenario({dau:1000,automaticOpportunities:1,rewardOptIn:.5,rewardsPerViewer:2,fill:1,interstitialEcpm:2,rewardedEcpm:4,dailyPayerShare:.01,payerSpend:1,platformFee:.3,refundRate:0});assert.equal(r.interstitial,2);assert.equal(r.rewarded,4);assert.equal(r.netIap,7);assert.equal(r.totalBeforeOperatingCosts,13);});
