'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {RoomStore}=require('../server/rooms.js'),{createPartyHandler}=require('../server/party-http.js');
async function fixture(){const store=new RoomStore(':memory:',{lanOnly:true});const handler=createPartyHandler({store}),server=http.createServer(async(req,res)=>{if(!await handler(req,res)){res.writeHead(404);res.end();}});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));return {store,server,url:'http://127.0.0.1:'+server.address().port,async close(){server.closeIdleConnections?.();server.closeAllConnections?.();if(server.listening)await new Promise(ok=>server.close(()=>ok()));store.close();}};}
let key=0;
async function call(f,path,body,token,headers={}){const r=await fetch(f.url+'/api/party/'+path,{method:body?'POST':'GET',headers:{Connection:'close',...(body?{'Content-Type':'application/json','Idempotency-Key':'key'+(++key)}:{}),...(token?{Authorization:'Bearer '+token}:{}),...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};}
test('LAN two clients: session, host, code join, readiness, move, reconnect snapshot',async()=>{const f=await fixture();try{const a=(await call(f,'session',{name:'Alice'})).data,b=(await call(f,'session',{name:'Bob'})).data;let r=(await call(f,'command',{type:'create',format:'duel'},a.token)).data;const id=r.id;assert(id);r=(await call(f,'command',{type:'join',id:r.code},b.token)).data;assert.equal(r.players.length,2);for(const p of [a,b])await call(f,'command',{type:'ready',id,value:true,rulesVersion:1},p.token);r=(await call(f,'command',{type:'start',id},a.token)).data;const game=r.fixtures[0];f.store.get(id);const raw=f.store.get(id);raw.fixtures[0].opens=Date.now()-1;f.store.save(raw);for(const p of [a,b])await call(f,'command',{type:'matchReady',id,fixture:game.id},p.token);r=(await call(f,'rooms/'+id,undefined,a.token)).data;const first=r.fixtures[0].players[0]===a.actor?a:b,other=first===a?b:a;const move=await call(f,'command',{type:'move',id,fixture:game.id,revision:0,move:{b:4,c:2},actor:'forged-id'},first.token);assert.equal(move.status,200);const read=(await call(f,'rooms/'+id,undefined,other.token)).data;assert.equal(read.fixtures[0].state.required,2);assert.equal(read.fixtures[0].state.moves.length,1);const me=(await call(f,'me',undefined,a.token)).data;assert.equal(me.actor,a.actor);}finally{await f.close();}});
test('No identity, wrong origin and unknown commands fail closed',async()=>{const f=await fixture();try{const denied=await call(f,'command',{type:'create',format:'duel'});assert.equal(denied.status,401);const origin=await call(f,'session',{name:'Alice'},undefined,{Origin:'https://hostile.invalid'});assert.equal(origin.status,400);const a=(await call(f,'session',{name:'Alice'})).data;const publicGame=await call(f,'command',{type:'publicJoin',table:'premium'},a.token);assert.equal(publicGame.data.error,'FREE_PRIVATE_ONLY');}finally{await f.close();}});
test('Every LAN participant can own one seat; 11th is rejected',async()=>{const f=await fixture();try{const people=[];for(let i=0;i<11;i++)people.push((await call(f,'session',{name:'P'+i})).data);let r=(await call(f,'command',{type:'create',format:'league'},people[0].token)).data;for(let i=1;i<10;i++){const result=await call(f,'command',{type:'join',id:r.code},people[i].token);assert.equal(result.status,200);r=result.data;}assert.equal(r.players.length,10);const extra=await call(f,'command',{type:'join',id:r.code},people[10].token);assert.equal(extra.data.error,'ROOM_FULL');}finally{await f.close();}});
test('Bodies cannot promote a guest to an operator or cancel public eligibility',async()=>{const f=await fixture();try{const a=(await call(f,'session',{name:'A'})).data;const res=await call(f,'command',{type:'publicJoin',table:'premium',scope:'operator',actor:'service'},a.token);assert.equal(res.data.error,'FREE_PRIVATE_ONLY');}finally{await f.close();}});
