'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),T=require('../src/tournament.js'),G=require('../src/game.js');
const {RoomStore}=require('../server/rooms.js');
const principal=id=>({actor:id,name:id,scope:'player'});let operation=0;const cmd=(store,id,c,key)=>store.run(principal(id),key||'op'+(++operation),c);
function env({lan=false,balance=10000}={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mega-party-')),file=path.join(dir,'test.sqlite');let now=100000;const options={lanOnly:lan,now:()=>now},store=new RoomStore(file,options);store.db.exec('CREATE TABLE state(id INTEGER PRIMARY KEY,json TEXT NOT NULL)');const accounts=Array.from({length:12},(_,i)=>['p'+i,{id:'p'+i,name:'p'+i,coins:balance,crowns:balance,reservedCoins:0,reservedCrowns:0,rating:1200+i,games:20,verified:true,suspended:false,hold:false,blocked:[],activeMatch:null}]);store.db.prepare('INSERT INTO state VALUES(1,?)').run(JSON.stringify({accounts,matches:[],burned:{coins:0,crowns:0},journal:[]}));return {store,file,options,now:()=>now,time:n=>now=n,clean(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}
function publicLobby(e,table='low'){let r;for(let i=0;i<10;i++)r=cmd(e.store,'p'+i,{type:'publicJoin',table});return r;}
function readyAll(e,r){for(const p of r.players)r=cmd(e.store,p.id,{type:'ready',id:r.id,value:true,rulesVersion:r.rulesVersion});return r;}
const account=(s,id)=>s.economy().accounts.find(([key])=>key===id)[1];
function conservation(s,table='low'){const e=s.economy(),q=T.prize(table),held=q.currency==='coins'?'reservedCoins':'reservedCrowns';return e.accounts.reduce((sum,[,p])=>sum+p[q.currency]+p[held],0)+e.burned[q.currency];}
test('ten entries are atomic, equal, and happen only after consent',()=>{const e=env();try{let r=publicLobby(e);const before=conservation(e.store);for(let i=0;i<9;i++)r=cmd(e.store,'p'+i,{type:'ready',id:r.id,value:true,rulesVersion:r.rulesVersion});assert.equal(account(e.store,'p0').coins,10000);r=cmd(e.store,'p9',{type:'ready',id:r.id,value:true,rulesVersion:r.rulesVersion});assert.equal(r.status,'RUNNING');assert.equal(r.escrow,1000);for(let i=0;i<10;i++){const a=account(e.store,'p'+i);assert.equal(a.coins,9900);assert.equal(a.reservedCoins,100);assert.equal(a.activeMatch,'tournament:'+r.id);}assert.equal(conservation(e.store),before);assert.deepEqual(r.groups.map(g=>g.players.length),[5,5]);}finally{e.clean();}});
test('late insufficient balance leaves every reservation untouched',()=>{const e=env();try{let r=publicLobby(e);for(let i=0;i<9;i++)cmd(e.store,'p'+i,{type:'ready',id:r.id,value:true,rulesVersion:1});const state=e.store.economy();state.accounts.find(([id])=>id==='p9')[1].coins=0;e.store.writeEconomy(state);assert.throws(()=>cmd(e.store,'p9',{type:'ready',id:r.id,value:true,rulesVersion:1}),/INSUFFICIENT_COINS/);for(let i=0;i<9;i++)assert.equal(account(e.store,'p'+i).reservedCoins,0);assert.equal(e.store.get(r.id).status,'LOBBY');}finally{e.clean();}});
for(const table of Object.keys(T.TABLES))test(table+' full event settles each exact placement once',()=>{const e=env();try{let r=readyAll(e,publicLobby(e,table));const total=conservation(e.store,table);let rounds=0;while(r.status==='RUNNING'&&rounds++<60){e.time(e.now()+16000);for(const f of r.fixtures.filter(f=>f.status==='READY'&&f.opens<=e.now())){cmd(e.store,f.players[0],{type:'matchReady',id:r.id,fixture:f.id});cmd(e.store,f.players[1],{type:'matchReady',id:r.id,fixture:f.id});r=cmd(e.store,f.players.slice().sort().at(-1),{type:'resign',id:r.id,fixture:f.id});}r=e.store.get(r.id);}assert.equal(r.status,'COMPLETE');assert(r.settled);const q=T.prize(table);r.ranking.forEach((id,i)=>{const acc=account(e.store,id);assert.equal(acc[q.currency],10000-q.entry+q.payouts[i]);assert.equal(acc.activeMatch,null);assert.equal(acc.rating,1200+Number(id.slice(1)));assert.equal(acc.tournamentRecord.entered,1);assert.equal(acc.tournamentRecord.bestFinish,i+1);assert.equal(acc.tournamentRecord.finishSum,i+1);if(i===0){assert.equal(acc.tournamentRecord.wins,1);assert.equal(acc.tournamentRecord.premiumWins,table==='premium'?1:0);}if(i===1)assert.equal(acc.tournamentRecord.runnerUp,1);});assert.equal(e.store.economy().burned[q.currency],q.burn);assert.equal(conservation(e.store,table),total);e.store.tick();assert.equal(conservation(e.store,table),total);assert.equal(account(e.store,r.ranking[0]).tournamentRecord.entered,1);assert(r.riskFlags.includes('HIGH_FORFEIT_RATE'));}finally{e.clean();}});
test('LAN-only mode cannot create public competitive tables',()=>{const e=env({lan:true});try{assert.throws(()=>publicLobby(e),/FREE_PRIVATE_ONLY/);assert.equal(account(e.store,'p0').coins,10000);}finally{e.clean();}});
test('private room is free even if a player sends a fake table property',()=>{const e=env({lan:true});try{const r=cmd(e.store,'p0',{type:'create',format:'mixed',table:'premium'});assert.equal(r.table,null);assert.equal(account(e.store,'p0').crowns,10000);}finally{e.clean();}});
test('restart voids a public event and refunds all contributors once',()=>{const e=env();try{const r=readyAll(e,publicLobby(e));const second=new RoomStore(e.file,e.options);second.recover();assert.equal(second.get(r.id).status,'VOID');assert.equal(account(second,'p0').coins,10000);assert.equal(account(second,'p0').reservedCoins,0);second.recover();assert.equal(account(second,'p0').coins,10000);second.close();}finally{e.clean();}});
test('an outsider cannot see, move, start, or cancel another room',()=>{const e=env();try{const r=cmd(e.store,'p0',{type:'create',format:'duel'});assert.throws(()=>e.store.view(r.id,'p2'),/NOT_IN_ROOM/);for(const type of ['start','cancel','move'])assert.throws(()=>cmd(e.store,'p2',{type,id:r.id}),/NOT_IN_ROOM/);}finally{e.clean();}});
test('membership, rules and host controls enforced',()=>{const e=env();try{let r=cmd(e.store,'p0',{type:'create',format:'mixed'});cmd(e.store,'p1',{type:'join',id:r.code});assert.throws(()=>cmd(e.store,'p1',{type:'configure',id:r.id,format:'league'}),/HOST_ONLY/);cmd(e.store,'p1',{type:'ready',id:r.id,value:true,rulesVersion:1});r=cmd(e.store,'p0',{type:'configure',id:r.id,format:'league',clock:120,increment:1});assert(r.players.every(p=>!p.ready));assert.equal(r.rulesVersion,2);assert.throws(()=>cmd(e.store,'p1',{type:'ready',id:r.id,value:true,rulesVersion:1}),/RULES_CHANGED/);cmd(e.store,'p0',{type:'transfer',id:r.id,target:'p1'});assert.equal(e.store.get(r.id).owner,'p1');}finally{e.clean();}});
test('idempotency survives restart and rejects changed payload',()=>{const e=env();try{const c={type:'create',format:'duel'},r=cmd(e.store,'p0',c,'same');const second=new RoomStore(e.file,e.options);assert.equal(cmd(second,'p0',c,'same').id,r.id);assert.throws(()=>cmd(second,'p0',{...c,format:'league'},'same'),/IDEMPOTENCY_CONFLICT/);second.close();}finally{e.clean();}});
test('no-show after start refunds a voided public event, no payout or burn',()=>{const e=env();try{let r=readyAll(e,publicLobby(e));e.time(e.now()+200000);e.store.tick();r=e.store.get(r.id);assert.equal(r.status,'VOID');assert.equal(r.receipt.refunded,true);assert.equal(account(e.store,'p0').coins,10000);assert.equal(e.store.economy().burned.coins,0);assert.equal(account(e.store,'p0').tournamentRecord,undefined);}finally{e.clean();}});
test('accepted ordinary match blocks tournament reservation',()=>{const e=env();try{const r=publicLobby(e);for(let i=0;i<9;i++)cmd(e.store,'p'+i,{type:'ready',id:r.id,value:true,rulesVersion:1});const state=e.store.economy();state.accounts[3][1].activeMatch='other-game';e.store.writeEconomy(state);assert.throws(()=>cmd(e.store,'p9',{type:'ready',id:r.id,value:true,rulesVersion:1}),/ALREADY_IN_MATCH/);assert.equal(account(e.store,'p0').reservedCoins,0);}finally{e.clean();}});
test('LAN guests use persistent secret tokens, not room codes',()=>{const e=env({lan:true});try{const s=e.store.guest('Alice');assert(s.token.length>=40);assert.equal(e.store.authenticate(s.token).actor,s.actor);assert.equal(e.store.authenticate('MEGA-CODE'),null);const second=new RoomStore(e.file,e.options);assert.equal(second.authenticate(s.token).actor,s.actor);second.close();}finally{e.clean();}});
test('Public account match command cannot forge the winner or balance',()=>{const e=env();try{const r=readyAll(e,publicLobby(e));assert.throws(()=>cmd(e.store,'p0',{type:'result',id:r.id,winner:'p0',coins:999999}),/UNKNOWN_COMMAND/);assert.equal(e.store.get(r.id).ranking,null);}finally{e.clean();}});
test('Money account hold blocks settlement; operator can refund review',()=>{const e=env();try{let r=readyAll(e,publicLobby(e));const state=e.store.economy();state.accounts[0][1].hold=true;e.store.writeEconomy(state);let iterations=0;while(r.status==='RUNNING'&&iterations++<60){e.time(e.now()+16000);for(const f of r.fixtures.filter(f=>f.status==='READY'&&f.opens<=e.now())){cmd(e.store,f.players[0],{type:'matchReady',id:r.id,fixture:f.id});cmd(e.store,f.players[1],{type:'matchReady',id:r.id,fixture:f.id});r=cmd(e.store,f.players.slice().sort().at(-1),{type:'resign',id:r.id,fixture:f.id});}r=e.store.get(r.id);}assert.equal(r.status,'REVIEW');assert.equal(account(e.store,'p0').reservedCoins,100);r=e.store.run({actor:'operator',scope:'operator'},'void',{type:'cancel',id:r.id});assert(r.receipt.refunded);assert.equal(account(e.store,'p0').coins,10000);}finally{e.clean();}});
test('public tournament entry requires a verified eligible account',()=>{const e=env();try{const state=e.store.economy();state.accounts[0][1].verified=false;e.store.writeEconomy(state);assert.throws(()=>cmd(e.store,'p0',{type:'publicJoin',table:'low'}),/INELIGIBLE/);assert.equal(account(e.store,'p0').coins,10000);}finally{e.clean();}});


test('premium tournament accepts store-bought Crowns',()=>{
 const e=env({balance:200});try{
  const state=e.store.economy();for(const [,a] of state.accounts){a.purchasedCrowns=200;a.purchasedCoins=0;a.purchaseInfluenced=true;}e.store.writeEconomy(state);
  let r=publicLobby(e,'premium');
  for(const p of r.players)r=cmd(e.store,p.id,{type:'ready',id:r.id,value:true,rulesVersion:r.rulesVersion});
  assert.equal(r.status,'RUNNING');assert.equal(r.quote.entry,200);assert.equal(r.quote.currency,'crowns');
  assert.equal(account(e.store,'p0').crowns,0);assert.equal(account(e.store,'p0').reservedCrowns,200);
 }finally{e.clean();}
});

test('tournament entry does not branch on how Crowns were obtained',()=>{
 const e=env({balance:200});try{
  const state=e.store.economy(),p0=state.accounts.find(([id])=>id==='p0')[1];p0.purchasedCrowns=200;p0.purchaseInfluenced=true;e.store.writeEconomy(state);
  const room=cmd(e.store,'p0',{type:'publicJoin',table:'premium'});
  assert.equal(room.table,'premium');assert.equal(room.quote.currency,'crowns');assert.equal(room.quote.entry,200);assert.equal(room.quote.funding,undefined);
 }finally{e.clean();}
});
