'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),T=require('../src/tournament.js'),G=require('../src/game.js');
const names=n=>Array.from({length:n},(_,i)=>'p'+i);
function started(format,n=10,table=null){let time=100000;const ids=names(n),r=T.create({id:'test',owner:ids[0],format,table,now:time});ids.forEach(p=>{T.join(r,p,p,time);T.ready(r,p,true,r.rulesVersion);});T.start(r,ids[0],ids,time);return r;}
function runToEnd(r,draw=false,clearOrder=false){let now=r.started,steps=0;while(r.status==='RUNNING'&&steps++<10000){now+=16000;T.tick(r,now);const games=r.fixtures.filter(f=>f.status==='READY'&&f.opens<=now);if(!games.length&&r.status==='RUNNING')throw Error('scheduler stuck '+JSON.stringify(r));for(const f of games){T.readyGame(r,f.id,f.players[0],now);T.readyGame(r,f.id,f.players[1],now);if(draw&&!f.decisive){for(let turn=0;f.status==='PLAYING'&&turn<81;turn++){const m=G.legal(f.state).at(-1);T.move(r,f.id,f.players[f.state.turn==='X'?0:1],f.state.moves.length,m,now+turn);}}else T.resign(r,f.id,clearOrder?f.players.slice().sort().at(-1):f.players[1],now+1);}}
 assert.equal(r.status,'COMPLETE');assert.equal(new Set(r.ranking).size,r.players.length);return r;
}
for(const n of [2,3,4,5,6,7,8,9,10])test('round robin '+n+' unique pairs and balanced starts',()=>{const ids=names(n),rounds=T.roundRobin(ids),pairs=new Set(),starts=Object.fromEntries(ids.map(x=>[x,0]));assert.equal(rounds.length,n%2?n:n-1);for(const games of rounds){const seen=new Set();for(const [a,b] of games){assert(!seen.has(a)&&!seen.has(b));seen.add(a);seen.add(b);const key=[a,b].sort().join(':');assert(!pairs.has(key));pairs.add(key);starts[a]++;}}assert.equal(pairs.size,n*(n-1)/2);for(const nStarts of Object.values(starts))assert(Math.abs(nStarts-(n-1)/2)<=.5);});
for(const format of ['league','knockout','mixed'])for(const n of (format==='mixed'?[4,5,6,7,8,9,10]:[2,3,4,5,6,7,8,9,10]))test(format+' completes all '+n+' positions',()=>{const r=runToEnd(started(format,n));assert.equal(r.ranking.length,n);});
test('10-player mixed has 20 group games + 7 playoff/placement games without ties',()=>{const r=runToEnd(started('mixed'),false,true);assert.equal(r.fixtures.filter(f=>f.group).length,20);assert.equal(r.fixtures.length,27);assert.deepEqual(r.groups.map(g=>g.players.length),[5,5]);});
test('10-player full-placement knockout has exactly 15 fixtures',()=>{const r=started('knockout');assert.equal(r.fixtures.length,15);runToEnd(r);});
test('10-player league has 45 base fixtures',()=>assert.equal(started('league').fixtures.filter(f=>f.group).length,45));
for(const table of Object.keys(T.TABLES))test(table+' exact prize conservation and fifth break-even',()=>{const q=T.prize(table);assert.equal(q.payouts.reduce((a,b)=>a+b,0)+q.burn,q.pool);assert.equal(q.pool,q.entry*10);assert.equal(q.net[4],0);assert(q.net.slice(0,4).every(n=>n>0));assert(q.net.slice(5).every(n=>n<0));assert(q.payouts.every(Number.isSafeInteger));assert.equal(q.burn,q.pool*.1);assert(q.payouts[0]>q.payouts[1]);});
test('Premium exceeds High under 10:1 conversion',()=>assert(T.prize('premium').pool*10>T.prize('high').pool));
test('Roster cap, min players, readiness and frozen configuration',()=>{const r=T.create({id:'r',owner:'p0'});for(const id of names(10))T.join(r,id,id);assert.throws(()=>T.join(r,'extra','Extra'),/ROOM_FULL/);assert.throws(()=>T.start(r,'p0',names(10)),/PLAYERS_NOT_READY/);r.players.forEach(p=>T.ready(r,p.id,true,r.rulesVersion));T.configure(r,'p0',{format:'league'});assert(r.players.every(p=>!p.ready));assert.throws(()=>T.ready(r,'p0',true,1),/RULES_CHANGED/);r.players.forEach(p=>T.ready(r,p.id,true,r.rulesVersion));T.start(r,'p0',names(10));assert.throws(()=>T.configure(r,'p0',{format:'mixed'}),/HOST_ONLY/);assert.throws(()=>T.leave(r,'p0'),/TOURNAMENT_STARTED/);});
test('Public forces ten seats, mixed, timed clocks',()=>{const r=started('knockout',10,'low');assert.equal(r.format,'mixed');assert.equal(r.clock,120);assert.equal(r.increment,1);assert.throws(()=>started('mixed',9,'low'),/NOT_ENOUGH_PLAYERS/);});
test('Turn ownership, send rule, occupied cell and revision checks',()=>{const r=started('duel',2),f=r.fixtures[0],now=f.opens;T.readyGame(r,f.id,'p0',now);T.readyGame(r,f.id,'p1',now);assert.throws(()=>T.move(r,f.id,'p1',0,{b:4,c:2},now),/NOT_YOUR_TURN/);T.move(r,f.id,'p0',0,{b:4,c:2},now+1000);assert.equal(f.state.required,2);assert.throws(()=>T.move(r,f.id,'p1',0,{b:2,c:4},now+2000),/STALE_REVISION/);assert.throws(()=>T.move(r,f.id,'p1',1,{b:4,c:4},now+2000),/ILLEGAL_MOVE/);T.move(r,f.id,'p1',1,{b:2,c:4},now+2000);assert.equal(f.state.required,4);});
test('Bank time and increment, exact flag boundary',()=>{const r=started('duel',2),f=r.fixtures[0],now=f.opens;T.readyGame(r,f.id,'p0',now);T.readyGame(r,f.id,'p1',now);T.move(r,f.id,'p0',0,{b:4,c:2},now+10000);assert.equal(f.banks.p0,172);assert.equal(T.remaining(r,f,now+15000),175);assert.throws(()=>T.move(r,f.id,'p1',1,{b:2,c:2},now+190000),/TIME_EXPIRED/);T.tick(r,now+190000);assert.equal(f.winner,'p0');assert.equal(f.reason,'timeout');});
test('Ready no-show is a loss, both absent pauses a private event',()=>{const r=started('duel',2),f=r.fixtures[0];T.readyGame(r,f.id,'p0',f.opens);T.tick(r,f.opens+45000);assert.equal(f.winner,'p0');assert.equal(f.reason,'no-show');const s=started('duel',2);T.tick(s,s.fixtures[0].expires);assert.equal(s.status,'PAUSED');T.resume(s,'p0',s.fixtures[0].expires+5000);assert.equal(s.status,'RUNNING');});
test('Public double no-show voids rather than choosing a random winner',()=>{const r=started('mixed',10,'low');T.tick(r,r.fixtures.find(f=>f.status==='READY').expires);assert.equal(r.status,'VOID');});
test('Private host transfer on leave, idempotent duplicate join',()=>{const r=T.create({id:'r',owner:'a'});T.join(r,'a','A');T.join(r,'b','B');T.join(r,'a','A');assert.equal(r.players.length,2);T.leave(r,'a');assert.equal(r.owner,'b');});
test('No client-supplied winner API is exported',()=>{assert.equal(T.finishGame,undefined);assert.equal(T.settle,undefined);});
test('Drawn decisive games replay with swapped starters; three do not allocate arbitrary prizes',()=>{
 const r=started('duel',2),f=r.fixtures[0];let now=f.opens;
 // A legal global draw position with one open, nearly drawn board. The production API never accepts this fixture injection.
 for(let attempt=0;attempt<3;attempt++){
  T.readyGame(r,f.id,f.players[0],now);T.readyGame(r,f.id,f.players[1],now);
  const original=f.players.slice();f.state.mini=Array(9).fill('DRAW');f.state.mini[4]=null;f.state.required=4;f.state.board[4]=['X','O','X','X','O','O','O','X',null];f.state.turn='X';
  T.move(r,f.id,f.players[0],f.state.moves.length,{b:4,c:8},now+1);
  if(attempt<2){assert.equal(f.status,'READY');assert.deepEqual(f.players,[original[1],original[0]]);now=f.opens;}else assert.equal(r.status,'PAUSED');
 }
});
test('free host pause freezes clocks and resumes without a time gift',()=>{const r=started('duel',2),f=r.fixtures[0],now=f.opens;T.readyGame(r,f.id,'p0',now);T.readyGame(r,f.id,'p1',now);T.pause(r,'p0',now+10000);assert.equal(T.remaining(r,f,now+100000),170);T.resume(r,'p0',now+110000);assert.equal(T.remaining(r,f,now+110000),170);assert.throws(()=>T.pause(started('mixed',10,'low'),'p0'),/HOST_ONLY/);});
test('quoted public rules are captured before consent',()=>{const r=T.create({id:'frozen',owner:'service',table:'low'});assert.equal(r.quote.entry,100);assert.equal(r.quote.burn,100);assert.equal(r.clock,120);});
test('one-device tournaments serialize fixtures instead of timing out other tables',()=>{const ids=names(10),r=T.create({id:'single',owner:'p0',format:'league',sequential:true,now:100000});ids.forEach(id=>{T.join(r,id,id,100000);T.ready(r,id,true,1);});T.start(r,'p0',ids,100000);let now=100000,n=0;while(r.status==='RUNNING'&&n++<150){const available=r.fixtures.filter(f=>['READY','PLAYING'].includes(f.status));assert.equal(available.length,1);const f=available[0];now=f.opens;f.players.forEach(p=>T.readyGame(r,f.id,p,now));T.resign(r,f.id,f.players.slice().sort().at(-1),now+1);}assert.equal(r.status,'COMPLETE');assert.equal(r.ranking.length,10);});
