/* Matchmaking process state: tickets, matched-result cache, storage reads and pairing writes.
 * The approved pure policy (windows, eligibility, scoring, cohort choice, seeding) lives once in
 * packages/domain/matchmaking.js and is reused here, so there is no second copy of its constants.
 */
'use strict';
const crypto=require('node:crypto');
/* The frozen package entry publishes the one approved policy definition and principal helper. */
const {domain:D,matchmaking:P,matchmakerPrincipal}=require('../packages/domain');
const {CONFIG,expected,quality,casualSkill,skill,searchWindow,compatibility,tournamentWindow,selectTournamentRoom,tournamentSeed}=P;
const sec=P.sec;
class Matchmaker{
 constructor({store,now=()=>Date.now(),makeId=()=>crypto.randomUUID(),maxTickets=5000}={}){if(!store)throw Error('STORE_REQUIRED');this.store=store;this.now=now;this.makeId=makeId;this.maxTickets=maxTickets;this.tickets=new Map();this.results=new Map();}
 _context(context={}){const latency=Number(context.latencyMs);return {region:P.normalizedRegion(context.region),latencyMs:Number.isFinite(latency)?Math.max(0,Math.min(1000,latency)):null};}
 status(actor){let found=this.results.get(actor);if(found){try{const m=this.store.read().view(found.matchId);if(['OFFERED','PLAYING'].includes(m.status))return structuredClone(found);}catch{}this.results.delete(actor);found=null;}const t=this.tickets.get(actor);return t?{state:'searching',mode:t.mode,joinedAt:t.joinedAt,waitSeconds:Math.floor(sec(t,this.now())),window:searchWindow(t.mode,sec(t,this.now()),this.store.read().account(actor))}:{state:'idle'};}
 cancel(actor){if(this.results.has(actor))return {state:'matched',...structuredClone(this.results.get(actor))};const removed=this.tickets.delete(actor);return {state:removed?'cancelled':'idle'};}
 enqueue(actor,mode,key,context={}){if(!['ranked','casual'].includes(mode))throw Error('INVALID_MODE');const a=this.store.read().account(actor);if(!a.verified||a.suspended||a.hold||a.activeMatch)throw Error('INELIGIBLE');if(this.tickets.size>=this.maxTickets&&!this.tickets.has(actor))throw Error('QUEUE_FULL');const prior=this.results.get(actor);if(prior)return structuredClone(prior);if(!this.tickets.has(actor))this.tickets.set(actor,{actor,mode,joinedAt:this.now(),key:String(key||''),...this._context(context)});else if(this.tickets.get(actor).mode!==mode)throw Error('ALREADY_QUEUED');this.sweep(mode);return this.status(actor);}
 sweep(mode=null){const modes=mode?[mode]:['ranked','casual'];for(const m of modes){let progress=true;while(progress){progress=false;const auth=this.store.read(),tickets=[...this.tickets.values()].filter(t=>t.mode===m).sort((a,b)=>a.joinedAt-b.joinedAt||a.actor.localeCompare(b.actor));for(const ta of tickets){if(!this.tickets.has(ta.actor))continue;let A;try{A=auth.account(ta.actor);}catch{this.tickets.delete(ta.actor);continue;}let best=null;for(const tb of tickets){if(tb.actor===ta.actor||!this.tickets.has(tb.actor))continue;let B;try{B=auth.account(tb.actor);}catch{continue;}const c=compatibility(A,B,ta,tb,m,this.now());if(!c.ok)continue;if(m==='ranked'){const q=D.quote({mode:'ranked',from:auth.currentTier(A),to:auth.currentTier(B)});if(A.coins<q.fee||B.coins<q.fee)continue;}if(!best||c.score<best.c.score||(c.score===best.c.score&&tb.joinedAt<best.ticket.joinedAt))best={ticket:tb,c};}if(!best)continue;const tb=best.ticket,id='queue:'+this.makeId(),turnSeconds=m==='ranked'?30:60;try{const match=this.store.run(matchmakerPrincipal(),'pair:'+id,{type:'queue',id,a:ta.actor,b:tb.actor,mode:m,turnSeconds});this.tickets.delete(ta.actor);this.tickets.delete(tb.actor);const result={state:'matched',mode:m,matchId:id,termsHash:match.termsHash,expires:match.expires,quality:best.c.quality,ratingGap:best.c.gap};this.results.set(ta.actor,result);this.results.set(tb.actor,result);progress=true;break;}catch(e){if(['RATED_PAIR_LIMIT','INELIGIBLE','ALREADY_IN_MATCH'].includes(e.message))continue;throw e;}}}}}
 tick(){this.sweep();return {queued:this.tickets.size,matched:this.results.size};}
 consume(actor){const x=this.results.get(actor);if(x)this.results.delete(actor);return x?structuredClone(x):null;}
}
module.exports={CONFIG,expected,quality,casualSkill,skill,searchWindow,compatibility,tournamentWindow,selectTournamentRoom,tournamentSeed,matchmakerPrincipal,Matchmaker};
