/* V3.5 account-bound cosmetics, verified purchases and rewarded-ad tickets.
 * Shares the economy SQLite transaction; no browser-supplied reward is trusted. */
'use strict';
const crypto=require('node:crypto'),D=require('../src/domain.js'),M=require('../src/monetization.js');
const {StoreBindings}=require('./store-bindings.js');
const {V35_COMMANDS}=require('../packages/db/scopes');
const idOK=s=>typeof s==='string'&&/^[A-Za-z0-9:_-]{1,160}$/.test(s);
function state(a){return a.monetization||(a.monetization={credits:0,redeemed:[],equipped:'classic',boosts:[],daily:{},lastAdAt:0,lastRewardStart:0});}
class MonetizationStore{
 constructor(store,{now=store.options.now||Date.now,eligible=()=>false,purchasesEnabled=false,verifyPurchase=store.options.verifyPurchase,purchaseProvider=null,adMode='off',adUnit='',adUnits={},rewardItem='cosmetic_reward',verifyAd=null,busy=()=>false}={}){
  M.cohort('validate',adMode);const normalized={};for(const [platform,value] of Object.entries(adUnits||{})){if(!['android','ios'].includes(platform)||!value||typeof value!=='object')continue;const rewarded=typeof value.rewarded==='string'?value.rewarded:'',interstitial=typeof value.interstitial==='string'?value.interstitial:'';if(rewarded||interstitial)normalized[platform]={rewarded,interstitial};}if(adUnit)normalized.legacy={rewarded:adUnit,interstitial:adUnit};Object.assign(this,{store,db:store.db,now,eligible,purchasesEnabled,verifyPurchase,purchaseProvider,adMode,adUnit,adUnits:Object.freeze(normalized),rewardItem,verifyAd,busy});
  this.bindings=purchaseProvider?new StoreBindings(this.db,{now}):null;
  this.db.exec(`CREATE TABLE IF NOT EXISTS v35_commands(actor TEXT,key TEXT,fingerprint TEXT,response TEXT,PRIMARY KEY(actor,key));
   CREATE TABLE IF NOT EXISTS v35_tickets(id TEXT PRIMARY KEY,actor TEXT,kind TEXT,issued INTEGER,expires INTEGER,day TEXT,settled INTEGER DEFAULT 0,transaction_id TEXT UNIQUE);
   CREATE TABLE IF NOT EXISTS v35_casual(actor TEXT,match_id TEXT,base INTEGER,bonus INTEGER,PRIMARY KEY(actor,match_id));
   CREATE TABLE IF NOT EXISTS v35_events(id INTEGER PRIMARY KEY,actor TEXT,kind TEXT,at INTEGER,value INTEGER);
   CREATE TABLE IF NOT EXISTS v41_ad_ticket_context(ticket TEXT PRIMARY KEY,platform TEXT NOT NULL,ad_unit TEXT NOT NULL);`);
 }
 account(a,id){const p=a.account(id);if(!p.verified)throw Error('LINK_ACCOUNT_REQUIRED');if(p.suspended||p.hold)throw Error('ACCOUNT_HELD');return p;}
 allowed(p){return this.eligible(structuredClone(p))===true;}
 owned(a,p){const frames=new Set(['classic',...state(p).redeemed]);for(const f of M.FRAMES)if((p.owned||[]).includes(f.name))frames.add(f.id);const products=[];for(const r of a.receipts.values())if(r.actor===p.id&&!r.refunded){const q=M.product(r.productId);if(q){if(q.once)products.push(q.id);q.frames.forEach(f=>frames.add(f));}}return {frames:[...frames],products:[...new Set(products)],removeAds:products.includes('remove_ads')};}
 event(actor,kind,value=0){this.db.prepare('INSERT INTO v35_events(actor,kind,at,value) VALUES(?,?,?,?)').run(actor,kind,this.now(),value);}
 transaction(actor,key,command,fn){
  if(!idOK(key))throw Error('IDEMPOTENCY_KEY_REQUIRED');const fingerprint=crypto.createHash('sha256').update(JSON.stringify(command)).digest('hex');
  return this.store.uow.run(tx=>{const repositories=tx.repositories,a=repositories.domain().authority,p=this.account(a,actor),old=repositories.outcomes.find(V35_COMMANDS,actor,key);if(old){if(old.fingerprint!==fingerprint)throw Error('IDEMPOTENCY_CONFLICT');return JSON.parse(old.response);}const result=fn(a,p);repositories.commitDomain();repositories.outcomes.save(V35_COMMANDS,actor,key,fingerprint,JSON.stringify(result));return result;});
 }
 status(actor){const a=this.store.read(),p=this.account(a,actor),s=state(p),owned=this.owned(a,p),now=this.now(),allowed=this.allowed(p),platforms=Object.entries(this.adUnits).filter(([,v])=>v.rewarded).map(([k])=>k),adMode=allowed&&platforms.length&&typeof this.verifyAd==='function'?M.cohort(actor,this.adMode):'off',verifier=this.purchaseProvider||this.verifyPurchase;const used=this.ticketCount(actor,M.day(now),now),purchasesAvailable=allowed&&this.purchasesEnabled&&!!verifier;return {actor,serverNow:now,credits:s.credits,...owned,equipped:owned.frames.includes(s.equipped)?s.equipped:'classic',boost:s.boosts.find(b=>b.endsAt>now)||null,rewardedRemaining:Math.max(0,M.POLICY.rewardedDayCap-used),rewardReadyAt:s.lastRewardStart+M.POLICY.rewardedGap,adMode,purchasesAvailable,storeContext:purchasesAvailable&&this.bindings?this.bindings.get(actor):null,stores:purchasesAvailable&&this.purchaseProvider?.stores?this.purchaseProvider.stores():[],adPlatforms:adMode==='off'?[]:platforms,policy:M.POLICY};}
 ticketCount(actor,day,now){return this.db.prepare('SELECT count(*) AS n FROM v35_tickets WHERE actor=? AND day=?').get(actor,day).n;}
 claim(actor,key){return this.transaction(actor,key,{type:'claim'},(a,p)=>{const s=state(p);let base=0,bonus=0;for(const h of [...p.history].sort((a,b)=>a.at-b.at)){if(!M.qualifiedCasual(h)||h.at>this.now()||this.db.prepare('SELECT 1 FROM v35_casual WHERE actor=? AND match_id=?').get(actor,h.id))continue;const d=s.daily[M.day(h.at)]||(s.daily[M.day(h.at)]={base:0,bonus:0,automatic:0});const b=Math.min(M.POLICY.casualCredits,Math.max(0,M.POLICY.casualDayCap-d.base)),x=b&&s.boosts.some(boost=>M.boostApplies(Number.isFinite(a.matches.get(h.id)?.started)?{...h,activeSeconds:(h.at-a.matches.get(h.id).started)/1000}:h,boost))?Math.min(b,Math.max(0,M.POLICY.boostDayCap-d.bonus)):0;d.base+=b;d.bonus+=x;base+=b;bonus+=x;this.db.prepare('INSERT INTO v35_casual VALUES(?,?,?,?)').run(actor,h.id,b,x);}s.credits=D.add(s.credits,base+bonus);if(base+bonus)this.event(actor,'casual_credits',base+bonus);return {base,bonus,credits:s.credits};});}
 cosmetic(actor,key,id,equip=false){return this.transaction(actor,key,{type:equip?'equip':'redeem',id},(a,p)=>{const f=M.frame(id),s=state(p);if(!f)throw Error('INVALID_FRAME');const owned=this.owned(a,p).frames.includes(id);if(!owned){if(equip||f.credits===null)throw Error('FRAME_NOT_OWNED');if(s.credits<f.credits)throw Error('INSUFFICIENT_COSMETIC_CREDITS');s.credits-=f.credits;s.redeemed.push(id);this.event(actor,'cosmetic_redeemed',f.credits);}s.equipped=id;return {equipped:id,credits:s.credits};});}
 async purchase(actor,key,evidence,restore=false){
  const p=this.account(this.store.read(),actor),verifier=this.purchaseProvider||this.verifyPurchase;if(!verifier)throw Error('STORE_UNAVAILABLE');if(!restore&&(!this.purchasesEnabled||!this.allowed(p)))throw Error('PURCHASE_UNAVAILABLE');
  const receipt=this.purchaseProvider?await this.purchaseProvider.verify(evidence,actor,this.bindings.get(actor)):await this.verifyPurchase(evidence,actor);
  if(!receipt||receipt.valid!==true||receipt.accountId!==actor||receipt.refunded||!['apple','google'].includes(receipt.store)||!idOK(receipt.transactionId))throw Error('INVALID_RECEIPT');
  if(this.store.repositories().purchases.revoked(receipt.store,receipt.transactionId))throw Error('RECEIPT_REFUNDED');
  const product=M.product(receipt.productId);if(!product||restore&&!product.once)throw Error('INVALID_PRODUCT');
  const safeReceipt={valid:true,accountId:receipt.accountId,store:receipt.store,transactionId:receipt.transactionId,productId:receipt.productId,refunded:false};
  const result=this.transaction(actor,key,{type:restore?'restore':'purchase',receipt:safeReceipt},(a,p)=>{if(!restore&&(!this.purchasesEnabled||!this.allowed(p)))throw Error('PURCHASE_UNAVAILABLE');const id=receipt.store+':'+receipt.transactionId,old=a.receipts.get(id);if(old){if(old.actor!==actor||old.productId!==product.id)throw Error('RECEIPT_REPLAY');if(old.refunded)throw Error('RECEIPT_REFUNDED');return {productId:product.id,duplicate:true};}if(product.once){const previous=[...a.receipts.values()].find(r=>r.actor===actor&&r.productId===product.id);if(previous){if(previous.refunded)throw Error('PRODUCT_PREVIOUSLY_REFUNDED');return {productId:product.id,alreadyOwned:true};}}p.crowns=D.add(p.crowns,product.crowns);if(product.crowns)p.purchaseInfluenced=true;a.receipts.set(id,{actor,productId:product.id,crowns:product.crowns,refunded:false,at:this.now()});if(product.crowns)a._entry('purchase:'+id,actor,'crowns',product.crowns,'Crown purchase','verified-store');this.event(actor,restore?'purchase_restored':'purchase_verified',product.crowns);return {productId:product.id,crowns:product.crowns,duplicate:false};});
  if(this.purchaseProvider?.finalize){const finalized=await this.purchaseProvider.finalize(receipt).catch(()=>false);if(!finalized)return {...result,finalizationPending:true};}
  return result;
 }
 async processPurchaseFinalizations(){if(!this.purchaseProvider?.processDue)return {processed:0,completed:0};return this.purchaseProvider.processDue((store,id)=>this.store.read().receipts.has(store+':'+id));}
 assertAdSafe(p,platform,kind='rewarded'){const units=this.adUnits[platform];if(!this.allowed(p)||!units||!units[kind]||typeof this.verifyAd!=='function'||M.cohort(p.id,this.adMode)==='off')throw Error('ADS_UNAVAILABLE');if(p.activeMatch||this.busy(p.id))throw Error('MATCH_ACTIVE');return units[kind];}
 ticket(actor,key,kind,platform='legacy'){return this.transaction(actor,key,{type:'ticket',kind,platform},(a,p)=>{const adUnit=this.assertAdSafe(p,platform,'rewarded');if(!['credits','boost'].includes(kind))throw Error('INVALID_REWARD');const now=this.now(),s=state(p);if(now-s.lastRewardStart<M.POLICY.rewardedGap)throw Error('AD_COOLDOWN');if(kind==='boost'&&s.boosts.some(b=>b.endsAt>now))throw Error('BOOST_ACTIVE');if(kind==='boost'&&this.db.prepare("SELECT 1 FROM v35_tickets WHERE actor=? AND kind='boost' AND settled=0 AND expires>?").get(actor,now-M.POLICY.callbackGrace))throw Error('AD_PENDING');if(this.ticketCount(actor,M.day(now),now)>=M.POLICY.rewardedDayCap)throw Error('AD_DAILY_LIMIT');if(this.db.prepare('SELECT 1 FROM v35_tickets WHERE actor=? AND settled=0 AND expires>?').get(actor,now))throw Error('AD_PENDING');const id=crypto.randomBytes(24).toString('hex'),expires=now+M.POLICY.ticketLifetime;this.db.prepare('INSERT INTO v35_tickets(id,actor,kind,issued,expires,day) VALUES(?,?,?,?,?,?)').run(id,actor,kind,now,expires,M.day(now));this.db.prepare('INSERT INTO v41_ad_ticket_context(ticket,platform,ad_unit) VALUES(?,?,?)').run(id,platform,adUnit);s.lastRewardStart=now;s.lastAdAt=now;this.event(actor,'reward_requested');return {ticket:id,actor,kind,platform,expires,adUnit,rewardItem:this.rewardItem,rewardAmount:1};});}
 async callback(raw){if(typeof this.verifyAd!=='function')throw Error('ADS_UNAVAILABLE');const e=await this.verifyAd(raw);if(!e||typeof e.transactionId!=='string'||e.transactionId.length>200||e.rewardItem!==this.rewardItem||e.amount!==1||!Number.isSafeInteger(e.timestamp))throw Error('INVALID_AD_REWARD');const digest=crypto.createHash('sha256').update(e.transactionId).digest('hex');return this.transaction(e.actor,'ssv:'+digest,{type:'ssv',event:e},(a,p)=>{const row=this.db.prepare('SELECT * FROM v35_tickets WHERE id=?').get(e.ticket),ctx=this.db.prepare('SELECT platform,ad_unit FROM v41_ad_ticket_context WHERE ticket=?').get(e.ticket);if(!row||!ctx||ctx.ad_unit!==e.adUnit||row.actor!==e.actor||e.timestamp<row.issued||e.timestamp>row.expires||e.timestamp>this.now()+60000||this.now()-e.timestamp>M.POLICY.callbackGrace)throw Error('INVALID_AD_TICKET');if(row.settled)throw Error('AD_TICKET_USED');if(this.db.prepare('SELECT 1 FROM v35_tickets WHERE transaction_id=?').get(e.transactionId))throw Error('AD_TRANSACTION_USED');const s=state(p);if(row.kind==='credits')s.credits=D.add(s.credits,M.POLICY.rewardCredits);else{if(s.boosts.some(b=>b.endsAt>this.now()))throw Error('BOOST_ACTIVE');s.boosts.push({startedAt:this.now(),endsAt:this.now()+M.POLICY.boostDuration});}s.lastAdAt=this.now();this.db.prepare('UPDATE v35_tickets SET settled=1,transaction_id=? WHERE id=?').run(e.transactionId,row.id);this.event(p.id,'reward_verified',row.kind==='credits'?M.POLICY.rewardCredits:0);return {granted:row.kind,credits:s.credits,boost:row.kind==='boost'?s.boosts.at(-1):null};});}
 automaticPermit(actor,key,platform='legacy'){return this.transaction(actor,key,{type:'automatic-permit',platform},(a,p)=>{const adUnit=this.assertAdSafe(p,platform,'interstitial');if(M.cohort(actor,this.adMode)!=='hybrid'||this.owned(a,p).removeAds)throw Error('AUTOMATIC_AD_DISABLED');const s=state(p),now=this.now(),d=s.daily[M.day(now)]||(s.daily[M.day(now)]={base:0,bonus:0,automatic:0});if(now-p.createdAt<M.POLICY.firstAdAge||now-s.lastAdAt<M.POLICY.fullScreenGap)throw Error('AD_COOLDOWN');if(d.automatic>=M.POLICY.interstitialDayCap)throw Error('AD_DAILY_LIMIT');s.lastAdAt=now;d.automatic++;this.event(actor,'interstitial_permitted');return {allowed:true,platform,adUnit,expires:now+3000};});}
 /* Trusted store-notification integration only. Never mount as a player endpoint. */
 refund(store,transactionId){
  return this.store.uow.run(tx=>{const repositories=tx.repositories,a=repositories.domain().authority,id=store+':'+transactionId,r=a.receipts.get(id);if(!r)throw Error('UNKNOWN_RECEIPT');if(r.refunded)return {refunded:true,duplicate:true};r.refunded=true;const account=a.accounts.get(r.actor);if(r.crowns&&account)account.hold=true;repositories.commitDomain();this.event(r.actor,'purchase_refunded');return {refunded:true,accountHeld:!!(r.crowns&&account),duplicate:false};});
 } report(){return this.db.prepare('SELECT kind,count(*) AS events,sum(value) AS value FROM v35_events GROUP BY kind').all();}
}
module.exports={MonetizationStore};
