/* V3.5 account-bound cosmetics, verified purchases and rewarded-ad tickets.
 * Shares the economy SQLite transaction; no browser-supplied reward is trusted. */
'use strict';
const crypto=require('node:crypto'),D=require('../src/domain.js'),M=require('../src/monetization.js');
const idOK=s=>typeof s==='string'&&/^[A-Za-z0-9:_-]{1,160}$/.test(s);
function state(a){return a.monetization||(a.monetization={credits:0,redeemed:[],equipped:'classic',boosts:[],daily:{},lastAdAt:0,lastRewardStart:0});}
class MonetizationStore{
 constructor(store,{now=store.options.now||Date.now,eligible=()=>false,purchasesEnabled=false,verifyPurchase=store.options.verifyPurchase,adMode='off',adUnit='',rewardItem='cosmetic_reward',verifyAd=null,busy=()=>false}={}){
  M.cohort('validate',adMode);Object.assign(this,{store,db:store.db,now,eligible,purchasesEnabled,verifyPurchase,adMode,adUnit,rewardItem,verifyAd,busy});
  this.db.exec(`CREATE TABLE IF NOT EXISTS v35_commands(actor TEXT,key TEXT,fingerprint TEXT,response TEXT,PRIMARY KEY(actor,key));
   CREATE TABLE IF NOT EXISTS v35_tickets(id TEXT PRIMARY KEY,actor TEXT,kind TEXT,issued INTEGER,expires INTEGER,day TEXT,settled INTEGER DEFAULT 0,transaction_id TEXT UNIQUE);
   CREATE TABLE IF NOT EXISTS v35_casual(actor TEXT,match_id TEXT,base INTEGER,bonus INTEGER,PRIMARY KEY(actor,match_id));
   CREATE TABLE IF NOT EXISTS v35_events(id INTEGER PRIMARY KEY,actor TEXT,kind TEXT,at INTEGER,value INTEGER);`);
 }
 account(a,id){const p=a.account(id);if(!p.verified)throw Error('LINK_ACCOUNT_REQUIRED');if(p.suspended||p.hold)throw Error('ACCOUNT_HELD');return p;}
 allowed(p){return this.eligible(structuredClone(p))===true;}
 owned(a,p){const frames=new Set(['classic',...state(p).redeemed]);for(const f of M.FRAMES)if((p.owned||[]).includes(f.name))frames.add(f.id);const products=[];for(const r of a.receipts.values())if(r.actor===p.id&&!r.refunded){const q=M.product(r.productId);if(q){if(q.once)products.push(q.id);q.frames.forEach(f=>frames.add(f));}}return {frames:[...frames],products:[...new Set(products)],removeAds:products.includes('remove_ads')};}
 event(actor,kind,value=0){this.db.prepare('INSERT INTO v35_events(actor,kind,at,value) VALUES(?,?,?,?)').run(actor,kind,this.now(),value);}
 transaction(actor,key,command,fn){
  if(!idOK(key))throw Error('IDEMPOTENCY_KEY_REQUIRED');const fingerprint=crypto.createHash('sha256').update(JSON.stringify(command)).digest('hex');
  this.db.exec('BEGIN IMMEDIATE');try{const a=this.store.read(),p=this.account(a,actor),old=this.db.prepare('SELECT * FROM v35_commands WHERE actor=? AND key=?').get(actor,key);if(old){if(old.fingerprint!==fingerprint)throw Error('IDEMPOTENCY_CONFLICT');this.db.exec('COMMIT');return JSON.parse(old.response);}const result=fn(a,p);this.db.prepare('UPDATE state SET json=? WHERE id=1').run(JSON.stringify(a.export()));this.db.prepare('INSERT INTO v35_commands VALUES(?,?,?,?)').run(actor,key,fingerprint,JSON.stringify(result));this.db.exec('COMMIT');return result;}catch(e){this.db.exec('ROLLBACK');throw e;}
 }
 status(actor){const a=this.store.read(),p=this.account(a,actor),s=state(p),owned=this.owned(a,p),now=this.now(),allowed=this.allowed(p),adMode=allowed&&this.adUnit&&typeof this.verifyAd==='function'?M.cohort(actor,this.adMode):'off';const used=this.ticketCount(actor,M.day(now),now);return {actor,serverNow:now,credits:s.credits,...owned,equipped:owned.frames.includes(s.equipped)?s.equipped:'classic',boost:s.boosts.find(b=>b.endsAt>now)||null,rewardedRemaining:Math.max(0,M.POLICY.rewardedDayCap-used),rewardReadyAt:s.lastRewardStart+M.POLICY.rewardedGap,adMode,purchasesAvailable:allowed&&this.purchasesEnabled&&typeof this.verifyPurchase==='function',adUnit:adMode==='off'?null:this.adUnit,policy:M.POLICY};}
 ticketCount(actor,day,now){return this.db.prepare('SELECT count(*) AS n FROM v35_tickets WHERE actor=? AND day=?').get(actor,day).n;}
 claim(actor,key){return this.transaction(actor,key,{type:'claim'},(a,p)=>{const s=state(p);let base=0,bonus=0;for(const h of [...p.history].sort((a,b)=>a.at-b.at)){if(!M.qualifiedCasual(h)||h.at>this.now()||this.db.prepare('SELECT 1 FROM v35_casual WHERE actor=? AND match_id=?').get(actor,h.id))continue;const d=s.daily[M.day(h.at)]||(s.daily[M.day(h.at)]={base:0,bonus:0,automatic:0});const b=Math.min(M.POLICY.casualCredits,Math.max(0,M.POLICY.casualDayCap-d.base)),x=b&&s.boosts.some(boost=>M.boostApplies(Number.isFinite(a.matches.get(h.id)?.started)?{...h,activeSeconds:(h.at-a.matches.get(h.id).started)/1000}:h,boost))?Math.min(b,Math.max(0,M.POLICY.boostDayCap-d.bonus)):0;d.base+=b;d.bonus+=x;base+=b;bonus+=x;this.db.prepare('INSERT INTO v35_casual VALUES(?,?,?,?)').run(actor,h.id,b,x);}s.credits=D.add(s.credits,base+bonus);if(base+bonus)this.event(actor,'casual_credits',base+bonus);return {base,bonus,credits:s.credits};});}
 cosmetic(actor,key,id,equip=false){return this.transaction(actor,key,{type:equip?'equip':'redeem',id},(a,p)=>{const f=M.frame(id),s=state(p);if(!f)throw Error('INVALID_FRAME');const owned=this.owned(a,p).frames.includes(id);if(!owned){if(equip||f.credits===null)throw Error('FRAME_NOT_OWNED');if(s.credits<f.credits)throw Error('INSUFFICIENT_COSMETIC_CREDITS');s.credits-=f.credits;s.redeemed.push(id);this.event(actor,'cosmetic_redeemed',f.credits);}s.equipped=id;return {equipped:id,credits:s.credits};});}
 async purchase(actor,key,evidence,restore=false){
  const p=this.account(this.store.read(),actor);if(typeof this.verifyPurchase!=='function')throw Error('STORE_UNAVAILABLE');if(!restore&&(!this.purchasesEnabled||!this.allowed(p)))throw Error('PURCHASE_UNAVAILABLE');
  const receipt=await this.verifyPurchase(evidence,actor);if(!receipt||receipt.valid!==true||receipt.accountId!==actor||receipt.refunded||!['apple','google'].includes(receipt.store)||!idOK(receipt.transactionId))throw Error('INVALID_RECEIPT');const product=M.product(receipt.productId);if(!product||restore&&!product.once)throw Error('INVALID_PRODUCT');
  return this.transaction(actor,key,{type:restore?'restore':'purchase',receipt},(a,p)=>{if(!restore&&(!this.purchasesEnabled||!this.allowed(p)))throw Error('PURCHASE_UNAVAILABLE');const id=receipt.store+':'+receipt.transactionId,old=a.receipts.get(id);if(old){if(old.actor!==actor||old.productId!==product.id)throw Error('RECEIPT_REPLAY');if(old.refunded)throw Error('RECEIPT_REFUNDED');return {productId:product.id,duplicate:true};}if(product.once){const previous=[...a.receipts.values()].find(r=>r.actor===actor&&r.productId===product.id);if(previous){if(previous.refunded)throw Error('PRODUCT_PREVIOUSLY_REFUNDED');return {productId:product.id,alreadyOwned:true};}}p.crowns=D.add(p.crowns,product.crowns);if(product.crowns)p.purchaseInfluenced=true;a.receipts.set(id,{actor,productId:product.id,crowns:product.crowns,refunded:false,at:this.now()});if(product.crowns)a._entry('purchase:'+id,actor,'crowns',product.crowns,'Crown purchase','verified-store');this.event(actor,restore?'purchase_restored':'purchase_verified',product.crowns);return {productId:product.id,crowns:product.crowns,duplicate:false};});
 }
 assertAdSafe(p){if(!this.allowed(p)||!this.adUnit||typeof this.verifyAd!=='function'||M.cohort(p.id,this.adMode)==='off')throw Error('ADS_UNAVAILABLE');if(p.activeMatch||this.busy(p.id))throw Error('MATCH_ACTIVE');}
 ticket(actor,key,kind){return this.transaction(actor,key,{type:'ticket',kind},(a,p)=>{this.assertAdSafe(p);if(!['credits','boost'].includes(kind))throw Error('INVALID_REWARD');const now=this.now(),s=state(p);if(now-s.lastRewardStart<M.POLICY.rewardedGap)throw Error('AD_COOLDOWN');if(kind==='boost'&&s.boosts.some(b=>b.endsAt>now))throw Error('BOOST_ACTIVE');if(kind==='boost'&&this.db.prepare("SELECT 1 FROM v35_tickets WHERE actor=? AND kind='boost' AND settled=0 AND expires>?").get(actor,now-M.POLICY.callbackGrace))throw Error('AD_PENDING');if(this.ticketCount(actor,M.day(now),now)>=M.POLICY.rewardedDayCap)throw Error('AD_DAILY_LIMIT');if(this.db.prepare('SELECT 1 FROM v35_tickets WHERE actor=? AND settled=0 AND expires>?').get(actor,now))throw Error('AD_PENDING');const id=crypto.randomBytes(24).toString('hex'),expires=now+M.POLICY.ticketLifetime;this.db.prepare('INSERT INTO v35_tickets(id,actor,kind,issued,expires,day) VALUES(?,?,?,?,?,?)').run(id,actor,kind,now,expires,M.day(now));s.lastRewardStart=now;s.lastAdAt=now;this.event(actor,'reward_requested');return {ticket:id,actor,kind,expires,adUnit:this.adUnit,rewardItem:this.rewardItem,rewardAmount:1};});}
 async callback(raw){if(typeof this.verifyAd!=='function')throw Error('ADS_UNAVAILABLE');const e=await this.verifyAd(raw);if(!e||typeof e.transactionId!=='string'||e.transactionId.length>200||e.adUnit!==this.adUnit||e.rewardItem!==this.rewardItem||e.amount!==1||!Number.isSafeInteger(e.timestamp))throw Error('INVALID_AD_REWARD');const digest=crypto.createHash('sha256').update(e.transactionId).digest('hex');return this.transaction(e.actor,'ssv:'+digest,{type:'ssv',event:e},(a,p)=>{const row=this.db.prepare('SELECT * FROM v35_tickets WHERE id=?').get(e.ticket);if(!row||row.actor!==e.actor||e.timestamp<row.issued||e.timestamp>row.expires||e.timestamp>this.now()+60000||this.now()-e.timestamp>M.POLICY.callbackGrace)throw Error('INVALID_AD_TICKET');if(row.settled)throw Error('AD_TICKET_USED');if(this.db.prepare('SELECT 1 FROM v35_tickets WHERE transaction_id=?').get(e.transactionId))throw Error('AD_TRANSACTION_USED');const s=state(p);if(row.kind==='credits')s.credits=D.add(s.credits,M.POLICY.rewardCredits);else{if(s.boosts.some(b=>b.endsAt>this.now()))throw Error('BOOST_ACTIVE');s.boosts.push({startedAt:this.now(),endsAt:this.now()+M.POLICY.boostDuration});}s.lastAdAt=this.now();this.db.prepare('UPDATE v35_tickets SET settled=1,transaction_id=? WHERE id=?').run(e.transactionId,row.id);this.event(p.id,'reward_verified',row.kind==='credits'?M.POLICY.rewardCredits:0);return {granted:row.kind,credits:s.credits,boost:row.kind==='boost'?s.boosts.at(-1):null};});}
 automaticPermit(actor,key){return this.transaction(actor,key,{type:'automatic-permit'},(a,p)=>{this.assertAdSafe(p);if(M.cohort(actor,this.adMode)!=='hybrid'||this.owned(a,p).removeAds)throw Error('AUTOMATIC_AD_DISABLED');const s=state(p),now=this.now(),d=s.daily[M.day(now)]||(s.daily[M.day(now)]={base:0,bonus:0,automatic:0});if(now-p.createdAt<M.POLICY.firstAdAge||now-s.lastAdAt<M.POLICY.fullScreenGap)throw Error('AD_COOLDOWN');if(d.automatic>=M.POLICY.interstitialDayCap)throw Error('AD_DAILY_LIMIT');s.lastAdAt=now;d.automatic++;this.event(actor,'interstitial_permitted');return {allowed:true,expires:now+3000};});}
 /* Trusted store-notification integration only. Never mount as a player endpoint. */
 refund(store,transactionId){this.db.exec('BEGIN IMMEDIATE');try{const a=this.store.read(),id=store+':'+transactionId,r=a.receipts.get(id);if(!r)throw Error('UNKNOWN_RECEIPT');r.refunded=true;if(r.crowns)a.account(r.actor).hold=true;this.db.prepare('UPDATE state SET json=? WHERE id=1').run(JSON.stringify(a.export()));this.event(r.actor,'purchase_refunded');this.db.exec('COMMIT');return {refunded:true};}catch(e){this.db.exec('ROLLBACK');throw e;}}
 report(){return this.db.prepare('SELECT kind,count(*) AS events,sum(value) AS value FROM v35_events GROUP BY kind').all();}
}
module.exports={MonetizationStore};
