/* V3.2 local prototype. Online identity, purchases and coin stakes fail closed. */
(()=>{
'use strict';
const G=window.MegaGame,D=window.MegaDomain,I=window.MegaIcons,$=s=>document.querySelector(s);
const KEY='mega_v32_state',escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parse=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}};
let data=parse(KEY);if(!data||data.version!==3.2){data=D.fresh();const old=parse('mega_v3_settings');if(old){Object.assign(data.settings,old);data.settings.haptics=old.haptic!==false;}data.legacy=parse('mega_v3_stats');}
data.playSeconds=data.playSeconds||{};
data.profile=data.profile||{};
if(!data.profile.friendCode){
 const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let code='MEGA-';
 for(let i=0;i<4;i++)code+=chars[Math.floor(Math.random()*chars.length)];
 data.profile.friendCode=code;
}
if(!['vector','dark','paper','neon'].includes(data.settings.theme))data.settings.theme='vector';
let page='play',mode='bot',difficulty='Medium',first='X',onlineType='ranked',statsMode='bot',statsDifficulty='all',rankLeague='all',rankScope='global',rankMetric='rating',demo=false;
let match=null,botTimer=null,toastTimer=null,ctx=null,ambient=null,sheetKind='',lastTick=performance.now(),lastInput=performance.now(),lastSave=0;
const themeNames={vector:'Vector Light',dark:'Midnight Club',paper:'Paper Club',neon:'After Hours'};
const lightBadges=[['#ead9c5','#715234'],['#e3e8ed','#58646b'],['#dae3f0','#465c7d'],['#f4dfc6','#7c4b20'],['#e3edf4','#4a6276'],['#f5e7b2','#805b0c'],['#d7f0fa','#176d8a'],['#d7efdf','#23673f'],['#eed7f0','#784576'],['#e7defa','#644991'],['#faf0c7','#805b0c']];
const darkBadges=[['#42372d','#e4c49c'],['#343f48','#d0dce5'],['#283b53','#b8d1f7'],['#4a3526','#f0bf91'],['#314455','#d6eafa'],['#4c4123','#f2d88d'],['#173e52','#9ce2f8'],['#233e31','#a5e4bf'],['#442e49','#e7b8ee'],['#362b51','#d9c2fc'],['#514224','#fff0aa']];
const icon=n=>I.icon(n),badge=(t,large=false)=>{const c=(['dark','neon'].includes(data.settings.theme)?darkBadges:lightBadges)[t.index];return '<span class="badge-wrap" style="--badge-bg:'+c[0]+';--badge-ink:'+c[1]+'">'+I.badge(t,large)+'</span>';};
function refreshIcons(){requestAnimationFrame(()=>I.refresh?.());}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));}catch{notify('Storage is unavailable. Progress lasts for this session only.');}}
function notify(text){const t=$('#toast');t.textContent=text;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2800);}
function applyTheme(){document.documentElement.dataset.theme=data.settings.theme;document.documentElement.dataset.motion=data.settings.motion?'reduced':'full';document.querySelector('meta[name="theme-color"]').content=getComputedStyle(document.documentElement).getPropertyValue('--surface').trim();}
function tone(freq=500){if(!data.settings.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;ctx=ctx||new C();ctx.resume().catch(()=>{});const o=ctx.createOscillator(),a=ctx.createGain();o.type='sine';o.frequency.value=freq;a.gain.setValueAtTime(.035,ctx.currentTime);a.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);o.connect(a);a.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.14);}catch{}}
function syncAudio(){try{if(ambient){ambient.osc.stop();ambient=null;}if(!data.settings.music||document.hidden)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;ctx=ctx||new C();ctx.resume().catch(()=>{});const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=130.81;gain.gain.value=.004;osc.connect(gain);gain.connect(ctx.destination);osc.start();ambient={osc,gain};}catch{}}
function haptic(){if(data.settings.haptics&&navigator.vibrate)navigator.vibrate(10);}
const seconds=s=>{if(s===null||s===undefined)return '--';const n=Math.round(s);return Math.floor(n/60)+':'+String(n%60).padStart(2,'0');};
const button=(text,action,value='',quiet=false)=>'<button class="button '+(quiet?'quiet':'')+'" data-action="'+action+'" data-value="'+escape(value)+'">'+text+'</button>';
const fullButton=(text,action,value='',quiet=false)=>'<button class="button full '+(quiet?'quiet':'')+'" data-action="'+action+'" data-value="'+escape(value)+'">'+text+'</button>';
const opts=(items,selected)=>items.map(([value,label])=>'<option value="'+value+'" '+(value===selected?'selected':'')+'>'+label+'</option>').join('');
const field=(title,id,options)=>'<label class="field">'+title+'<select id="'+id+'">'+options+'</select></label>';
const empty=(symbol,title,text)=>'<div class="empty">'+icon(symbol)+'<h3>'+title+'</h3><p>'+text+'</p></div>';
function render(){
 $('#walletAmount').textContent=data.wallet.coins.toLocaleString();
 $('#navigation').innerHTML=[['play','Play','board'],['friends','Friends','users'],['rank','Rank','trophy'],['stats','Stats','chart'],['quests','Quests','quest']].map(([id,name,symbol])=>'<button class="nav-button '+(id===page?'active':'')+'" data-action="nav" data-value="'+id+'" '+(id===page?'aria-current="page"':'')+'>'+icon(symbol)+'<span>'+name+'</span></button>').join('');
 $('#page').innerHTML=({play:home,friends:friends,rank:ranks,stats:statsView,quests:quests})[page]();
 refreshIcons();
}
function home(){
 const desc={Beginner:'Learning the rules. Plenty of room to experiment.',Easy:'Spots simple wins and blocks.',Medium:'Looks ahead and considers where each move sends you next.',Hard:'Deeper search and fewer tactical mistakes.',Expert:'The strongest offline search, with the least room for mistakes.'}[difficulty];
 const chip=(label,action,value,active)=>'<button class="setup-chip '+(active?'active':'')+'" data-action="'+action+'" data-value="'+value+'">'+label+'</button>';
 const modes=[['bot','bot','Vs Bot','Five skill levels, fully offline'],['local','users','Pass & Play','Two players on one device'],['online','swords','Play Online','Ranked or casual matchmaking'],['private','link','Private Match','Create or join a friend room']];
 let setup='';
 if(mode==='bot') setup='<div class="setup old-setup"><div class="setup-block"><div class="setup-title"><b>Bot difficulty</b><span>Strategy depth</span></div><div class="setup-chips">'+G.LEVELS.map(x=>chip(x.toUpperCase(),'difficulty',x,difficulty===x)).join('')+'</div></div><div class="setup-block"><div class="setup-title"><b>First move</b><span>Who starts</span></div><div class="setup-chips two">'+chip('X STARTS','first','X',first==='X')+chip('O STARTS','first','O',first==='O')+'</div></div><div class="setup-block"><div class="setup-title"><b>Turn timer</b><span>Optional</span></div><div class="setup-chips three">'+[['0','OFF'],['30','30 SEC'],['60','60 SEC']].map(([v,l])=>chip(l,'settimer',v,String(data.settings.timer)===v)).join('')+'</div></div><p class="setup-note">'+desc+'</p></div>';
 else if(mode==='local') setup='<div class="setup old-setup"><div class="setup-block"><div class="setup-title"><b>First move</b><span>Who starts</span></div><div class="setup-chips two">'+chip('X STARTS','first','X',first==='X')+chip('O STARTS','first','O',first==='O')+'</div></div><div class="setup-block"><div class="setup-title"><b>Turn timer</b><span>Optional</span></div><div class="setup-chips three">'+[['0','OFF'],['30','30 SEC'],['60','60 SEC']].map(([v,l])=>chip(l,'settimer',v,String(data.settings.timer)===v)).join('')+'</div></div><p class="setup-note">Pass & Play stays off your personal stats, coins and rank.</p></div>';
 else if(mode==='online') setup='<div class="setup old-setup"><div class="setup-block"><div class="setup-title"><b>Match type</b><span>Choose your queue</span></div><div class="setup-chips two">'+chip('RANKED','onlinetype','ranked',onlineType==='ranked')+chip('CASUAL','onlinetype','casual',onlineType==='casual')+'</div></div><p class="setup-note">'+(onlineType==='ranked'?'Ranked changes Elo. Entry-coin rules remain disabled until the online service and review are complete.':'Casual is free and never changes Elo.')+'</p></div>';
 const cta=mode==='private'?'Open Private Lobby':mode==='online'?'Find Match':'Start Match';
 return '<div class="hero home-hero"><h1>Tic-tac-toe.<br><em>Think bigger.</em></h1><p>Win the small boards to win the big one. Every move also decides where your opponent plays next.</p></div>'+
 '<button class="card rank-summary" data-action="nav" data-value="rank">'+badge(D.TIERS[0])+'<span class="grow"><b>Your ranked journey starts here</b><small>Unranked &middot; 0 / 10 placement games</small></span>'+icon('arrow')+'</button>'+
 '<div class="section-heading"><h3>Choose mode</h3><span class="eyebrow">OFFLINE READY</span></div><div class="mode-list">'+modes.map(([id,sym,title,desc])=>'<button class="mode '+(id===mode?'active':'')+'" data-action="mode" data-value="'+id+'" aria-pressed="'+(id===mode)+'"><span class="mode-symbol">'+icon(sym)+'</span><span class="mode-copy"><strong>'+title+'</strong><small>'+desc+'</small></span>'+icon('arrow')+'</button>').join('')+'</div>'+setup+
 fullButton(icon('play')+cta,'start')+
 '<button class="learn" data-action="tutorial">'+icon('tutorial')+'<span><strong>New to Mega XO?</strong><small>Learn the rules in under a minute</small></span>'+icon('arrow')+'</button>'+
 '<div class="home-quests"><span><b>Daily quests</b><small>Earn coins through play.</small></span>'+button('View quests','nav','quests',true)+'</div>';
}
function friends(){
 return '<div class="panel-head friends-head"><div class="eyebrow">Social</div><h2>Friends</h2><p>Challenge people you know, or add someone you just played.</p></div>'+
 '<div class="friend-search"><div class="friend-search-wrap">'+icon('search')+'<input id="friendName" placeholder="Search username" maxlength="30" autocomplete="off"></div><button class="friend-add" data-action="findfriend">'+icon('userPlus')+'<span>Add</span></button></div>'+
 '<div class="friend-code-card"><div><span>YOUR FRIEND CODE</span><div class="friend-code">'+escape(data.profile.friendCode)+'</div></div><button class="copy-friend" data-action="copyfriend" aria-label="Copy friend code">'+icon('copy')+'</button></div>'+
 '<div class="section-title friends-section-title"><span>Friends</span><small>0 ONLINE</small></div>'+
 '<div class="friend-empty"><div class="friend-empty-icon">'+icon('usersRound')+'</div><b>Your squad is empty</b><p>Add a friend by username or share your code. Recent online opponents will also appear here once multiplayer is connected.</p></div>';
}
function statsView(){const a=D.aggregate(data.records,statsMode,statsDifficulty);return '<h2>Your game, in numbers</h2><p class="caption">Different opponents. Separate records.</p><div class="tabs">'+[['bot','Bot'],['ranked','Ranked'],['casual','Casual'],['friend','Friends']].map(([id,name])=>'<button class="tab '+(statsMode===id?'active':'')+'" data-action="statmode" data-value="'+id+'">'+name+'</button>').join('')+'</div>'+(statsMode==='bot'?field('Bot difficulty','statsDifficulty',opts([['all','All difficulties'],...G.LEVELS.map(x=>[x,x])],statsDifficulty)):'<div class="note">Online results require verified server match records. Offline games are never added here.</div>')+
 '<div class="section-heading"><h3>'+({bot:'Against the bot',ranked:'Ranked matches',casual:'Casual matches',friend:'Friend matches'}[statsMode])+'</h3><span class="eyebrow">'+a.games+' games</span></div><div class="stats-grid">'+[['Win rate',a.winRate===null?'--':(a.winRate*100).toFixed(1)+'%'],['Wins',a.wins],['Average game',seconds(a.averageSeconds)],['Hours played',((data.playSeconds[statsMode+':'+statsDifficulty]??a.hours*3600)/3600).toFixed(2)],['Losses',a.losses],['Draws',a.draws]].map(([label,value])=>'<div class="stat"><span>'+label+'</span><strong>'+value+'</strong></div>').join('')+'</div><p class="caption">Win rate = wins / all completed games, including draws. Average game time uses completed matches. Total hours also includes unfinished sessions. Menus, background time, Pass & Play and tutorial practice are excluded.</p>'+
 (data.legacy?'<div class="note">Your V3.1 summary is preserved: '+(data.legacy.g||0)+' games, '+(data.legacy.w||0)+' bot wins. It is not merged into the new averages because old records did not store mode-specific timing.</div>':'')+
 '<div class="section-heading"><h3>Recent games</h3></div>'+data.records.filter(r=>r.mode===statsMode).slice(-6).reverse().map(r=>'<div class="ledger"><span>'+escape(r.difficulty||r.mode)+'<small>'+new Date(r.at).toLocaleDateString()+' &middot; '+seconds(r.activeSeconds)+'</small></span><b>'+r.result+'</b></div>').join('')+(a.games?'':empty('chart','Your first game goes here','Finish a match to start your record. No sample wins or invented playtime.'));}
function rankDescription(t){return t.cap?'Up to '+t.cap.toLocaleString()+' exclusive worldwide seats &middot; '+t.min+'+ Elo':t.name==='Emerald'?'1900+ Elo &middot; the highest open league':t.min+' &ndash; '+(D.TIERS[t.index+1].min-1)+' Elo';}
function fixtureRows(){const rows=[];D.TIERS.forEach(t=>{const n=t.id==='grandmaster'?20:25;for(let i=0;i<n;i++)rows.push({id:t.id+'-'+i,name:['Quiet Knight','Blue Orbit','Boardwalk','Corner Theory','Next Move'][i%5]+' '+String(i+1).padStart(2,'0'),tier:t.id,rating:t.min+(t.id==='grandmaster'?340:180)-i*5,coins:4500+t.index*800-i*47,crowns:1200+t.index*120-i*11,region:i%3?'India':'Australia',wealthPublic:true});});return rows;}
function ranks(){const t=rankLeague==='all'?D.tier('grandmaster'):D.tier(rankLeague);const rows=demo?D.leaderboard(fixtureRows(),{scope:rankScope,region:data.profile.region,league:rankLeague,metric:rankMetric}):[];
 return '<h2>Find your league</h2><p class="caption">Earn your rank. Make it yours.</p><div class="tabs">'+[['rating','Skill'],['coins','Coin vault'],['crowns','Crown vault']].map(([id,label])=>'<button class="tab '+(id===rankMetric?'active':'')+'" data-action="metric" data-value="'+id+'">'+label+'</button>').join('')+'</div>'+
 '<div class="two-fields">'+field('Leaderboard','rankScope',opts([['global','Global'],['local',data.profile.region+' (country)']],rankScope))+field('League','rankLeague',opts([['all','All leagues'],...D.TIERS.map(t=>[t.id,t.name])],rankLeague))+'</div>'+
 '<div class="league-strip" aria-label="Browse leagues">'+D.TIERS.map(x=>'<button class="league '+(x.id===rankLeague?'active':'')+'" data-action="league" data-value="'+x.id+'">'+badge(x)+'<b>'+x.name+'</b></button>').join('')+'</div>'+
 '<div class="league-hero">'+badge(t,true)+'<h3>'+t.name+'</h3><p>'+rankDescription(t)+'</p><div class="league-meta"><span class="pill">'+t.motto+'</span><span class="pill">'+t.multiplier.toFixed(2)+'&times; win bonus</span><span class="pill">'+t.fee+' coin ticket*</span></div></div>'+
 '<p class="caption">*Proposed earned-coin ticket. Stake features are off. Skill rank cannot be bought.</p>'+
 '<div class="section-heading"><h3>Top 20 &middot; '+(rankMetric==='rating'?'Skill':rankMetric==='coins'?'Earned coins':'Purchased cosmetic crowns')+'</h3></div>'+
 (rankMetric!=='rating'?'<div class="note">This is a separate, opt-in vault leaderboard. It does not affect Elo or matchmaking. Only verified server balances will appear; local preview coins are excluded.</div>':'')+
 (demo?'<div class="note notice"><b>Fictional preview data.</b> These are not real players, balances, titles or challenge recipients.</div>':'')+
 (rows.length?rows.map((p,i)=>'<div class="standing"><span class="position">'+(i+1)+'</span>'+badge(D.tier(p.tier))+'<div><b>'+p.name+'</b><small>'+p[rankMetric].toLocaleString()+' '+(rankMetric==='rating'?'Elo':rankMetric)+' &middot; '+p.region+'</small></div><button data-action="challenge" data-value="'+p.tier+'" aria-label="Preview challenge against '+p.name+'">'+icon('arrow')+'</button></div>').join(''):empty('trophy','The ladder is not live yet','Browse every league above. Live positions, your percentile and the top 20 will appear after multiplayer is connected.'))+
 fullButton(demo?'Hide fictional preview':'Preview leaderboard layout','demo','',true)+fullButton('How ranks work','rankhelp','',true)+'<p class="caption">Your league: Unranked. Complete 10 verified ranked placements. Local means your selected country, not GPS location.</p>';
}
function quests(){const d=D.getDaily(data);const remaining=Math.max(0,100-d.botPaid);return '<h2>A reason for one more</h2><p class="caption">Small goals. Coins for playing, not paying.</p><div class="status-line">'+icon('clock')+'Resets at 00:00 UTC &middot; '+D.day()+'</div><div class="note">On-device preview rewards only. Online verification will be required before coins can enter any live economy.</div>'+D.QUESTS.map(q=>{const count=Math.min(q.target,d[q.metric]||0),done=d.claimed.includes(q.id),ready=count>=q.target&&!q.online;return '<div class="quest"><div><strong>'+q.title+'</strong><p>'+q.desc+'</p><div class="progress" aria-label="'+Math.round(count/q.target*100)+' percent"><span style="width:'+Math.min(100,count/q.target*100)+'%"></span></div><p>'+ (q.metric==='seconds'?seconds(count)+' / 10:00':count+' / '+q.target)+(q.online?' &middot; needs online play':'')+'</p></div><div class="quest-side"><span class="reward">'+icon('coin')+' '+q.reward+'</span><button class="button quiet" data-action="claim" data-value="'+q.id+'" '+(!ready||done?'disabled':'')+'>'+(done?'Claimed':'Claim')+'</button></div></div>';}).join('')+'<div class="section-heading"><h3>Bot rewards</h3><span class="pill">'+remaining+' / 100 left today</span></div>'+G.LEVELS.map(l=>'<div class="split"><span>'+l+'</span><span class="amount">'+D.BOT_PAY[l]+' coins / win</span></div>').join('')+'<p class="caption">Maximum 5 rewarded wins per difficulty and 100 bot coins per UTC day. Full games only: at least 12 moves and 30 active seconds. No rewards for restarts, resignations, local two-player or tutorial practice.</p>'+fullButton('Open wallet','wallet','',true);}
function sheetOpen(){return !$('#sheet').hidden;}
function open(title,html,kind='info'){
 clearTimeout(botTimer);botTimer=null;sheetKind=kind;$('#sheetTitle').textContent=title;$('#sheetBody').innerHTML=html;$('#sheet').dataset.kind=kind;$('#sheetBackdrop').hidden=false;$('#sheet').hidden=false;$('#sheet').scrollTop=0;lastTick=performance.now();refreshIcons();
}
function close(){if($('#sheet').hidden)return;$('#sheet').hidden=true;$('#sheetBackdrop').hidden=true;sheetKind='';lastTick=performance.now();lastInput=lastTick;scheduleBot();}
function settings(){const s=data.settings;
 const toggle=(key,label,desc)=>'<div class="setting-row"><label for="setting-'+key+'">'+label+'<small>'+desc+'</small></label><input class="switch" id="setting-'+key+'" data-setting="'+key+'" type="checkbox" '+(s[key]?'checked':'')+'></div>';
 const themes='<div class="theme-grid">'+Object.entries(themeNames).map(([id,name])=>'<button class="theme-card '+(s.theme===id?'active':'')+'" data-action="theme" data-value="'+id+'" aria-pressed="'+(s.theme===id)+'"><span class="theme-preview '+id+'"><span class="sample-x">X</span><span class="sample-o">O</span></span><b>'+name+'</b><small>'+({vector:'Clear, bright and familiar.',dark:'Slate, soft light, lime accents.',paper:'Printed paper and warm ink.',neon:'Arcade glow. No strobe effects.'}[id])+'</small></button>').join('')+'</div>';
 open('Settings','<div class="setting-group"><h4>GAMEPLAY</h4>'+toggle('legal','Legal board highlight','Shows the board you can play in')+toggle('preview','Destination preview','Shows where a move sends the next player')+'<div class="setting-row"><label for="setting-timer">Move timer<small>Applies to the next match</small></label><select id="setting-timer" data-setting="timer">'+opts([['0','Off'],['30','30 seconds'],['60','60 seconds']],String(s.timer))+'</select></div>'+toggle('confirm','Confirm each move','Tap a cell twice before placing')+'</div><div class="setting-group"><h4>FEEDBACK</h4>'+toggle('sound','Sound effects','Move and win cues')+toggle('music','Ambient sound','Soft background tone')+toggle('haptics','Haptics','On supported devices')+'</div><div class="setting-group"><h4>APPEARANCE</h4>'+themes+'<p class="caption theme-caption">Themes change the whole interface while keeping board geometry identical.</p>'+toggle('motion','Reduce motion','Keeps gameplay readable with fewer effects')+'</div><div class="setting-group"><h4>LEARN</h4><div class="setting-row"><label>How to play<small>Replay the simple four-step tutorial</small></label>'+button('Open tutorial','tutorial','',true)+'</div></div><div class="setting-group"><h4>PROFILE</h4><div class="setting-row"><label for="profileRegion">Local leaderboard country<small>Chosen by you, never inferred from GPS</small></label><select id="profileRegion">'+opts(['India','Australia','United States','United Kingdom'].map(x=>[x,x]),data.profile.region)+'</select></div><div class="setting-row"><label for="wealthPublic">Public vault<small>Opt-in only; no real-money amount is displayed</small></label><input class="switch" type="checkbox" id="wealthPublic" '+(data.profile.wealthPublic?'checked':'')+'></div></div><div class="setting-group"><h4>PURCHASES</h4><div class="setting-row"><label>Remove Ads<small>One-time purchase &middot; store integration pending</small></label>'+button('View','billing','',true)+'</div></div><p class="caption settings-version">V3.2 &middot; Offline preview. No ads, payments or real stakes are enabled.</p>','settings');}
function wallet(){open('Your wallet','<div class="balance-grid"><div class="balance">'+icon('coin')+'<strong>'+data.wallet.coins+'</strong><span>Coins &middot; earned through play</span></div><div class="balance">'+icon('crown')+'<strong>'+data.wallet.crowns+'</strong><span>Crowns &middot; paid cosmetics</span></div></div><div class="note">Local preview balance. Coins are not cash, cannot be bought, cashed out, gifted or converted to Crowns. Crowns cannot enter a match pot.</div><h3>Something to make yours</h3>'+[['Copper edge',30],['Orbit frame',60],['Crown frame',120]].map(([name,cost])=>'<div class="ledger"><span>'+name+'<small>Profile cosmetic &middot; preview ownership</small></span>'+button(data.wallet.owned.includes(name)?'Owned':cost+' coins','cosmetic',name,true)+'</div>').join('')+'<div class="section-heading"><h3>Crown packs</h3><span class="pill">Not on sale</span></div><p class="caption">The proposed paid currency is for cosmetics and an optional Crown vault ranking. Prices must come from the platform store, not a hard-coded currency conversion.</p>'+fullButton('Purchase availability','billing','',true)+'<div class="section-heading"><h3>Activity</h3></div>'+data.wallet.ledger.slice(-15).reverse().map(e=>'<div class="ledger"><span>'+escape(e.reason)+'<small>'+new Date(e.at).toLocaleDateString()+'</small></span><b class="'+(e.amount>=0?'gain':'loss')+'">'+(e.amount>=0?'+':'')+e.amount+'</b></div>').join(''),'wallet');}
function rankHelp(){open('Skill first. Always.','<p class="caption">Use Elo for matchmaking and the open leagues. Percentile is useful context, not the thing that sets your rank. Ten placement games come first. A new player is never shown a made-up Gold badge.</p><div class="note">Elo changes only after verified ranked games. Coins, purchases, quests, bot games and friend challenges do not change it.</div>'+D.TIERS.map(t=>'<div class="ledger"><span>'+t.name+'<small>'+rankDescription(t)+'</small></span>'+badge(t)+'</div>').join('')+'<div class="note">Elite titles activate after 5,000 verified placed players. To qualify: 50 ranked games, 10 unique opponents, a 14-day-old account and 5 ranked games in the last 7 days. Grandmaster gets up to 20 eligible seats, Master the next 200, Champion the next 1,000. These are exclusive caps, not inclusive top-N bands. Rating floors still apply; seats can stay empty.</div><p class="caption">Tie-breaks: rating, when that rating was reached, then stable account ID. Recompute from a server snapshot; show season peak separately. A regional leaderboard never grants a global elite title.</p>');}
function challenge(target='friend'){
 const isFriend=target==='friend';open(isFriend?'Challenge a friend':'Leaderboard challenge','<div class="note notice">'+(isFriend?'Free friend play is the default.':'Preview only. This is not an invitation to a real player.')+'</div>'+field('Match format','challengeKind',opts(isFriend?[['friend-free','Free game'],['friend-stake','Earned-coin stake (disabled)']]:[['challenge','Earned-coin challenge (disabled)']],'friend-free'))+'<div class="two-fields">'+field('Your league (preview)','challengeFrom',opts(D.TIERS.map(t=>[t.id,t.name]),'wood'))+field(isFriend?'Opponent league':'Target league','challengeTo',opts(D.TIERS.map(t=>[t.id,t.name]),isFriend?'wood':target))+'</div>'+ (isFriend?'<label class="field">Stake per player (2-200, even coins)<input id="challengeStake" type="number" min="2" max="200" step="2" value="10"></label>':'')+'<div id="challengeQuote"></div><div class="note">No charge for an invitation, refusal or expiry. Both players must accept identical terms. Draws and server-voided games refund both sides. Direct challenges are unrated. Three paid proposals per pair/day maximum in the reference authority.</div>'+fullButton('Online service not connected','onlineinfo','',true),'challenge');updateQuote();
}
function updateQuote(){if(!$('#challengeQuote'))return;try{const q=D.quote({mode:$('#challengeKind').value,from:$('#challengeFrom').value,to:$('#challengeTo').value,stake:Number($('#challengeStake')?.value||0)});$('#challengeQuote').innerHTML='<div class="card" style="margin-top:14px"><h3>Before either player accepts</h3>'+[['Each player reserves',q.fee],['Combined pot',q.pool],['Burned (50%)',q.burn],['Winner receives (50%)',q.payout],['Winner net, before bonuses',q.payout-q.fee]].map(([name,n])=>'<div class="split"><span>'+name+'</span><b>'+n+' coins</b></div>').join('')+'</div><p class="caption">Higher-league challenges cost more, capped at 200 per player. This quote does not reserve or transfer any coins.</p>';}catch(e){$('#challengeQuote').innerHTML='<p class="caption">'+escape(e.message)+'</p>';}}
function onlineInfo(){
 const privateMode=mode==='private';
 const title=privateMode?'Private Match':onlineType==='ranked'?'Ranked matchmaking':'Casual matchmaking';
 const copy=privateMode?'<p>Create or join a private lobby with a friend. The lobby UI is ready, but real invitations and realtime rooms still need the multiplayer service.</p>':onlineType==='ranked'?'<p>Ranked uses verified accounts and Elo. The client flow is ready; matchmaking, authoritative moves and rating settlement are not connected yet.</p>':'<p>Casual online is free, does not change Elo and will use the same realtime game service once connected.</p>';
 open(title,copy+'<div class="note">No fake opponent is substituted. Online play stays unavailable until the server-authoritative service is connected.</div>'+(onlineType==='ranked'&&!privateMode?fullButton('See ranked entry proposal','feehelp','',true):'')+fullButton('Back','close','',true));
}
function feeHelp(){open('Ranked entry proposal','<p class="caption">Both players pay the same ticket, based on the lower league in a ranked pairing. Casual online is free. No wallet deductions happen while searching.</p>'+D.TIERS.map(t=>'<div class="split"><span>'+t.name+'</span><b>'+t.fee+' coins &middot; '+t.multiplier.toFixed(2)+'&times;</b></div>').join('')+'<div class="note">Two 20-coin entries make a 40-coin pot. Burn 20; the winner receives 20. That is break-even for the winner, not a 20-coin profit. The separate ranked win bonus is floor(12 &times; your multiplier), capped at 120/day. Multipliers do not touch Elo, the pot split or bot earnings.</div><p class="caption">Fees and reward caps are test values, not production economics. Staked matchmaking remains disabled in V3.2.</p>');}
function tutorial(){
 const grid=(hot=[],marks={})=>'<div class="tutorial-map old-map">'+Array.from({length:9},(_,i)=>'<span class="'+(hot.includes(i)?'hot':'')+'">'+(marks[i]||'')+'</span>').join('')+'</div>';
 open('How to play','<div class="tutorial-cards"><div class="tutorial-card"><span class="step-number">01</span><div><b>Win a Mini Board</b><p>Inside any Mini Board, X and O play normal tic-tac-toe. Make 3 in a row to claim that whole board.</p>'+grid([2],{0:'X',1:'X',2:'X',3:'O',5:'O'})+'</div></div><div class="tutorial-card"><span class="step-number">02</span><div><b>Your cell sends the opponent</b><p>The cell position you choose becomes the opponent\'s next Mini Board. Play top-right and they must play in the top-right board.</p><div class="tutorial-flow">'+grid([2],{2:'X'})+icon('arrow')+grid([2],{2:'GO'})+'</div></div></div><div class="tutorial-card"><span class="step-number">03</span><div><b>Closed board? Free Move.</b><p>If your move points to a Mini Board that is already won or drawn, the next player can choose any open Mini Board.</p></div></div><div class="tutorial-card"><span class="step-number">04</span><div><b>Win the Mega Board</b><p>Claim 3 Mini Boards in a row, column or diagonal to win the match.</p>'+grid([0,1,2],{0:'X',1:'X',2:'X',4:'O',6:'O'})+'</div></div></div>'+fullButton(match&&!match.state.winner?'Back to your match':'Practice vs Beginner Bot',match&&!match.state.winner?'close':'practice')+'<p class="caption">Practice has no coins or personal stats.</p>','tutorial');try{localStorage.setItem('mega_v32_tutorial_seen','1');}catch{}}
// Build the fixed board once. Theme changes and marks never replace its grid containers.
const miniNodes=[],cellNodes=[];
function buildBoard(){for(let b=0;b<9;b++){const el=document.createElement('div');el.className='mini';el.dataset.board=b;const cells=[];for(let c=0;c<9;c++){const cell=document.createElement('button');cell.type='button';cell.className='cell';cell.dataset.b=b;cell.dataset.c=c;cell.addEventListener('click',()=>humanMove(b,c));cell.addEventListener('pointerenter',()=>preview(b,c));cell.addEventListener('pointerleave',clearPreview);el.append(cell);cells.push(cell);}const claim=document.createElement('div');claim.className='claim';claim.hidden=true;el.append(claim);$('#board').append(el);miniNodes.push({el,claim});cellNodes.push(cells);}}
function mark(p){return '<span class="mark-layer '+p.toLowerCase()+'"><svg viewBox="0 0 40 40" stroke="currentColor" aria-hidden="true">'+(p==='X'?'<path d="M10 10 30 30M30 10 10 30"/>':'<circle cx="20" cy="20" r="11"/>')+'</svg></span>';}
function startGame(practice=false,rematch=false){
 clearTimeout(botTimer);botTimer=null;const starter=rematch&&match?(match.first==='X'?'O':'X'):practice?'X':first;
 match={id:globalThis.crypto?.randomUUID?.()||String(Date.now())+Math.random(),state:G.create(starter),mode:practice?'bot':mode,difficulty:practice?'Beginner':difficulty,first:starter,practice,active:0,turnRemaining:Number(data.settings.timer)||0,turnLimit:Number(data.settings.timer)||0,last:null,recorded:false,pending:null};
 $('#gameScreen').hidden=false;$('#matchMode').textContent=practice?'Tutorial practice':match.mode==='local'?'Pass & Play':'Vs Bot';$('#matchLevel').textContent=match.mode==='local'?'Two players, one device':match.difficulty+' difficulty';$('#playerXName').textContent=match.mode==='local'?'Player X':'You';$('#playerOName').textContent=match.mode==='local'?'Player O':'Bot';
 lastTick=lastInput=performance.now();paint();syncAudio();scheduleBot();
}
function paint(){if(!match)return;const s=match.state,canHuman=!s.winner&&(match.mode==='local'||s.turn==='X');const choices=new Set(G.legal(s).map(m=>m.b*9+m.c));
 for(let b=0;b<9;b++){const {el,claim}=miniNodes[b],allowed=!s.mini[b]&&!s.winner&&(s.required===null||s.required===b);
  el.className='mini'+(allowed&&data.settings.legal?(s.required===null?' available':' active'):'')+(!allowed&&!s.mini[b]?' inactive':'')+(s.line?.includes(b)?' win':'');
  el.setAttribute('aria-label',G.NAMES[b]+' Mini Board'+(s.mini[b]?', '+(s.mini[b]==='DRAW'?'drawn':'won by '+s.mini[b]):allowed?', playable':''));
  for(let c=0;c<9;c++){const n=cellNodes[b][c],v=s.board[b][c];if(n.dataset.mark!==(v||'')){n.innerHTML=v?mark(v):'';n.dataset.mark=v||'';}n.disabled=!canHuman||!choices.has(b*9+c);n.classList.toggle('last',!!match.last&&match.last.b===b&&match.last.c===c);n.setAttribute('aria-label',G.NAMES[b]+' board, '+G.NAMES[c]+' cell, '+(v||'empty'));}
  claim.hidden=!s.mini[b];if(s.mini[b]&&claim.dataset.owner!==s.mini[b]){claim.className='claim '+s.mini[b].toLowerCase();claim.innerHTML=s.mini[b]==='DRAW'?'<span>DRAW</span>':mark(s.mini[b]);claim.dataset.owner=s.mini[b];}
 }
 $('#miniX').textContent=s.mini.filter(x=>x==='X').length;$('#miniO').textContent=s.mini.filter(x=>x==='O').length;$('#playerX').classList.toggle('active',!s.winner&&s.turn==='X');$('#playerO').classList.toggle('active',!s.winner&&s.turn==='O');
 const who=match.mode==='local'?(s.turn==='X'?'PLAYER X':'PLAYER O'):(s.turn==='X'?'YOUR TURN':'BOT TURN');
 $('#turnText').textContent=s.winner?(s.winner==='DRAW'?'MATCH DRAWN':s.winner+' WINS'):s.required===null?'FREE ROUTE':who+' · '+G.NAMES[s.required].toUpperCase();
 $('#destinationText').textContent=s.winner?'Review the board or start a rematch.':s.required===null?'CHOOSE ANY OPEN MINI BOARD':'PLAY ONLY IN THIS MINI BOARD';
 $('#clock').textContent=match.turnLimit?Math.ceil(match.turnRemaining)+'s':'∞';$('#clock').classList.toggle('urgent',match.turnLimit>0&&match.turnRemaining<=5);
}
function clearPreview(){
 miniNodes.forEach(x=>x.el.classList.remove('preview'));
 cellNodes.flat().forEach(n=>n.classList.remove('cell-hover','hover-x','hover-o'));
 if(match)$('#previewText').textContent=match.pending?'Tap the same cell again to confirm.':"Your cell determines the opponent's next board.";
}
function preview(b,c){
 if(!match||cellNodes[b][c].disabled)return;
 clearPreview();
 const cell=cellNodes[b][c];
 cell.classList.add('cell-hover',match.state.turn==='X'?'hover-x':'hover-o');
 if(!data.settings.preview)return;
 if(match.state.mini[c])$('#previewText').textContent='This gives your opponent free choice of any open board.';
 else{miniNodes[c].el.classList.add('preview');$('#previewText').textContent='This sends your opponent to the '+G.NAMES[c].toLowerCase()+' board.';}
}
function animateRoute(b,c,next){
 const routeOverlay=$('#routeOverlay');routeOverlay.innerHTML="";if(next===null)return;
 requestAnimationFrame(()=>{
   const wrap=$('#boardWrap').getBoundingClientRect(),cell=cellNodes[b]?.[c],target=miniNodes[next]?.el;
   if(!cell||!target)return;const a=cell.getBoundingClientRect(),t=target.getBoundingClientRect();
   const x1=a.left+a.width/2-wrap.left,y1=a.top+a.height/2-wrap.top,x2=t.left+t.width/2-wrap.left,y2=t.top+t.height/2-wrap.top;
   routeOverlay.setAttribute("viewBox","0 0 "+wrap.width+" "+wrap.height);
   routeOverlay.innerHTML='<line x1="'+x1+'" y1="'+y1+'" x2="'+x2+'" y2="'+y2+'"/><circle cx="'+x2+'" cy="'+y2+'" r="5"/>';
   target.classList.add('route-target');
   setTimeout(()=>{routeOverlay.innerHTML="";target.classList.remove('route-target');},700);
 });
}
function humanMove(b,c){if(!match||match.state.winner||sheetOpen()||(match.mode==='bot'&&match.state.turn==='O'))return;lastInput=performance.now();if(data.settings.confirm&&(!match.pending||match.pending.b!==b||match.pending.c!==c)){match.pending={b,c};preview(b,c);$('#previewText').textContent='Tap the same cell again to confirm.';return;}move({b,c},'human');}
function move(m,source){if(!match||match.state.winner)return;if(match.mode==='bot'&&((match.state.turn==='O')!==(source==='bot')))return;
 try{match.state=G.apply(match.state,m);}catch{notify('Choose an empty cell in the highlighted board.');return;}
 match.last=m;match.pending=null;match.turnRemaining=match.turnLimit;tone(source==='bot'?370:540);haptic();paint();clearPreview();animateRoute(m.b,m.c,match.state.required);if(match.state.winner)finish(match.state.winner==='DRAW'?'draw':'line');else scheduleBot();
}
function scheduleBot(){clearTimeout(botTimer);botTimer=null;if(!match||match.state.winner||match.mode!=='bot'||match.state.turn!=='O'||sheetOpen()||document.hidden)return;const current=match,revision=match.state.moves.length;
 botTimer=setTimeout(()=>{botTimer=null;if(match!==current||match.state.moves.length!==revision||sheetOpen()||document.hidden)return;const m=G.choose(match.state,match.difficulty);if(m)move(m,'bot');},850+Math.random()*220);
}
function finish(reason){if(!match||match.recorded)return;clearTimeout(botTimer);botTimer=null;match.recorded=true;
 const s=match.state,result=s.winner==='DRAW'?'draw':s.winner==='X'?'win':'loss';const record={id:match.id,at:Date.now(),mode:match.mode,difficulty:match.difficulty,practice:match.practice,result,reason,moves:s.moves.length,activeSeconds:Math.round(match.active),claimed:s.mini.filter(x=>x==='X').length};
 const award=D.complete(data,record);save();render();paint();open(result==='draw'?'A well-fought draw':match.mode==='local'?'Player '+s.winner+' wins':result==='win'?'Nicely played.':'One more try?',
 '<p class="caption">'+(reason==='line'?'Three Mini Boards in a row.':reason==='draw'?'All Mini Boards resolved without a big winning line.':reason==='timeout'?'The turn timer ran out.':'The match ended by resignation.')+'</p><div class="stats-grid"><div class="stat"><span>Moves</span><strong>'+s.moves.length+'</strong></div><div class="stat"><span>Active time</span><strong>'+seconds(match.active)+'</strong></div></div><div class="note">'+(match.practice?'Tutorial practice is not counted in your personal stats.':match.mode==='local'?'Pass & Play does not affect personal stats or rewards.':award?'You earned '+award+' on-device preview coins.':'No coin reward for this result. Quests count qualifying full games; bot rewards require a win and daily eligibility.')+'</div>'+fullButton('Rematch','rematch')+fullButton('Back to home','home','',true),'result');
}
setInterval(()=>{const now=performance.now(),delta=Math.min(1,Math.max(0,(now-lastTick)/1000));lastTick=now;if(!match||match.state.winner||$('#gameScreen').hidden||sheetOpen()||document.hidden)return;if(now-lastInput<60000){match.active+=delta;if(match.mode!=='local'&&!match.practice){const k=match.mode+':all',d=match.mode+':'+match.difficulty;data.playSeconds[k]=(data.playSeconds[k]||0)+delta;data.playSeconds[d]=(data.playSeconds[d]||0)+delta;if(now-lastSave>5000){save();lastSave=now;}}}if(match.turnLimit){match.turnRemaining=Math.max(0,match.turnRemaining-delta);$('#clock').textContent=Math.ceil(match.turnRemaining)+'s';$('#clock').classList.toggle('urgent',match.turnRemaining<=5);if(match.turnRemaining===0){match.state={...match.state,winner:match.state.turn==='X'?'O':'X'};finish('timeout');}}},100);
document.addEventListener('visibilitychange',()=>{lastTick=performance.now();if(document.hidden){clearTimeout(botTimer);botTimer=null;}else{lastInput=lastTick;scheduleBot();}syncAudio();});
document.addEventListener('pointerdown',()=>{lastInput=performance.now();},true);
function currentMatchStats(){if(!match)return;const s=match.state;open('Current match','<div class="stats-grid"><div class="stat"><span>Moves</span><strong>'+s.moves.length+'</strong></div><div class="stat"><span>Active time</span><strong>'+seconds(match.active)+'</strong></div><div class="stat"><span>X Mini Boards</span><strong>'+s.mini.filter(x=>x==='X').length+'</strong></div><div class="stat"><span>O Mini Boards</span><strong>'+s.mini.filter(x=>x==='O').length+'</strong></div></div>'+fullButton('Resign match','resign','',true),'matchstats');}
function leave(){save();clearTimeout(botTimer);botTimer=null;match=null;$('#gameScreen').hidden=true;close();page='play';render();}
const actions={
 nav:v=>{page=v;render();$('#page').scrollTop=0;},mode:v=>{mode=v;render();},difficulty:v=>{difficulty=v;render();},first:v=>{first=v;render();},settimer:v=>{data.settings.timer=Number(v);save();render();},onlinetype:v=>{onlineType=v;render();},start:()=>['bot','local'].includes(mode)?startGame():onlineInfo(),settings,wallet,tutorial,matchstats:currentMatchStats,rankhelp:rankHelp,feehelp:feeHelp,onlineinfo:onlineInfo,
 close,theme:v=>{if(!themeNames[v])return;data.settings.theme=v;applyTheme();save();const top=$('#sheet').scrollTop;settings();$('#sheet').scrollTop=top;render();paint();},
 statmode:v=>{statsMode=v;statsDifficulty='all';render();},metric:v=>{rankMetric=v;render();},league:v=>{rankLeague=v;render();},demo:()=>{demo=!demo;render();},challenge,
 claim:v=>{const n=D.claim(data,v);save();render();notify(n?'Claimed '+n+' coins.':'Quest is not ready.');},cosmetic:v=>{const cost={'Copper edge':30,'Orbit frame':60,'Crown frame':120}[v];try{const ok=D.spend(data,v,cost);save();render();wallet();notify(ok?'Cosmetic added to your local collection.':'Already owned.');}catch(e){notify(e.message==='INSUFFICIENT_COINS'?'Earn a few more coins first.':e.message);}},
 billing:()=>open('Purchases are not connected','<p>Crown packs and Remove Ads need the native store and server receipt verification. There is no payment or purchase confirmation in this preview.</p><div class="note">Paid Crowns buy cosmetics only. They cannot be converted into earned coins, staked, gifted or cashed out. An optional Crown vault compares verified in-game balances, never skill.</div>'+fullButton('Back to wallet','wallet','',true)),
 findfriend:()=>{const name=$('#friendName').value.trim();if(!name)return notify('Enter a username first.');onlineInfo();},
 copyfriend:()=>{const code=data.profile.friendCode;if(navigator.clipboard?.writeText)navigator.clipboard.writeText(code).then(()=>notify('Friend code copied.')).catch(()=>notify(code));else notify(code);},
 practice:()=>{close();mode='bot';difficulty='Beginner';startGame(true);},
 leave:()=>{if(!match||match.state.winner)return leave();open('Leave this game?','<p>Your current offline match will be discarded. No coins or completed-game stats are awarded.</p>'+fullButton('Leave game','home')+fullButton('Keep playing','close','',true));},
 home:leave,restart:()=>open('Start a new game?','<p>This discards the current match, without rewards.</p>'+fullButton('Start again','restartyes')+fullButton('Keep playing','close','',true)),restartyes:()=>{close();startGame();},
 rematch:()=>{close();startGame(match?.practice||false,true);},resign:()=>{if(!match||match.state.winner)return;open('Resign?','<p>A bot game resignation counts as a loss, but gives no coins.</p>'+fullButton('Resign match','resignyes')+fullButton('Keep playing','close','',true));},
 resignyes:()=>{close();match.state={...match.state,winner:match.mode==='bot'?'O':match.state.turn==='X'?'O':'X'};finish('resign');}
};
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const fn=actions[el.dataset.action];if(fn)fn(el.dataset.value||'');});
document.addEventListener('change',e=>{
 const el=e.target;if(el.dataset.setting){const key=el.dataset.setting;data.settings[key]=el.type==='checkbox'?el.checked:Number(el.value);save();if(key==='music')syncAudio();applyTheme();if(key==='preview')clearPreview();paint();return;}
 if(el.id==='difficulty')difficulty=el.value;else if(el.id==='first')first=el.value;else if(el.id==='setupTimer'){data.settings.timer=Number(el.value);save();}
 else if(el.id==='statsDifficulty'){statsDifficulty=el.value;render();}else if(el.id==='rankScope'){rankScope=el.value;render();}else if(el.id==='rankLeague'){rankLeague=el.value;render();}
 else if(el.id==='profileRegion'){data.profile.region=el.value;save();render();}else if(el.id==='wealthPublic'){data.profile.wealthPublic=el.checked;save();}else if(el.id.startsWith('challenge'))updateQuote();
});
for(const [id,name] of [['brandIcon','board'],['coinIcon','coin'],['settingsButton','settings'],['sheetClose','close'],['backIcon','back'],['matchSettings','sliders'],['routeIcon','route'],['rulesIcon','help'],['restartIcon','refresh'],['statsIcon','chart']])$('#'+id).innerHTML=icon(name);
refreshIcons();applyTheme();buildBoard();render();save();
// Read-only diagnostics: no method can credit money, set rank or submit a server result.
window.MegaXO=Object.freeze({version:'3.2.4',getState:()=>match?structuredClone(match.state):null,getSettings:()=>({...data.settings})});
try{if(!localStorage.getItem('mega_v32_tutorial_seen'))tutorial();}catch{}
})();
