/* V3.3.3 account and social UI. Existing game rendering is used via MegaApp;
 * the module never writes authoritative currency, Elo or game results. */
(()=>{
'use strict';
const API=window.MegaAccount,APP=window.MegaApp,NET=window.MegaNetwork,D=window.MegaDomain,I=window.MegaIcons;
if(!API||!APP)return;
const $=(s,root=document)=>root.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='mega_v32_state',OWNER='mega_v333_owner',META='mega_v333_sync';
const get=k=>{try{return JSON.parse(localStorage.getItem(k)||'null');}catch{return null;}},put=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}};
const icon=n=>I?.icon(n)||'',btn=(text,action,id='',quiet=false)=>'<button type="button" class="button full '+(quiet?'quiet':'')+'" data-c="'+action+'" data-id="'+esc(id)+'">'+text+'</button>';
const label={online:'Online',away:'Away',offline:'Offline',hidden:'Status hidden','in-match':'In a match','in-lobby':'In a lobby',queued:'Finding a match'};
let session=null,social={friends:[],incoming:[],outgoing:[],blocked:[]},invites=[],panel=null,profile=null,previousFocus=null,profileMode='ranked',selectedAvatar='board',syncRevision=0,syncState='device',dirty=false,saving=false,suppressSave=false,syncTimer=null,lastPresence=0,queuedAt=0,bootVersion=0,conflict=null,refreshing=false,lastError='',friendsQuery='',searchRows=[],reconnecting=false;
function error(e){return ({SERVICE_UNAVAILABLE:'You are offline, or the service is unavailable. You can still play on this device.',ONLINE_UNAVAILABLE:'The online service is unavailable.',PROVIDER_NOT_CONFIGURED:'This sign-in method is not available yet.',AUTH_REQUIRED:'Sign in again to continue.',LINK_ACCOUNT_REQUIRED:'Create or link a profile first.',INVALID_USERNAME:'Use 3-20 letters, numbers or underscores. Start with a letter.',USERNAME_TAKEN:'That username is already taken.',USERNAME_COOLDOWN:'You can change your username again after seven days.',INVALID_DISPLAY_NAME:'Use a display name of up to 28 characters.',ACCOUNT_LINKED_ELSEWHERE:'That login belongs to another profile. Sign out and restore that profile instead; nothing has been merged.',PROVIDER_ALREADY_LINKED:'This profile already has a different login from that provider.',LAST_LOGIN_METHOD:'Link another sign-in method before removing this one.',REAUTH_REQUIRED:'Verify your account again before changing linked accounts.',REAUTH_ACCOUNT_MISMATCH:'Choose a login already linked to this profile. Nothing has been changed.',SAVE_CONFLICT:'A newer cloud save exists. Choose which practice save to keep.',PROFILE_NOT_FOUND:'This player is unavailable.',FRIENDSHIP_REQUIRED:'Both players must accept the friend request first.',RATE_LIMITED:'Please wait a moment and try again.',MATCH_ACTIVE:'Finish or leave your current match first.',CSRF_FAILED:'Your session changed. Sign in again to continue.',SIGNIN_CANCELLED:'Sign-in was cancelled. Your device progress is unchanged.'})[e?.message]||'Could not complete that action. Please try again.';}
function announce(text,bad=false){lastError=text;const el=$('#identityStatus');if(el){el.textContent=text;el.classList.toggle('error',bad);}else APP.notify(text);}
function loader(small=false){return '<div class="theme-loader '+(small?'small':'')+'" aria-hidden="true">'+Array.from({length:9},(_,i)=>'<span style="--i:'+i+'"></span>').join('')+'</div>';}
function avatar(kind='board',small=false){const glyph={cross:'<path d="M6 6 18 18M18 6 6 18"/>',ring:'<circle cx="12" cy="12" r="7"/>',board:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M9 3v18M15 3v18M3 9h18M3 15h18"/>',rook:'<path d="M6 21h12M7 18h10L16 8h2V3h-3v3h-2V3h-2v3H9V3H6v5h2z"/>',crown:'<path d="m3 7 4 3 5-7 5 7 4-3-3 13H6z"/>',star:'<path d="m12 3 3 6 6 1-4 5 1 6-6-3-6 3 1-6-4-5 6-1z"/>'}[kind]||'';return '<span class="profile-avatar '+(small?'small':'')+'"><svg viewBox="0 0 24 24" aria-hidden="true">'+glyph+'</svg></span>';}
function state(p){const v=p.presence||{state:'offline',online:false};return '<span class="presence" data-online="'+(v.online===true)+'">'+esc(label[v.state]||'Offline')+'</span>';}
function frame(title,html,kind='profile',canClose=true){if(!panel){previousFocus=document.activeElement;panel=document.createElement('section');panel.id='identityScreen';$('#app').append(panel);}panel.className='identity-screen '+kind;panel.dataset.kind=kind;panel.setAttribute('aria-label',title||'Opening Mega XO');panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.innerHTML=(title?'<div class="identity-top"><h2 tabindex="-1">'+esc(title)+'</h2>'+(canClose?'<button class="icon-button" data-c="dismiss" aria-label="Close">'+icon('close')+'</button>':'')+'</div>':'')+html+'<span id="identityStatus" class="identity-status" role="status" aria-live="polite"></span>';I?.refresh?.();}
function dismiss(){panel?.remove();panel=null;profile=null;lastError='';if(previousFocus?.isConnected)previousFocus.focus?.();}
function loading(text,allowGuest=false){frame('',loader()+'<h1>MEGA XO</h1><div class="loading-track" aria-hidden="true"></div><p role="status">'+esc(text)+'</p>'+(allowGuest?btn('Play on this device','guest','',true):''),'startup',false);}
function providerButtons(intent='login'){const caps=session?.providers||{};return '<div class="signin-options">'+[['google','Continue with Google'],['apple','Sign in with Apple']].map(([provider,text])=>'<button class="provider-button" data-c="signin" data-id="'+provider+'" data-intent="'+intent+'" '+(caps[provider]?.web||window.MegaNativeIdentity&&caps[provider]?.native?'':'disabled')+'>'+esc(text)+'</button>').join('')+'</div>';}
function landing(link=false){frame(link?'Save your progress':'Welcome to Mega XO','<div class="signin-art">'+loader()+'</div><span class="identity-eyebrow">YOUR GAME. YOUR PROFILE.</span><h1>Play now.<br>Keep it with you.</h1><p>Create a profile with Google or Apple to restore your progress on another device. Your player tag stays the same.</p>'+providerButtons(link?'link':'login')+btn('Continue as guest','guest','',true)+'<div class="signin-foot"><p>Guest progress stays on this device. Uninstalling the app or clearing its storage can erase it. Sign-in is optional for offline play.</p></div>','signin',true);if(!session){announce('Checking sign-in availability...');API.session(true).then(s=>{session=s;if(panel?.dataset.kind==='signin'){const el=$('.signin-options',panel);if(el)el.outerHTML=providerButtons(link?'link':'login');announce('');}}).catch(()=>announce('Sign-in needs a connection. Guest play is available.'));}}
function archiveCurrent(){const owner=get(OWNER)||'guest';put('mega_v333_archive:'+owner,APP.getSave());}
async function becomeGuest(){bootVersion++;if(!session)try{session=await API.session();}catch{}if(APP.getContext().playing&&get(OWNER))return announce('Finish your current match before switching profiles.',true);
 if(session?.linked){await saveNow();if(dirty||syncState==='conflict')return announce('Back up or resolve the current profile before switching to guest.',true);await API.request('/api/account/logout',{});}
 if(get(OWNER)){archiveCurrent();const previous=get('mega_v333_archive:guest')||D.fresh();previous.settings.theme=APP.getSave().settings.theme;suppressSave=true;put(OWNER,null);APP.applyPractice(previous);suppressSave=false;}
 API.reset();session=null;syncState='device';put('mega_v333_welcomed',true);dismiss();APP.refresh();APP.render();}

function hasProgress(p){return !!p?.records?.length||!!p?.offlineMatch||!!p?.wallet?.owned?.length||Object.values(p?.playSeconds||{}).some(n=>Number(n)>0)||(p?.wallet?.ledger||[]).some(e=>e.id!=='welcome');}
async function adoptCloud(remote){suppressSave=true;archiveCurrent();const p=remote.practice||D.fresh();if(!remote.practice)p.settings.theme=APP.getSave().settings.theme;APP.applyPractice(p);put(OWNER,session.profile.id);syncRevision=remote.revision||0;dirty=!remote.practice;put(META,{actor:session.profile.id,revision:syncRevision,dirty});suppressSave=false;syncState=dirty?'pending':'saved';if(dirty)await saveNow();dismiss();APP.refresh();APP.render();}
async function useDevice(){const remote=conflict?.remote||{revision:syncRevision};archiveCurrent();put(OWNER,session.profile.id);syncRevision=remote.revision;dirty=true;conflict=null;await saveNow();if(syncState==='saved'){dismiss();APP.refresh();APP.render();}}
function chooseSave(remote){conflict={remote};frame('Choose your practice save','<p>'+ (remote.practice?'This profile already has a cloud save. Choose which practice progress to use.':'This is a different profile with no cloud backup yet. Start fresh or explicitly bring this device practice across.') +' The current device copy remains archived.</p><div class="profile-card"><b>'+(remote.practice?'Cloud save':'New practice save')+'</b><p>'+Number(remote.practice?.records?.length||0)+' completed practice games</p></div><div class="profile-card"><b>This device</b><p>'+APP.getSave().records.length+' completed practice games</p></div>'+btn(remote.practice?'Restore cloud save':'Start fresh for this profile','restore-choice')+btn('Keep this device practice save','device-choice','',true)+'<p>Your server-owned Coins, Crowns, rank and online results are unchanged by either choice.</p>','conflict',false);}
async function saveNow(){if(!session?.linked||saving||suppressSave||!dirty)return;const owner=get(OWNER);if(owner!==session.profile.id)return;const snapshot=APP.getSave();saving=true;syncState='saving';
 try{const saved=await API.request('/api/account/save',{revision:syncRevision,practice:snapshot});syncRevision=saved.revision;dirty=JSON.stringify(APP.getSave())!==JSON.stringify(snapshot);put(META,{actor:owner,revision:syncRevision,dirty});put('mega_v333_archive:'+owner,snapshot);syncState=dirty?'pending':'saved';}
 catch(e){syncState=e.message==='SAVE_CONFLICT'?'conflict':'offline';if(e.message==='SAVE_CONFLICT'){conflict={remote:await API.request('/api/account/save').catch(()=>null)};if(panel?.dataset.kind==='profile')announce('A newer save is available. Resolve it before syncing.',true);}}finally{saving=false;}
}
async function syncBoot(generation){const resolved=await API.session(true);if(generation!==bootVersion)return;session=resolved;if(!session.linked)return;const remote=await API.request('/api/account/save');if(generation!==bootVersion)return;const owner=get(OWNER),meta=get(META);syncRevision=remote.revision;
 if(owner!==session.profile.id){if((remote.practice||owner)&&hasProgress(APP.getSave())){chooseSave(remote);return 'conflict';}if(remote.practice){await adoptCloud(remote);return;}archiveCurrent();put(OWNER,session.profile.id);dirty=true;await saveNow();}
 else if(meta?.revision!==undefined&&remote.revision>meta.revision){if(meta.dirty){chooseSave(remote);return 'conflict';}if(remote.practice)await adoptCloud(remote);}
 else if(meta?.dirty){dirty=true;await saveNow();}
 if(!dirty)syncState='saved';put(META,{actor:session.profile.id,revision:syncRevision,dirty});
}
async function boot(){const id=++bootVersion;loading('Opening your board',true);try{await syncBoot(id);if(id!==bootVersion)return;if(panel?.dataset.kind==='conflict')return;
  if(session?.linked){dismiss();await presence();await refreshFriends();if(session.profile.profileVersion===1)await openProfile();else if(session.profile.activeMatch&&!session.profile.activeMatch.startsWith('tournament:'))resumePrompt(session.profile.activeMatch);}
  else if(get(OWNER)){landing();announce('Sign in to reconnect your saved profile, or continue separately as a guest.');}else if(get('mega_v333_welcomed')){dismiss();if(APP.getSave().offlineMatch)frame('Continue your game?','<p>Your unfinished game is saved on this device.</p>'+btn('Resume game','resume-offline')+btn('Back to home','dismiss','',true),'resume');}else landing();
 }catch{if(id!==bootVersion)return;syncState='offline';session=null;if(get('mega_v333_welcomed'))dismiss();else landing();}
 const params=new URLSearchParams(location.search);if(params.has('authError')){APP.notify(error({message:params.get('authError')}));history.replaceState(null,'',location.pathname+location.hash);}else if(params.has('account'))history.replaceState(null,'',location.pathname+location.hash);
 if(location.hash.startsWith('#player=')){const tag=decodeURIComponent(location.hash.slice(8));if(session?.linked)openProfile(tag);else landing();}
 decorate();}
async function signIn(provider,intent){if(APP.getContext().playing)return announce('Finish your current game before switching or linking profiles.',true);archiveCurrent();announce('Opening secure sign-in...');try{
 if(window.MegaNativeIdentity&&session?.providers?.[provider]?.native){const c=await API.request('/api/account/native/challenge',{provider,intent});const credential=await window.MegaNativeIdentity.getCredential({provider,nonce:c.nonce});await API.request('/api/account/native/finish',{provider,state:c.state,idToken:credential.idToken});API.reset();await boot();}
 else {const out=await API.request('/api/account/start',{provider,intent});location.assign(out.url);}
 }catch(e){announce(error(e),true);}}
async function openProfile(id){if(!session?.linked){landing();return;}try{const p=await API.request('/api/community/profile/'+encodeURIComponent(id||session.profile.id));profile=p;profileMode='ranked';selectedAvatar=p.avatar;showProfile();}catch(e){APP.notify(error(e));}}
function fmtTime(n){if(n===null||n===undefined)return '--';const s=Math.round(n);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');}
function showProfile(){if(!profile)return;const p=profile,own=p.id===session.profile.id,stats=p.stats?.[profileMode];const statHTML=stats?'<div class="stats-grid">'+[['Games',stats.games],['Wins',stats.wins],['Win rate',stats.winRate===null?'--':(100*stats.winRate).toFixed(1)+'%'],['Average game',fmtTime(stats.averageSeconds)],['Hours played',stats.hours.toFixed(2)],['Draws',stats.draws]].map(([k,v])=>'<div class="stat"><span>'+k+'</span><strong>'+v+'</strong></div>').join(''):'<p>These stats are private. Friends can see them when the player allows it.</p>';
 let actions='';if(own)actions=btn('Edit profile','edit')+btn('Linked accounts & recovery','connections','',true)+(APP.getSave().offlineMatch?btn('Resume offline game','resume-offline','',true):'')+btn(syncState==='conflict'?'Resolve cloud save':'Save progress now','sync','',true)+'<p>Cloud save: '+esc(syncState)+'. Offline practice and online competitive balances are stored separately.</p>';
 else if(p.relation==='friend')actions=btn(icon('swords')+'Challenge (1v1)','challenge',p.id)+btn('Remove friend','social','remove:'+p.id,true)+btn('Block player','social','block:'+p.id,true);
 else if(p.relation==='incoming')actions=btn('Accept friend request','social','accept:'+p.id)+btn('Decline','social','decline:'+p.id,true);
 else if(p.relation==='outgoing')actions=btn('Cancel friend request','social','cancel:'+p.id,true);else actions=btn('Add friend','social','request:'+p.id);
 frame(own?'Your profile':'Player profile','<div class="profile-card"><div class="profile-heading">'+avatar(p.avatar)+'<div><h3>'+esc(p.name)+'</h3><small>@'+esc(p.username)+'</small>'+state(p)+'</div></div><div class="tag-row"><code>'+esc(p.tag)+'</code><button class="icon-button" data-c="copy" data-id="'+esc(p.tag)+'" aria-label="Copy player tag">'+icon('copy')+'</button><button class="icon-button" data-c="share" data-id="'+esc(p.tag)+'" aria-label="Share profile">'+icon('link')+'</button></div><small>'+esc(p.games>=10?D.tier(p.tier).name+' - '+p.rating+' Elo':'Unranked - '+p.games+'/10 placements')+'</small></div><div class="profile-modes">'+[['ranked','Ranked'],['casual','Casual'],['friend','Friends']].map(([id,n])=>'<button class="tab '+(profileMode===id?'active':'')+'" data-c="statsmode" data-id="'+id+'">'+n+'</button>').join('')+'</div>'+statHTML+actions,'profile');}
function editProfile(){const p=profile||session.profile;selectedAvatar=p.avatar;frame('Make it yours','<div class="profile-fields"><label>Username<input id="cUsername" value="'+esc(p.username)+'" maxlength="20" autocapitalize="none" autocomplete="off"><small>Unique, 3-20 characters. Changes are limited to once every 7 days.</small></label><label>Display name<input id="cDisplayName" value="'+esc(p.name)+'" maxlength="28" autocomplete="nickname"></label><label>Avatar<div class="avatar-choices">'+['cross','ring','board','rook','crown','star'].map(v=>'<button class="avatar-choice" data-c="avatar" data-id="'+v+'" aria-label="'+v+' avatar" aria-pressed="'+(selectedAvatar===v)+'">'+avatar(v)+'</button>').join('')+'</div></label><label>Who can see my stats<select id="cStatsPrivacy"><option value="public" '+(p.statsVisibility==='public'?'selected':'')+'>Everyone</option><option value="friends" '+(p.statsVisibility==='friends'?'selected':'')+'>Friends</option><option value="private" '+(p.statsVisibility==='private'?'selected':'')+'>Only me</option></select></label><label>Online status<select id="cPresencePrivacy"><option value="friends" '+(p.presenceVisibility==='friends'?'selected':'')+'>Visible to friends</option><option value="hidden" '+(p.presenceVisibility==='hidden'?'selected':'')+'>Hidden</option></select></label></div>'+btn('Save profile','saveprofile')+'<p>Your player tag never changes, even if your username does.</p>','edit');}
function connections(){
 const available=p=>session?.providers?.[p]?.web||window.MegaNativeIdentity&&session?.providers?.[p]?.native;
 const linked=session.profile.providers;
 frame('Keep your progress','<p>Restore this profile with either linked provider. Your player tag, friends and rank stay the same.</p>'+['google','apple'].map(provider=>{
  const name=provider==='google'?'Google':'Apple',exists=linked.includes(provider);
  return '<div class="profile-card"><b>'+name+'</b><p>'+(exists?'Linked':'Not linked')+'</p>'+(exists?
   '<button class="button full quiet" data-c="signin" data-id="'+provider+'" data-intent="reauth" '+(available(provider)?'':'disabled')+'>Verify with '+name+'</button><button class="button full quiet" data-c="unlink" data-id="'+provider+'" '+(linked.length<=1?'disabled':'')+'>Unlink</button>':
   '<button class="button full quiet" data-c="signin" data-id="'+provider+'" data-intent="link" '+(available(provider)?'':'disabled')+'>Link '+name+'</button>')+'</div>';
 }).join('')+'<p>Verify again before changing linked accounts. At least one sign-in method must remain linked.</p>'+btn('Sign out on this device','signout','',true)+btn('Sign out everywhere','signout-all','',true),'connections');
}
function person(p){return '<button type="button" class="friend-person" data-c="profile" data-id="'+esc(p.id)+'">'+avatar(p.avatar,true)+'<span class="person-copy"><strong>'+esc(p.name)+'</strong><small>@'+esc(p.username)+'</small>'+state(p)+'</span>'+icon('arrow')+'</button>';}
function requestCard(p,kind){return '<div class="friend-request">'+person(p)+'<div class="request-actions">'+(kind==='incoming'?btn('Accept','social','accept:'+p.id)+btn('Decline','social','decline:'+p.id,true):btn('Cancel request','social','cancel:'+p.id,true))+'</div></div>';}
function friendsMarkup(){return '<div class="panel-head friends-head"><div class="eyebrow">Social</div><h2>Friends</h2><p>Find your people. Start a friendly rivalry.</p></div>'+(!session?.linked?'<button class="community-profile-cta" data-c="login">'+icon('shield')+'<span><strong>Save your profile</strong><small>Create or link an account to add friends.</small></span>'+icon('arrow')+'</button><div class="friend-empty"><b>Guest on this device</b><p>You can play offline without an account.</p></div>':
 '<button class="community-profile-cta" data-c="profile">'+avatar(session.profile.avatar,true)+'<span><strong>'+esc(session.profile.name)+'</strong><small>@'+esc(session.profile.username)+' - View your profile</small></span>'+icon('arrow')+'</button><form class="community-search" id="cSearch"><input id="cQuery" aria-label="Search usernames or player tags" placeholder="Username or MEGA-tag" maxlength="64" value="'+esc(friendsQuery)+'"><button class="button quiet" type="submit">Search</button></form><div class="friend-code-card"><div><span>YOUR PLAYER TAG</span><div class="friend-code">'+esc(session.profile.tag)+'</div></div><button class="copy-friend" data-c="copy" data-id="'+esc(session.profile.tag)+'" aria-label="Copy tag">'+icon('copy')+'</button><button class="copy-friend" data-c="share" data-id="'+esc(session.profile.tag)+'" aria-label="Share profile">'+icon('link')+'</button></div>'+(friendsQuery?'<h3 class="identity-section">Search results</h3>'+ (searchRows.length?searchRows.map(person).join(''):'<p class="caption">No matching player found.</p>'):'')+
 '<div class="section-title friends-section-title"><span>Friends</span><small>'+social.friends.filter(p=>p.presence.online).length+' ONLINE</small></div>'+(social.friends.length?social.friends.map(person).join(''):'<div class="friend-empty"><div class="friend-empty-icon">'+icon('usersRound')+'</div><b>Your squad is empty</b><p>Add someone by username or share your player tag.</p></div>')+
 (social.incoming.length?'<h3 class="identity-section">Friend requests</h3>'+social.incoming.map(p=>requestCard(p,'incoming')).join(''):'')+(social.outgoing.length?'<h3 class="identity-section">Sent requests</h3>'+social.outgoing.map(p=>requestCard(p,'outgoing')).join(''):'')+
 (invites.length?'<h3 class="identity-section">Challenges</h3>'+invites.map(m=>'<div class="friend-request"><b>'+esc(m.challengerName)+'</b><p class="caption">'+(m.quote.rated?'Ranked challenge':'Free friendly game')+'</p>'+btn('Review invitation','review',m.id,true)+'</div>').join(''):'')+(social.blocked.length?'<details><summary>Blocked players</summary>'+social.blocked.map(p=>'<div class="ledger"><span>'+esc(p.username)+'</span><button class="button quiet" data-c="social" data-id="unblock:'+esc(p.id)+'">Unblock</button></div>').join('')+'</details>':''));}
async function refreshFriends(render=true){if(!session?.linked||refreshing)return;refreshing=true;try{[social,invites]=await Promise.all([API.request('/api/community/friends'),NET.invitations()]);invites=invites.filter(m=>m.terms.source!=='queue');if(render&&APP.getContext().page==='friends'&&!$('#cQuery')?.matches(':focus'))APP.render();}catch(e){if(e.message==='AUTH_REQUIRED'){API.reset();session=null;}else if(render)lastError=error(e);}finally{refreshing=false;}}
async function socialAction(value){const pos=value.indexOf(':'),action=value.slice(0,pos),target=value.slice(pos+1);if(['remove','block'].includes(action)&&!confirm(action==='block'?'Block this player and remove the friendship?':'Remove this friend?'))return;await API.request('/api/community/friend',{action,target});await APP.refresh();await refreshFriends();if(profile&&profile.id===target){if(['remove','block','unblock'].includes(action))dismiss();else await openProfile(target);}}
function decorate(){const sheet=$('#sheet');if(sheet&&!sheet.hidden&&['queue','waiting'].includes(sheet.dataset.kind)&&!$('.theme-loader',sheet)){const host=$('#sheetBody');host.insertAdjacentHTML('afterbegin',loader()+'<div class="theme-loader-label">'+(sheet.dataset.kind==='queue'?'FINDING YOUR MATCH':'WAITING FOR ACCEPTANCE')+'</div><div class="queue-time" data-queue-time role="timer">0:00</div>');queuedAt=performance.now();}
 if(sheet&&!sheet.hidden&&sheet.dataset.kind==='settings'&&!$('[data-c="profile"]',sheet)){const groups=sheet.querySelectorAll('.setting-group');const group=[...groups].find(g=>g.querySelector('h4')?.textContent==='PROFILE');if(group)group.insertAdjacentHTML('afterbegin','<button class="community-profile-cta" data-c="'+(session?.linked?'profile':'login')+'">'+icon('usersRound')+'<span><strong>'+(session?.linked?'Your profile':'Save your progress')+'</strong><small>'+(session?.linked?esc(session.profile.username):'Link Google or Apple')+'</small></span>'+icon('arrow')+'</button>');}
 const party=$('#partyScreen');if(party?.dataset.view==='room'){
  const roster=$('.party-roster',party);if(roster&&!$('.lobby-wait',party)){const joined=roster.querySelectorAll('.ledger').length,ready=[...roster.querySelectorAll('.ledger b')].filter(x=>x.textContent==='Ready').length;roster.insertAdjacentHTML('afterend','<div class="lobby-wait">'+loader(true)+'<div><b>Waiting in the lobby</b><small>'+joined+' joined - '+ready+' ready</small><small>The game starts when everyone is ready.</small></div></div>');}
 }
 const home=$('#page .home-quests');if(home&&!$('#page .community-profile-cta'))home.insertAdjacentHTML('afterend','<button class="community-profile-cta" data-c="'+(session?.linked?'profile':'login')+'">'+icon('shield')+'<span><strong>'+(session?.linked?'Your profile':'Save your progress')+'</strong><small>'+(session?.linked?'Tag, linked accounts and cloud save':'Playing as guest - stored on this device')+'</small></span>'+icon('arrow')+'</button>');
 I?.refresh?.();}
function resumePrompt(id){frame('Your match is still running','<p>Reconnect to continue. Online clocks do not pause when you leave the app.</p>'+btn('Reconnect to match','resume-online',id),'resume',true);}
async function presence(){if(!session?.linked)return;try{await API.request('/api/community/presence',{foreground:!document.hidden});lastPresence=Date.now();}catch{} }
const actions={
 dismiss,guest:becomeGuest,login:()=>landing(),profile:id=>openProfile(id),edit:editProfile,connections,
 signin:(id,el)=>signIn(id,el.dataset.intent||'login'),
 statsmode:id=>{profileMode=id;showProfile();},avatar:id=>{selectedAvatar=id;document.querySelectorAll('.avatar-choice').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===id)));},
 saveprofile:async()=>{const p=await API.request('/api/account/profile',{username:$('#cUsername').value,displayName:$('#cDisplayName').value,avatar:selectedAvatar,statsVisibility:$('#cStatsPrivacy').value,presenceVisibility:$('#cPresencePrivacy').value});session.profile=p;profile=p;APP.refresh();await refreshFriends();showProfile();},
 copy:async tag=>{try{await navigator.clipboard.writeText(tag);APP.notify('Player tag copied.');}catch{APP.notify(tag);}},
 share:async tag=>{const url=location.origin+location.pathname+'#player='+encodeURIComponent(tag);try{if(navigator.share)await navigator.share({title:'Mega XO player',text:tag,url});else{await navigator.clipboard.writeText(url);APP.notify('Profile link copied.');}}catch(e){if(e.name!=='AbortError')APP.notify(tag);}},
 social:socialAction,challenge:async id=>{dismiss();await APP.challenge(id);},review:async id=>{dismiss();await APP.reviewInvite(id);},
 unlink:async provider=>{if(!confirm('Remove this sign-in method?'))return;await API.request('/api/account/unlink',{provider});session=await API.session(true);connections();},
 signout:async()=>signOut(false),'signout-all':async()=>signOut(true),
 sync:async()=>{if(syncState==='conflict'&&conflict?.remote)return chooseSave(conflict.remote);dirty=true;await saveNow();announce(syncState==='saved'?'Progress saved.':syncState==='conflict'?'A newer cloud save needs your choice.':'Will retry when connected.',syncState!=='saved');},
 'restore-choice':async()=>{await adoptCloud(conflict.remote);conflict=null;},'device-choice':useDevice,
 'resume-online':async id=>{dismiss();await APP.resumeOnline(id);},'resume-offline':()=>{dismiss();APP.resumeOffline();}
};
async function signOut(all){if(APP.getContext().playing)return announce('Finish your current match before signing out.',true);if(!confirm('Sign out'+(all?' on all devices':'')+'? Your account progress remains saved.'))return;await saveNow();if(syncState==='conflict'||dirty)return announce('Resolve your cloud save before signing out.',true);archiveCurrent();await API.request('/api/account/logout',{allDevices:all});API.reset();session=null;put(OWNER,null);suppressSave=true;APP.applyPractice(get('mega_v333_archive:guest')||D.fresh());suppressSave=false;syncState='device';APP.refresh();APP.render();landing();}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-c]');if(!el||el.disabled)return;const fn=actions[el.dataset.c];if(!fn)return;e.preventDefault();e.stopImmediatePropagation();el.disabled=true;try{await fn(el.dataset.id||'',el);}catch(err){announce(error(err),true);}finally{if(el.isConnected)el.disabled=false;}},true);
document.addEventListener('keydown',e=>{if(!panel)return;if(e.key==='Escape'&&$('[data-c="dismiss"]',panel)){e.preventDefault();dismiss();return;}if(e.key==='Tab'){const nodes=[...panel.querySelectorAll('button:not([disabled]),input,select,[tabindex="0"]')].filter(n=>n.getClientRects().length);if(nodes.length){const i=nodes.indexOf(document.activeElement);if(e.shiftKey&&(i<=0)){e.preventDefault();nodes.at(-1).focus();}else if(!e.shiftKey&&(i===nodes.length-1||i<0)){e.preventDefault();nodes[0].focus();}}}},true);
document.addEventListener('submit',async e=>{if(e.target.id!=='cSearch')return;e.preventDefault();friendsQuery=$('#cQuery').value.trim();try{searchRows=friendsQuery?await API.request('/api/community/search?q='+encodeURIComponent(friendsQuery)):[];APP.render();}catch(err){APP.notify(error(err));}});
window.addEventListener('mega:local-save',()=>{
 if(suppressSave)return;archiveCurrent();const owner=get(OWNER);if(!owner)return;
 const meta=get(META),active=session?.linked&&session.profile.id===owner;
 dirty=true;put(META,{actor:owner,revision:active?syncRevision:(meta?.actor===owner?meta.revision:0),dirty:true});
 if(!active){syncState='offline';return;}
 clearTimeout(syncTimer);syncTimer=setTimeout(saveNow,3000);
});
async function reconnectSync(){
 if(reconnecting||session?.linked||!get(OWNER)||APP.getContext().playing||panel)return;
 reconnecting=true;try{const linked=await API.session(true);if(!linked.linked||linked.profile.id!==get(OWNER))return;await syncBoot(bootVersion);await presence();await refreshFriends();}catch{syncState='offline';}finally{reconnecting=false;}
}
window.addEventListener('online',()=>{if(session?.linked){if(dirty)saveNow();presence();refreshFriends();}else reconnectSync();});
window.addEventListener('mega:sheet',decorate);
const observer=new MutationObserver(()=>{if(!panel)decorate();});observer.observe($('#app'),{childList:true,subtree:true});
document.addEventListener('mega:party-transport',e=>{const party=$('#partyScreen');if(!party)return;party.setAttribute('aria-busy',String(e.detail.pending));});
document.addEventListener('visibilitychange',()=>{presence();if(!document.hidden){refreshFriends();if(dirty)saveNow();}});
window.addEventListener('pagehide',()=>{if(!session?.linked)return;fetch('/api/community/presence',{method:'POST',credentials:'same-origin',keepalive:true,headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf},body:JSON.stringify({foreground:false})}).catch(()=>{});});
setInterval(()=>{presence();refreshFriends();if(dirty)saveNow();if(!session?.linked)reconnectSync();},15000);
setInterval(()=>{const q=$('[data-queue-time]');if(q)q.textContent=fmtTime((performance.now()-queuedAt)/1000);},1000);
window.MegaCommunity=Object.freeze({friendsMarkup,openProfile,login:landing,loader,refresh:refreshFriends,getStatus:()=>({linked:!!session?.linked,syncState,revision:syncRevision})});
APP.render();boot();
})();
