/* V3.5 additive UI. Native providers are optional; absent providers never fake ads or purchases. */
(function(){
'use strict';
const M=window.MegaMonetization,APP=window.MegaApp,API=window.MegaAccount;if(!M||!APP||!API)return;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='mega_v35_ad_cadence',parse=()=>{try{return JSON.parse(localStorage.getItem(KEY));}catch{return null;}};
const progress=M.startSession(parse());let status=null,prices=[],actor=null,busy=false,selected=null,adGeneration=0,refreshing=null,freshBotResult=null;
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(progress));}catch{}},who=()=>API.peek()?.linked?API.peek()?.profile?.id:null;
for(const r of APP.getSave().records||[])if(!progress.seen.includes(r.id))progress.seen.push(r.id);progress.seen=progress.seen.slice(-500);persist();
const button=(label,action,value='',disabled=false)=>'<button class="button quiet mono-button" data-monetization="'+action+'" data-value="'+esc(value)+'" '+(disabled?'disabled':'')+'>'+esc(label)+'</button>';
const request=(path,body,key)=>API.request('/api/monetization/'+path,body,key);
function privacyReady(){try{return window.MegaAds?.privacyState?.()?.canRequestAds===true;}catch{return false;}}
function adReady(kind){try{return window.MegaAds?.isReady?.(kind)===true;}catch{return false;}}
function safe(allowStudio=false){const c=APP.getContext();return !c.playing&&!c.onlineMatch&&!c.waitingId&&!document.hidden&&!$('#partyScreen')&&!$('#identityScreen')&&(!c.sheetKind||(allowStudio&&['monetization','purchase-review','reward-review','wallet','settings'].includes(c.sheetKind)));}
function applyFrame(){document.body.dataset.cosmeticFrame=status?.equipped||'classic';}
async function refresh(){
 if(refreshing)return refreshing;const user=who();if(!user){status=null;actor=null;applyFrame();return null;}
 refreshing=(async()=>{try{const value=await request('status');if(who()!==user)return null;actor=user;status=value;applyFrame();return value;}catch{status=null;applyFrame();return null;}finally{refreshing=null;}})();return refreshing;
}
async function loadPrices(){try{const list=await window.MegaBilling?.products?.();prices=Array.isArray(list)?list.filter(p=>M.product(p.id)&&typeof p.price==='string'&&p.price.trim()):[];}catch{prices=[];}}
function details(p){return (p.crowns?p.crowns+' Crowns = '+(p.crowns*10).toLocaleString()+' Coins of purchasing capacity. ':'')+(p.frames.length?p.frames.map(id=>M.frame(id).name).join(' and ')+'. ':'')+(p.removeAds?'Permanently removes automatic ads. Optional rewarded ads remain your choice. ':'')+(p.once?'One-time purchase. No subscription.':'Repeatable currency pack. No subscription.');}
function show(){
 const connected=!!status,remaining=status?.rewardedRemaining??0,ready=connected&&status.adMode!=='off'&&privacyReady()&&adReady('rewarded'),canReward=ready&&remaining>0&&status.serverNow>=status.rewardReadyAt;
 const products=M.PRODUCTS.map(p=>{const price=prices.find(x=>x.id===p.id),owned=status?.products.includes(p.id),unneeded=p.removeAds&&status?.adMode!=='hybrid';return '<article class="mono-product"><div><h3>'+esc(p.name)+'</h3><p>'+esc(details(p))+'</p></div>'+button(owned?'Owned':unneeded?'No automatic ads in this mode':price?'Review '+price.price:'Store unavailable','review',p.id,busy||owned||unneeded||!price||!status?.purchasesAvailable||!window.MegaBilling?.purchase)+'</article>';}).join('');
 const gallery=M.FRAMES.map(f=>{const owned=status?.frames.includes(f.id)||f.id==='classic';return '<article class="mono-frame"><div class="mono-preview" data-frame="'+f.id+'" aria-label="'+esc(f.name)+' preview"><span>X</span><span>O</span><span>X</span></div><h3>'+esc(f.name)+'</h3><p>'+esc(f.description)+'</p><small>'+(owned?'Owned':f.credits===null?'Included with Starter':f.credits+' Cosmetic Credits')+'</small>'+button(status?.equipped===f.id?'Equipped':owned?'Equip':'Review unlock','frame',f.id,busy||!connected||status?.equipped===f.id||!owned&&(f.credits===null||status.credits<f.credits))+'</article>';}).join('');
 const boost=status?.boost?'<p class="mono-notice">2x cosmetic boost active. Games started before '+esc(new Date(status.boost.endsAt).toLocaleTimeString())+' qualify even if they finish later.</p>':'';
 APP.open('Rewards & Style','<div class="mono-hub"><p class="mono-kicker">YOUR BOARD. YOUR CHOICE.</p><p>Personalise your board, earn cosmetic rewards, or choose a quieter experience. Nothing here buys Elo, moves or wins.</p>'+(!connected?'<p class="mono-notice">Link your account to save cosmetics and check availability. Purchases and ads are unavailable until your account and providers are ready.</p>'+button('Sign in','signin'):'<div class="mono-balance"><strong>'+status.credits+'</strong><span>Cosmetic Credits<br><small>Cannot be bought, exchanged, transferred or used as stakes.</small></span></div>')+'<h3>Your board collection</h3><div class="mono-gallery">'+gallery+'</div><h3>Earn without ads</h3><p>Complete a meaningful free Casual queue game for 2 Cosmetic Credits, up to 10 per UTC day. Private, Ranked, short and forfeited games do not count.</p>'+button('Collect earned credits','claim','',busy||!connected)+'<h3>Optional ad rewards</h3><p>Choose a guaranteed reward. Four ad starts per UTC day, at least two minutes apart. You can always continue playing without watching.</p>'+boost+'<p class="caption">'+(connected?remaining+' ad opportunities remaining today.':'Account required.')+(status?.removeAds?' Your automatic ads are removed. These rewards are optional.':'')+'</p>'+button('Watch ad for 5 Cosmetic Credits','reward','credits',busy||!canReward)+button('Watch ad for 10-minute 2x cosmetic boost','reward','boost',busy||!canReward||!!status?.boost)+'<p class="caption">The boost doubles only free Casual cosmetic rewards, adding at most 10 extra credits per UTC day. It never multiplies Coins, Crowns, wagers, tournament prizes or Elo. A game started during the boost may finish afterward.</p>'+(!ready?button('Check optional ad availability','prepare','',busy||!connected||status?.adMode==='off'||!window.MegaAds?.prepare):'')+(!ready?'<p class="caption">No ad is ready. Opening this page never starts one.</p>':'')+'<h3>Shop</h3><p>Prices come directly from your device store. Review exactly what you receive before opening its purchase confirmation.</p>'+products+'<div class="mono-footer">'+button('Restore purchases','restore','',busy||!connected||!window.MegaBilling?.restore)+button('Ad privacy options','privacy','',!window.MegaAds?.privacyOptions)+button('Report an ad','report','',!window.MegaAds?.reportAd)+'</div><p class="caption">Cosmetics are decorative. Existing themes and game controls stay unchanged. Coins and Crowns still follow the normal wallet rules. No wheel, subscription, purchase timer or paid rank boost.</p></div>','monetization');
}
async function open(){if(!safe(true))return;selected=null;await Promise.all([refresh(),loadPrices()]);if(safe(true))show();}
function review(id){const p=M.product(id),price=prices.find(x=>x.id===id);if(!p||!price||!status?.purchasesAvailable||status.products.includes(id)||p.removeAds&&status.adMode!=='hybrid'||!safe(true))return;selected={id,actor:who(),price:price.price};APP.open('Review purchase','<div class="mono-hub"><h3>'+esc(p.name)+'</h3><p>'+esc(details(p))+'</p><p><strong>'+esc(price.price)+'</strong> in your device store.</p><p>No competitive advantage. The store will ask you to confirm payment. Nothing has been charged.</p>'+button('Continue to device store','confirm')+button('Cancel','open')+'</div>','purchase-review');}
async function execute(action){if(busy)return;busy=true;try{await action();}catch(e){APP.notify(({AD_COOLDOWN:'Please allow two minutes between rewarded ad starts.',AD_DAILY_LIMIT:'All four ad opportunities have been used today.',AD_PENDING:'An earlier reward is awaiting verification.',BOOST_ACTIVE:'A cosmetic boost is already active.',STORE_UNAVAILABLE:'The device store is unavailable.',INSUFFICIENT_COSMETIC_CREDITS:'Not enough Cosmetic Credits.',MATCH_ACTIVE:'Finish or leave your current match or lobby first.'})[e.message]||'This action could not be completed. Your balance has not been changed without verification.');}finally{busy=false;await refresh();if(APP.getContext().sheetKind==='monetization')show();}}
async function reward(kind){
 if(!safe(true)||!status||status.adMode==='off'||!privacyReady()||!adReady('rewarded'))return;
 const title=kind==='boost'?'Watch for a cosmetic boost':'Watch for 5 Cosmetic Credits';
 APP.open(title,'<div class="mono-hub"><p>'+(kind==='boost'?'Complete one rewarded ad to activate 2x free Casual cosmetic earnings for ten minutes. Maximum 10 extra credits today.':'Complete one rewarded ad to receive exactly 5 Cosmetic Credits.')+'</p><p>Ad length depends on the provider. No click, install or purchase is required. Closing early may not earn a reward. Starting reserves one of four daily opportunities, including a failed or skipped start.</p>'+button('Watch ad','watch',kind)+button('Not now','open')+'</div>','reward-review');
}
async function watch(kind){await execute(async()=>{if(!safe(true)||!privacyReady()||!adReady('rewarded')||!who())return;const user=who(),generation=adGeneration,ticket=await request('reward-ticket',{kind});if(who()!==user||generation!==adGeneration||!safe(true)||!privacyReady()||!adReady('rewarded'))return;APP.close();M.noteFullScreen(progress,'rewarded');persist();await window.MegaAds.showRewarded(ticket);if(who()!==user)return;await refresh();if(safe())show();APP.notify('Rewards are delivered only after server verification. Refresh this page if confirmation is still pending.');});}
function decorate(){const page=$('#page'),c=APP.getContext();if(page&&['play','quests'].includes(c.page)&&!page.querySelector('[data-monetization="open"]')){const div=document.createElement('div');div.className='mono-entry';div.innerHTML='<button class="button quiet" data-monetization="open">Rewards & Style</button><p class="caption">Your board collection, optional rewards and shop.</p>';page.append(div);}if(['wallet','settings'].includes(c.sheetKind)&&!$('#sheetBody')?.querySelector('[data-monetization="open"]'))$('#sheetBody')?.insertAdjacentHTML('beforeend','<div class="mono-entry">'+button('Rewards & Style','open')+'</div>');}
function adContext(){const c=APP.getContext();return {adMode:status?.adMode,entitlementsKnown:!!status&&status.actor===who(),removeAds:status?.removeAds,consentReady:privacyReady(),adReady:adReady('interstitial'),transition:'result_to_home',gameMode:'bot',safe:safe(),playing:c.playing,onlineMatch:c.onlineMatch,queued:!!c.waitingId,partyOpen:!!$('#partyScreen'),hidden:document.hidden,modalOpen:!!c.sheetKind};}
async function automatic(generation){if(busy||!M.interstitialAllowed(progress,adContext()))return;const user=who(),started=Date.now();let presenting=false;try{const permit=await request('interstitial-permit',{});if(busy||Date.now()-started>1500||generation!==adGeneration||user!==who()||!permit.allowed||!M.interstitialAllowed(progress,adContext()))return;busy=true;presenting=true;M.noteFullScreen(progress,'interstitial');persist();await window.MegaAds.showInterstitial();}catch{}finally{if(presenting)busy=false;}}
window.addEventListener('mega:local-save',()=>{const r=APP.getSave().records?.at(-1);if(M.noteGame(progress,r)){freshBotResult=r.id;persist();const c=APP.getContext();if(!document.hidden&&!c.playing&&!c.onlineMatch&&!c.waitingId&&!$('#partyScreen')&&!$('#identityScreen')&&c.mode==='bot'&&status?.adMode==='hybrid'&&!status.removeAds&&privacyReady()&&progress.sessions>1&&Date.now()-progress.firstSeenAt>=M.POLICY.firstAdAge&&progress.totalGames>=M.POLICY.firstAdGames)Promise.resolve(window.MegaAds?.prepare?.('interstitial')).catch(()=>{});}});
document.addEventListener('click',e=>{
 const node=e.target.closest('button,[data-action]');if(!node)return;const action=node.dataset.monetization;
 const isResultHome=freshBotResult===APP.getSave().records?.at(-1)?.id&&node.dataset.action==='home'&&APP.getContext().sheetKind==='result'&&APP.getContext().mode==='bot'&&!APP.getContext().onlineMatch&&M.meaningfulBot(APP.getSave().records?.at(-1));
 freshBotResult=null;adGeneration++;if(isResultHome){const generation=adGeneration;queueMicrotask(()=>automatic(generation));}
 if(node.dataset.action==='buy'||node.dataset.action==='billing'){e.preventDefault();e.stopImmediatePropagation();const id=node.dataset.value;open().then(()=>{if(node.dataset.action==='buy')review(id);});return;}
 if(!action||node.disabled)return;e.preventDefault();e.stopPropagation();const value=node.dataset.value;
 if(action==='open')open();else if(action==='signin'){APP.close();window.MegaCommunity?.login?.();}else if(action==='review')review(value);else if(action==='reward')reward(value);else if(action==='watch')watch(value);
 else if(action==='confirm')execute(async()=>{const p=selected;if(!p||p.actor!==who()||!safe(true))return;selected=null;const evidence=await window.MegaBilling.purchase(p.id);if(who()!==p.actor)throw Error('AUTH_REQUIRED');await request('purchase',{evidence});await window.MegaBilling.acknowledge?.(evidence);await APP.refresh();await refresh();if(safe(true))show();APP.notify('Verified purchase delivered.');});
 else if(action==='restore')execute(async()=>{const user=who(),receipts=await window.MegaBilling.restore();if(user!==who()||!Array.isArray(receipts)||receipts.length>50)throw Error('INVALID_RECEIPT');for(const evidence of receipts)await request('restore',{evidence});APP.notify('Verified non-consumable purchases restored.');});
 else if(action==='claim')execute(async()=>{const r=await request('claim',{});APP.notify((r.base+r.bonus)+' earned Cosmetic Credits collected.');});
 else if(action==='frame'){const owned=status?.frames.includes(value);if(owned)execute(()=>request('equip',{frame:value}));else{const f=M.frame(value);APP.open('Unlock '+f.name,'<p>Spend '+f.credits+' Cosmetic Credits to unlock and equip this decorative frame. No Coins or Crowns are spent.</p>'+button('Unlock and equip','redeem',value)+button('Cancel','open'),'purchase-review');}}
 else if(action==='redeem')execute(async()=>{await request('redeem',{frame:value});await refresh();if(safe(true))show();});
 else if(action==='prepare')execute(async()=>{if(!safe(true)||!status||status.adMode==='off')return;await window.MegaAds.privacyOptions?.();if(!safe(true)||!privacyReady())return;await window.MegaAds.prepare('rewarded');});
 else if(action==='privacy')execute(()=>window.MegaAds.privacyOptions());else if(action==='report')execute(()=>window.MegaAds.reportAd());
},true);
window.addEventListener('mega:sheet',decorate);new MutationObserver(decorate).observe($('#page'),{childList:true});
setInterval(()=>{if(who()!==actor){status=null;applyFrame();refresh();}},2000);
document.addEventListener('visibilitychange',()=>{adGeneration++;if(!document.hidden)refresh();});
window.MegaXO=Object.freeze({...window.MegaXO,version:'3.5.0-monetisation-1'});
window.MegaMonetizationUI=Object.freeze({open,refresh});decorate();refresh();
})();
