/* V4.1 rewards UI. Native providers are optional; absent providers never fake ads or purchases. */
(function(){
'use strict';
const M=window.MegaMonetization,APP=window.MegaApp,API=window.MegaAccount;if(!M||!APP||!API)return;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='mega_v35_ad_cadence',parse=()=>{try{return JSON.parse(localStorage.getItem(KEY));}catch{return null;}};
const progress=M.startSession(parse());let status=null,prices=[],actor=null,busy=false,selected=null,adGeneration=0,refreshing=null,freshBotResult=null;
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(progress));}catch{}},who=()=>API.peek()?.linked?API.peek()?.profile?.id:null;
for(const r of APP.getSave().records||[])if(!progress.seen.includes(r.id))progress.seen.push(r.id);progress.seen=progress.seen.slice(-500);persist();
const button=(label,action,value='',disabled=false)=>'<button class="button quiet mono-button" data-monetization="'+action+'" data-value="'+esc(value)+'" '+(disabled?'disabled':'')+'>'+esc(label)+'</button>';
const request=(path,body,key)=>API.request('/api/monetization/'+path,body,key);
function adPlatform(){const p=window.MegaAds?.platform;return p==='android'||p==='ios'?p:null;}
function privacyReady(){try{return window.MegaAds?.privacyState?.()?.canRequestAds===true;}catch{return false;}}
function adReady(kind){try{return window.MegaAds?.isReady?.(kind)===true;}catch{return false;}}
function safe(allowStudio=false){const c=APP.getContext();return !c.playing&&!c.onlineMatch&&!c.waitingId&&!document.hidden&&!$('#partyScreen')&&!$('#identityScreen')&&(!c.sheetKind||(allowStudio&&['purchase-review','reward-review','wallet','settings'].includes(c.sheetKind)));}
async function refresh(){
 if(refreshing)return refreshing;const user=who();if(!user){status=null;actor=null;return null;}
 refreshing=(async()=>{try{const value=await request('status');if(who()!==user)return null;actor=user;status=value;return value;}catch{status=null;return null;}finally{refreshing=null;}})();return refreshing;
}
async function loadPrices(){try{const list=await window.MegaBilling?.products?.(status?.storeContext||null);prices=Array.isArray(list)?list.filter(p=>M.product(p.id)&&typeof p.price==='string'&&p.price.trim()):[];}catch{prices=[];}}
function details(p){return (p.crowns?p.crowns+' Crowns = '+(p.crowns*10).toLocaleString()+' Coins of purchasing capacity. ':'')+(p.removeAds?'Permanently removes automatic ads. Optional rewarded ads remain your choice. ':'')+(p.once?'One-time purchase. No subscription.':'Repeatable currency pack. No subscription.');}
function themeGallery(){const active=APP.getSave()?.settings?.theme||'vector',themes=[['vector','Vector Light','Clean lines and bright contrast.'],['midnight','Midnight Club','Slate surfaces with soft light and lime accents.'],['paperclub','Paper Club','Warm paper, ink and hand-drawn character.'],['afterhours','After Hours','Arcade glow with no strobe effects.']];return '<div class="mono-theme-grid" aria-label="Themes">'+themes.map(([id,name,desc])=>'<button class="theme-card mono-theme-card '+(active===id?'active':'')+'" data-action="theme" data-value="'+id+'" aria-pressed="'+(active===id)+'"><span class="theme-preview '+id+'"><span class="sample-x">X</span><span class="sample-o">O</span></span><b>'+name+'</b><small>'+desc+'</small></button>').join('')+'</div>';}
function pageMarkup(){
 const connected=!!status,remaining=status?.rewardedRemaining??0,ready=connected&&status.adMode!=='off'&&privacyReady()&&adReady('rewarded'),canReward=ready&&remaining>0&&status.serverNow>=status.rewardReadyAt;
 const products=M.PRODUCTS.map(p=>{const price=prices.find(x=>x.id===p.id),owned=status?.products.includes(p.id),unneeded=p.removeAds&&status?.adMode!=='hybrid';return '<article class="mono-product"><div><h3>'+esc(p.name)+'</h3><p>'+esc(details(p))+'</p></div>'+button(owned?'Owned':unneeded?'No automatic ads in this mode':price?'Review '+price.price:'Store unavailable','review',p.id,busy||owned||unneeded||!price||!status?.purchasesAvailable||!window.MegaBilling?.purchase)+'</article>';}).join('');
 const boost=status?.boost?'<p class="mono-notice">2x cosmetic boost active. Games started before '+esc(new Date(status.boost.endsAt).toLocaleTimeString())+' qualify even if they finish later.</p>':'';
 const balance=connected?'<div class="mono-balance"><div><span class="mono-balance-label">COSMETIC CREDITS</span><strong>'+status.credits+'</strong></div><p>Earn them through play or optional rewarded ads. Cosmetic Credits can be used for future cosmetic releases.</p></div>':'<div class="mono-balance mono-balance-guest"><div><span class="mono-balance-label">COSMETIC CREDITS</span><strong>--</strong></div><p>Sign in to save Cosmetic Credits and access rewards and purchases.</p>'+button('Sign in or create profile','signin')+'</div>';
 return '<div class="mono-page">'+
  '<header class="mono-page-head"><button class="button quiet mono-back" data-action="nav" data-value="play">Back to Play</button><p class="mono-kicker">STYLE &amp; REWARDS</p><h2>Rewards &amp; Themes</h2><p>Earn cosmetic rewards, choose your look and manage optional store purchases in one place.</p></header>'+
  balance+
  '<section class="mono-section"><div class="mono-section-head"><div><p class="mono-kicker">PLAY TO EARN</p><h3>Casual rewards</h3></div><span class="pill">2 Credits / game</span></div><p>Complete a qualifying free Casual queue game for 2 Cosmetic Credits, up to 10 per UTC day.</p>'+button('Collect earned credits','claim','',busy||!connected)+'</section>'+
  '<section class="mono-section"><div class="mono-section-head"><div><p class="mono-kicker">OPTIONAL REWARDS</p><h3>Watch &amp; earn</h3></div><span class="pill">'+(connected?remaining+' / 4 left':'Sign in')+'</span></div><p>Choose a reward. Up to four rewarded ads per UTC day, at least two minutes apart.</p>'+boost+
  '<div class="mono-reward-grid"><article class="mono-reward-card"><b>5 Cosmetic Credits</b><p>Add credits directly to your cosmetic balance.</p>'+button('Watch rewarded ad','reward','credits',busy||!canReward)+'</article><article class="mono-reward-card"><b>10-minute 2x boost</b><p>Double qualifying Casual Cosmetic Credit rewards, up to 10 bonus credits per UTC day.</p>'+button('Watch for boost','reward','boost',busy||!canReward||!!status?.boost)+'</article></div>'+
  (!ready?button('Check ad availability','prepare','',busy||!connected||status?.adMode==='off'||!window.MegaAds?.prepare):'')+
  '<p class="caption">'+(connected?(remaining+' rewarded ads remaining today.'):'Sign in to earn rewards.')+(status?.removeAds?' Automatic ads are off. Rewarded ads are still optional.':'')+(!ready&&connected?' No rewarded ad is available right now.':'')+'</p></section>'+
  '<section class="mono-section"><div class="mono-section-head"><div><p class="mono-kicker">THEMES</p><h3>Choose your style</h3></div><span class="pill">4 included</span></div><p>Switch the entire Mega XO look whenever you want. Current themes are free to use.</p>'+themeGallery()+'<p class="caption">Cosmetic Credits can be used for future cosmetic releases.</p></section>'+
  '<section class="mono-section mono-shop"><div class="mono-section-head"><div><p class="mono-kicker">STORE</p><h3>Crowns &amp; Remove Ads</h3></div></div><p>Optional purchases do not change skill rating or game rules.</p><div class="mono-product-list">'+products+'</div></section>'+
  '<div class="mono-footer">'+button('Restore purchases','restore','',busy||!connected||!window.MegaBilling?.restore)+button('Ad privacy options','privacy','',!window.MegaAds?.privacyOptions)+button('Report an ad','report','',!window.MegaAds?.reportAd)+'</div>'+
 '</div>';
}
function show(){if(APP.getContext().page==='rewards')APP.render();}
async function open(){if(!safe(true))return;selected=null;APP.close();APP.goRewards();await refresh();await loadPrices();if(safe(true)&&APP.getContext().page==='rewards')show();}
function review(id){const p=M.product(id),price=prices.find(x=>x.id===id);if(!p||!price||!status?.purchasesAvailable||status.products.includes(id)||p.removeAds&&status?.adMode!=='hybrid'||!safe(true))return;selected={id,actor:who(),price:price.price};APP.open('Review purchase','<div class="mono-hub"><h3>'+esc(p.name)+'</h3><p>'+esc(details(p))+'</p><p><strong>'+esc(price.price)+'</strong> in your device store.</p><p>No competitive advantage. The store will ask you to confirm payment. Nothing has been charged.</p>'+button('Continue to device store','confirm')+button('Cancel','open')+'</div>','purchase-review');}
async function execute(action){if(busy)return;busy=true;try{await action();}catch(e){APP.notify(({AD_COOLDOWN:'Please allow two minutes between rewarded ad starts.',AD_DAILY_LIMIT:'All four ad opportunities have been used today.',AD_PENDING:'An earlier reward is awaiting verification.',BOOST_ACTIVE:'A cosmetic boost is already active.',STORE_UNAVAILABLE:'The device store is unavailable.',INSUFFICIENT_COSMETIC_CREDITS:'Not enough Cosmetic Credits.',MATCH_ACTIVE:'Finish or leave your current match or lobby first.'})[e.message]||'This action could not be completed. Your balance has not been changed without verification.');}finally{busy=false;await refresh();if(APP.getContext().page==='rewards'&&!APP.getContext().sheetKind)show();}}
async function reward(kind){
 if(!safe(true)||!status||status.adMode==='off'||!privacyReady()||!adReady('rewarded'))return;
 const title=kind==='boost'?'Watch for a cosmetic boost':'Watch for 5 Cosmetic Credits';
 APP.open(title,'<div class="mono-hub"><p>'+(kind==='boost'?'Complete one rewarded ad to activate 2x free Casual cosmetic earnings for ten minutes. Maximum 10 extra credits today.':'Complete one rewarded ad to receive exactly 5 Cosmetic Credits.')+'</p><p>Ad length varies. No click, install or purchase is required. Closing early may not earn a reward. Starting reserves one of four daily opportunities, including a failed or skipped start.</p>'+button('Watch ad','watch',kind)+button('Not now','open')+'</div>','reward-review');
}
async function watch(kind){await execute(async()=>{if(!safe(true)||!privacyReady()||!adReady('rewarded')||!who())return;const user=who(),generation=adGeneration,platform=adPlatform();if(!platform)throw Error('ADS_UNAVAILABLE');const ticket=await request('reward-ticket',{kind,platform});if(who()!==user||generation!==adGeneration||!safe(true)||!privacyReady()||!adReady('rewarded'))return;APP.close();M.noteFullScreen(progress,'rewarded');persist();await window.MegaAds.showRewarded(ticket);if(who()!==user)return;await refresh();if(safe())show();APP.notify('Your reward may take a moment to appear.');});}
function decorate(){const page=$('#page'),c=APP.getContext();if(page&&['play','quests'].includes(c.page)&&!page.querySelector('[data-monetization="open"]')){const div=document.createElement('div');div.className='mono-entry';div.innerHTML='<button class="button quiet" data-monetization="open">Rewards & Themes</button><p class="caption">Cosmetic rewards, themes and optional store purchases.</p>';page.append(div);}if(['wallet','settings'].includes(c.sheetKind)&&!$('#sheetBody')?.querySelector('[data-monetization="open"]'))$('#sheetBody')?.insertAdjacentHTML('beforeend','<div class="mono-entry">'+button('Rewards & Themes','open')+'</div>');}
function adContext(){const c=APP.getContext();return {adMode:status?.adMode,entitlementsKnown:!!status&&status.actor===who(),removeAds:status?.removeAds,consentReady:privacyReady(),adReady:adReady('interstitial'),transition:'result_to_home',gameMode:'bot',safe:safe(),playing:c.playing,onlineMatch:c.onlineMatch,queued:!!c.waitingId,partyOpen:!!$('#partyScreen'),hidden:document.hidden,modalOpen:!!c.sheetKind};}
async function automatic(generation){if(busy||!M.interstitialAllowed(progress,adContext()))return;const user=who(),started=Date.now();let presenting=false;try{const platform=adPlatform();if(!platform)return;const permit=await request('interstitial-permit',{platform});if(busy||Date.now()-started>1500||generation!==adGeneration||user!==who()||!permit.allowed||!M.interstitialAllowed(progress,adContext()))return;busy=true;presenting=true;M.noteFullScreen(progress,'interstitial');persist();await window.MegaAds.showInterstitial(permit);}catch{}finally{if(presenting)busy=false;}}
window.addEventListener('mega:local-save',()=>{const r=APP.getSave().records?.at(-1);if(M.noteGame(progress,r)){freshBotResult=r.id;persist();const c=APP.getContext();if(!document.hidden&&!c.playing&&!c.onlineMatch&&!c.waitingId&&!$('#partyScreen')&&!$('#identityScreen')&&c.mode==='bot'&&status?.adMode==='hybrid'&&!status.removeAds&&privacyReady()&&progress.sessions>1&&Date.now()-progress.firstSeenAt>=M.POLICY.firstAdAge&&progress.totalGames>=M.POLICY.firstAdGames)Promise.resolve(window.MegaAds?.prepare?.('interstitial')).catch(()=>{});}});
document.addEventListener('click',e=>{
 const node=e.target.closest('button,[data-action]');if(!node)return;const action=node.dataset.monetization;
 const isResultHome=freshBotResult===APP.getSave().records?.at(-1)?.id&&node.dataset.action==='home'&&APP.getContext().sheetKind==='result'&&APP.getContext().mode==='bot'&&!APP.getContext().onlineMatch&&M.meaningfulBot(APP.getSave().records?.at(-1));
 freshBotResult=null;adGeneration++;if(isResultHome){const generation=adGeneration;queueMicrotask(()=>automatic(generation));}
 if(node.dataset.action==='buy'||node.dataset.action==='billing'){e.preventDefault();e.stopImmediatePropagation();const id=node.dataset.value;open().then(()=>{if(node.dataset.action==='buy')review(id);});return;}
 if(!action||node.disabled)return;e.preventDefault();e.stopPropagation();const value=node.dataset.value;
 if(action==='open')open();else if(action==='signin'){APP.close();window.MegaCommunity?.login?.();}else if(action==='review')review(value);else if(action==='reward')reward(value);else if(action==='watch')watch(value);
 else if(action==='confirm')execute(async()=>{const p=selected;if(!p||p.actor!==who()||!safe(true))return;selected=null;const evidence=await window.MegaBilling.purchase(p.id,status?.storeContext||null);if(who()!==p.actor)throw Error('AUTH_REQUIRED');const delivered=await request('purchase',{evidence});await window.MegaBilling.finish?.(evidence,delivered);await APP.refresh();await refresh();APP.close();show();APP.notify('Verified purchase delivered.');});
 else if(action==='restore')execute(async()=>{const user=who(),receipts=await window.MegaBilling.restore(status?.storeContext||null);if(user!==who()||!Array.isArray(receipts)||receipts.length>50)throw Error('INVALID_RECEIPT');for(const evidence of receipts)await request('restore',{evidence});APP.notify('Verified non-consumable purchases restored.');});
 else if(action==='claim')execute(async()=>{const r=await request('claim',{});APP.notify((r.base+r.bonus)+' earned Cosmetic Credits collected.');});
 else if(action==='prepare')execute(async()=>{if(!safe(true)||!status||status.adMode==='off')return;await window.MegaAds.privacyOptions?.();if(!safe(true)||!privacyReady())return;await window.MegaAds.prepare('rewarded');});
 else if(action==='privacy')execute(()=>window.MegaAds.privacyOptions());else if(action==='report')execute(()=>window.MegaAds.reportAd());
},true);
window.addEventListener('mega:sheet',decorate);new MutationObserver(decorate).observe($('#page'),{childList:true});
setInterval(()=>{if(who()!==actor){status=null;refresh().then(()=>show());}},2000);
document.addEventListener('visibilitychange',()=>{adGeneration++;if(!document.hidden)refresh().then(()=>show());});
window.MegaXO=Object.freeze({...window.MegaXO,version:'3.5.1-auth-themes'});
window.MegaMonetizationUI=Object.freeze({open,refresh,pageMarkup});decorate();refresh();
})();
