/* V3.3 additive UI module. Existing theme CSS, economy, icons and one-on-one controller are untouched. */
(()=>{
'use strict';
const T=window.MegaTournament,G=window.MegaGame,I=window.MegaIcons;
if(!T||!G)return;
const $=(s,root=document)=>root.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2),fmt=n=>n===null?'\u221e':Math.floor(Math.ceil(Math.max(0,n))/60)+':'+String(Math.ceil(Math.max(0,n))%60).padStart(2,'0'),num=n=>Number(n).toLocaleString('en-US');
const icon=n=>I?.icon(n)||'',button=(text,action,extra='',quiet=false)=>'<button type="button" class="button '+(quiet?'quiet':'')+'" data-party="'+action+'" '+extra+'>'+text+'</button>';
let screen=null,body=null,room=null,session=null,transport='local',activeFixture=null,poll=null,viewName='hub',lastRevision=-1,offset=0,capabilities=null,busy=false,savedFocus=null;
try{session=JSON.parse(localStorage.getItem('mega_party_session')||'null');}catch{}
const saved=()=>{try{return JSON.parse(localStorage.getItem('mega_party_local')||'null');}catch{return null;}};
const networkSaved=()=>{try{return JSON.parse(localStorage.getItem('mega_party_network_room')||'null');}catch{return null;}};
function persist(){if(transport==='local'&&room)try{localStorage.setItem('mega_party_local',JSON.stringify(room));}catch{}}
// Tournaments is a first-class home mode in app.js. Selecting the card only selects it;
// the shared Start/Browse CTA calls MegaParties.tables().
function shell(title){if(!screen){savedFocus=document.activeElement;screen=document.createElement('section');screen.id='partyScreen';screen.className='party-screen';screen.setAttribute('aria-label','Private rooms and tournaments');screen.innerHTML='<div class="party-top"><button class="icon-button" data-party="back" aria-label="Back">'+icon('back')+'</button><h2></h2><button class="icon-button" data-party="rules" aria-label="Tournament rules">'+icon('help')+'</button></div><p id="partyMessage" role="status" aria-live="polite" hidden></p><div id="partyBody" class="party-body"></div>';$('#app').append(screen);body=$('#partyBody');}screen.dataset.view=viewName;$('.party-top h2',screen).textContent=title;I?.refresh?.();}
function message(text){const el=$('#partyMessage');if(el){el.textContent=text;el.hidden=!text;}}
function hide(){const refreshWallet=room?.table&&room?.status==='COMPLETE';clearInterval(poll);poll=null;screen?.remove();screen=null;body=null;activeFixture=null;savedFocus?.focus?.();if(refreshWallet)location.reload();}
function setBody(html){body.innerHTML=html;I?.refresh?.();}
function hub(){viewName='hub';activeFixture=null;shell('Private rooms');const resume=saved();const choice=(action,iconName,title,copy,quiet=false)=>'<button type="button" class="party-choice '+(quiet?'quiet':'')+'" data-party="'+action+'"><span class="party-choice-icon">'+icon(iconName)+'</span><span class="party-choice-copy"><strong>'+title+'</strong><small>'+copy+'</small></span><span class="party-choice-arrow">'+icon('arrow')+'</span></button>';setBody('<div class="party-page-intro"><span class="party-kicker">PRIVATE PLAY</span><h3>Bring everyone into the same room.</h3><p>Free private play for 2–10 people. Pick the connection that fits your group.</p></div><div class="party-room-choices">'+choice('local','users','One device','Pass & play on a single phone')+choice('lan','link','Same Wi-Fi','Separate phones, no internet required')+choice('online','globe','Online private room','Invite people from anywhere')+choice('friends','swords','Challenge a friend (1v1)','Quick head-to-head',true)+(resume&&!['COMPLETE','VOID','CANCELLED'].includes(resume.status)?choice('continue','refresh','Continue saved tournament','Resume this device\'s last private event',true):'')+(networkSaved()?choice('reconnect','route','Reconnect to your room','Return to your saved network room',true):'')+'</div><div class="party-info-card"><b>Private tournament options</b><p>Host up to 10 people and choose League, Knockout, or Groups + Knockout. Private rooms never charge Coins or Crowns.</p></div>');}
function tables(){viewName='tables';activeFixture=null;shell('Tournaments');setBody('<div class="party-page-intro party-tournament-intro"><span class="party-kicker">10-PLAYER TABLES</span><h3>Choose your stakes.</h3><p>Equal entries. Groups + Knockout. Finish fifth to recover your entry; finish higher to profit.</p></div><div class="party-tables">'+Object.keys(T.TABLES).map(key=>{const q=T.prize(key),currency=q.currency.toLowerCase(),currencyIcon=currency==='crowns'?'crown':'coin';return '<article class="party-table card" data-table-tier="'+key+'"><div class="party-table-head"><h3>'+q.name+'</h3><span class="party-currency">'+icon(currencyIcon)+currency.toUpperCase()+'</span></div><div class="party-entry"><span>ENTRY / PLAYER</span><strong>'+num(q.entry)+'</strong><small>'+currency+'</small></div><div class="party-table-stats"><div><span>Total pool</span><b>'+num(q.pool)+'</b></div><div><span>1st place</span><b>'+num(q.payouts[0])+'</b></div></div>'+button('View payouts & join','table','data-table="'+key+'"',true)+'</article>';}).join('')+'</div><div class="party-info-card party-prize-note"><b>Prize curve</b><p>Top four profit, fifth breaks even, and 10% of the pool is burned. This is separate from the normal two-player ranked split.</p></div>');}
function table(key){const q=T.prize(key);viewName='table';shell(q.name+' table');setBody('<p>Entry: <b>'+q.entry+' '+q.currency+'</b> per player.</p><div class="party-standings"><table><thead><tr><th>Place</th><th>Payout</th><th>Net</th></tr></thead><tbody>'+q.payouts.map((n,i)=>'<tr><th>'+(i+1)+'</th><td>'+n+'</td><td>'+(n-q.entry>0?'+':'')+(n-q.entry)+'</td></tr>').join('')+'</tbody></table></div><p class="caption">Ten confirmed players are required. Entries are reserved together only after everyone readies. Burn: '+q.burn+' '+q.currency+'. Your entry stays reserved until the event ends. No rebuys, mid-event top-ups or extra per-game fees.</p>'+button('Join table','joinPublic','data-table="'+key+'"')+'<p class="caption">Match clock: 2 minutes each + 1 second per move. Tournament placements do not change your normal Elo.</p>');}
async function request(path,options={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),6000);try{const response=await fetch('/api/party/'+path,{...options,signal:controller.signal,credentials:'same-origin',headers:{...(session?.token&&transport==='lan'?{Authorization:'Bearer '+session.token}:{}),...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});let data;try{data=await response.json();}catch{throw Error('SERVICE_UNAVAILABLE');}if(!response.ok)throw Error(data.error||'SERVICE_UNAVAILABLE');return data;}finally{clearTimeout(timeout);}}
async function connect(which){transport=which;if(which==='lan')try{session=JSON.parse(localStorage.getItem('mega_party_session')||'null');}catch{}try{capabilities=await request('capabilities');if(which==='lan'&&!capabilities.lan)throw Error('LAN_HOST_REQUIRED');if(which==='online'&&!capabilities.online)throw Error('ONLINE_SERVICE_REQUIRED');setup(false);}catch{viewName='connection';shell(which==='lan'?'Same Wi-Fi':'Online rooms');setBody(which==='lan'?'<p>One host device runs the local room server. Connect every phone to the same router or hotspot, then open the address printed by the host.</p><code class="party-command">node server/party-server.js</code><p class="caption">The host can be a laptop on your Wi-Fi. It must stay awake. Internet is not required. A phone browser cannot start this server by itself; phone-only hosting needs the native app integration.</p>'+button('Back','hub','',true):'<p>The online room service is not connected here yet.</p>'+button('Back','hub','',true));}}
function setup(joining=false){viewName=joining?'join':'create';shell(joining?'Join a room':'Create a room');setBody('<label class="field">'+(transport==='local'?'Player names - one per line':'Your display name')+(transport==='local'?'<textarea id="partyNames" rows="5" maxlength="360" placeholder="Enter 2 to 10 names"></textarea>':'<input id="partyName" maxlength="32" value="'+esc(session?.name||'')+'" autocomplete="nickname">')+'</label>'+(joining?'<label class="field">Room code<input id="partyCode" maxlength="10" autocapitalize="characters" autocomplete="off"></label>':'<div class="two-fields"><label class="field">Format<select id="partyFormat"><option value="mixed">Groups + Knockout</option><option value="league">League</option><option value="knockout">Knockout</option><option value="duel">Two-player match</option></select></label><label class="field">Clock<select id="partyClock"><option value="180">3 min + 2 sec</option><option value="120">2 min + 2 sec</option><option value="300">5 min + 2 sec</option><option value="0">Off (private only)</option></select></label></div>')+button(joining?'Join room':'Create free room',joining?'joinRoom':'createRoom')+(transport!=='local'?button(joining?'Create instead':'I have a room code',joining?'createForm':'joinForm','',true):'')+'<p class="caption">Private rooms never charge Coins or Crowns and do not affect global stats, Elo or weekly rewards.</p>');}
async function identity(){if(transport!=='lan')return;const name=$('#partyName')?.value.trim();if(!session){if(!name)throw Error('ENTER_NAME');session=await request('session',{method:'POST',body:JSON.stringify({name})});localStorage.setItem('mega_party_session',JSON.stringify(session));}}
async function command(cmd){if(transport==='local'){const now=Date.now();switch(cmd.type){case 'start':room.players.forEach(p=>T.ready(room,p.id,true,room.rulesVersion));T.start(room,room.owner,shuffle(room.players.map(p=>p.id)),now);break;case 'matchReady':T.readyGame(room,cmd.fixture,cmd.actor,now);break;case 'move':T.move(room,cmd.fixture,cmd.actor,cmd.revision,cmd.move,now);break;case 'resign':T.resign(room,cmd.fixture,cmd.actor,now);break;case 'pause':T.pause(room,room.owner,now);break;case 'resume':T.resume(room,room.owner,now);break;default:throw Error('INVALID_LOCAL_COMMAND');}persist();return T.view(room,now);}const result=await request('command',{method:'POST',headers:{'Idempotency-Key':uid()},body:JSON.stringify({...cmd,id:cmd.id||room?.id})});offset=result.serverNow-Date.now();return result;}
function shuffle(ids){const a=ids.slice();for(let i=a.length-1;i>0;i--){const v=new Uint32Array(1);crypto.getRandomValues(v);const j=v[0]%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
async function createRoom(){if(transport==='local'){const names=$('#partyNames').value.split(/\n|,/).map(s=>s.trim()).filter(Boolean);if(names.length<2||names.length>10)throw Error('ENTER_2_TO_10_NAMES');const ids=names.map(()=>uid());room=T.create({id:uid(),owner:ids[0],sequential:true,format:$('#partyFormat').value,clock:Number($('#partyClock').value),increment:2});names.forEach((name,i)=>T.join(room,ids[i],name));session={actor:ids[0]};persist();}else{await identity();room=await command({type:'create',format:$('#partyFormat').value,clock:Number($('#partyClock').value),increment:2});}showRoom();startPolling();}
async function joinRoom(){await identity();room=await command({type:'join',id:$('#partyCode').value.trim().toUpperCase()});showRoom();startPolling();}
function me(){return transport==='local'?room.owner:session?.actor;}
async function ensureOnlineActor(){if(transport==='online')session=await request('me');}
function player(id){return room.players.find(p=>p.id===id)?.name||id||'TBD';}
function showRoom(){viewName='room';activeFixture=null;if(transport!=='local')try{localStorage.setItem('mega_party_network_room',JSON.stringify({id:room.id,transport}));}catch{}drawRoom();}
function drawRoom(){if(!room)return;shell(room.table?T.TABLES[room.table].name+' tournament':'Private room');message('');const isHost=transport==='local'||room.owner===me(),playing=room.status==='RUNNING';const mine=room.players.find(p=>p.id===me());
 let html='<div class="party-room-heading"><span class="pill">'+(room.table?'Public':transport==='local'?'One device':transport==='lan'?'Same Wi-Fi':'Online')+'</span><b>'+esc(room.format==='mixed'?'Groups + Knockout':room.format)+'</b>'+(!room.table&&transport!=='local'?button('Copy invite','copy','',true):'')+'</div>';
 if(transport!=='local'&&!room.table)html+='<div class="note"><b>Room '+esc(room.code)+'</b><br>'+esc(location.origin)+'</div>';
 if(room.status==='LOBBY'){
  html+='<h3>'+room.players.length+' / '+room.capacity+' players</h3><div class="party-roster">'+room.players.map(p=>'<div class="ledger"><span>'+esc(p.name)+(p.id===room.owner?' (host)':'')+'</span><b>'+(p.ready?'Ready':'Not ready')+'</b></div>').join('')+'</div><p class="caption">'+(room.clock?room.clock/60+' minutes each + '+room.increment+' seconds per move.':'No clock. Private play only.')+' Roster and rules lock when the tournament starts.</p>';
  if(room.table)html+='<div class="note">Each player contributes '+room.quote.entry+' '+room.quote.currency+'. Fifth breaks even. 10% burn. No debit until all ten are ready.</div>';
  if(transport!=='local')html+=button(mine?.ready?'Not ready':'Ready'+(room.table?' - approve entry':''),'ready');
  if(isHost&&!room.table)html+=button(transport==='local'?'Everyone is here - Start':'Start tournament','start');
  if(isHost&&!room.table&&transport!=='local')html+='<details><summary>Host controls</summary><div class="party-host-controls">'+room.players.filter(p=>p.id!==room.owner).map(p=>'<div class="ledger"><span>'+esc(p.name)+'</span>'+button('Make host','transfer','data-player="'+esc(p.id)+'"',true)+button('Remove','kick','data-player="'+esc(p.id)+'"',true)+'</div>').join('')+'</div></details>';
  if(transport!=='local')html+=button('Leave lobby','leaveRoom','',true);
 }else if(room.status==='COMPLETE'){
  html+='<h3>Final standings</h3><div class="party-standings"><table><thead><tr><th>Place</th><th>Player</th>'+(room.table?'<th>Payout</th>':'')+'</tr></thead><tbody>'+room.ranking.map((id,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(player(id))+'</td>'+(room.table?'<td>'+room.quote.payouts[i]+' '+room.quote.currency+'</td>':'')+'</tr>').join('')+'</tbody></table></div>';
 }else if(['VOID','CANCELLED','REVIEW','PAUSED'].includes(room.status)){
  html+='<div class="note"><b>'+esc(room.status==='PAUSED'?'Tournament paused':room.status==='REVIEW'?'Settlement under review':'Tournament cancelled')+'</b><p>'+esc(room.reason||'')+'</p>'+(room.receipt?.refunded?'All entry contributions were refunded.':'')+'</div>';
  if(room.status==='PAUSED'&&isHost)html+=button('Resume tournament','resume');
 }
 if(room.groups?.length)for(const group of room.groups){const rows=T.standings(room,group);html+='<h3>'+esc(group.name)+'</h3><div class="party-standings"><table><thead><tr><th>Player</th><th>Played</th><th>Pts</th></tr></thead><tbody>'+rows.map(p=>'<tr><td>'+esc(player(p.id))+'</td><td>'+p.played+'</td><td>'+p.points+'</td></tr>').join('')+'</tbody></table></div>';}
 if(room.fixtures.length){html+='<h3>Schedule & bracket</h3><div class="party-fixtures">'+room.fixtures.map(f=>'<div class="card"><small>'+esc(f.label)+'</small><b>'+esc(player(f.players?.[0]||T.slot(room,f.slots[0])))+' vs '+esc(player(f.players?.[1]||T.slot(room,f.slots[1])))+'</b><span class="caption">'+esc(f.status==='DONE'?(f.winner?player(f.winner)+' won':'Draw'):f.status.toLowerCase())+'</span>'+(['READY','PLAYING'].includes(f.status)?button((transport==='local'||f.players.includes(me()))?'Open game':'Watch','game','data-fixture="'+f.id+'"',true):'')+'</div>').join('')+'</div>';}
 if(playing&&isHost&&!room.table)html+=button('Pause tournament','pause','',true);
 if(playing)html+='<p class="caption">Reconnect with this browser to keep your seat. Match clocks continue on other devices.</p>';
 setBody(html);lastRevision=room.revision;
}
function game(id){activeFixture=id;viewName='game';shell('Tournament game');setBody('<div id="partyGame"><div class="players"><div class="player" id="partyX"></div><div class="player" id="partyO"></div></div><div class="turn-hud"><span class="turn-icon">'+icon('route')+'</span><div><b id="partyTurn"></b><span id="partySend"></span></div></div><div class="board-wrap" id="partyBoardWrap"><div class="mega-board" id="partyBoard"></div><svg class="route-overlay" id="partyRoute" aria-hidden="true"></svg></div><p class="board-note" id="partyHint">Your cell sends the next player.</p><div id="partyGameActions" class="party-options"></div></div>');const board=$('#partyBoard');for(let b=0;b<9;b++){const mini=document.createElement('div');mini.className='mini';mini.dataset.mini=b;for(let c=0;c<9;c++){const cell=document.createElement('button');cell.className='cell';cell.type='button';cell.dataset.pb=b;cell.dataset.pc=c;cell.addEventListener('pointerenter',()=>hover(b,c));cell.addEventListener('pointerleave',clearHover);cell.onclick=()=>play(b,c);mini.append(cell);}const claim=document.createElement('div');claim.className='claim';claim.hidden=true;mini.append(claim);board.append(mini);}paint();}
function mark(p){return '<span class="mark-layer '+p.toLowerCase()+'"><svg viewBox="0 0 40 40" stroke="currentColor" aria-hidden="true">'+(p==='X'?'<path d="M10 10 30 30M30 10 10 30"/>':'<circle cx="20" cy="20" r="11"/>')+'</svg></span>';}
function paint(){const f=room?.fixtures.find(f=>f.id===activeFixture);if(!f||!$('#partyBoard'))return;const state=f.state||G.create(),own=transport==='local'||f.players?.includes(me()),turn=f.players?.[state.turn==='X'?0:1],legal=new Set(G.legal(state).map(m=>m.b*9+m.c));
 for(let b=0;b<9;b++){const mini=$('[data-mini="'+b+'"]',body),allowed=!state.winner&&!state.mini[b]&&(state.required===null||state.required===b);mini.className='mini'+(allowed?(state.required===null?' available':' active'):' inactive');for(let c=0;c<9;c++){const cell=$('[data-pc="'+c+'"]',mini),value=state.board[b][c]||'';if(cell.dataset.mark!==value){cell.innerHTML=value?mark(value):'';cell.dataset.mark=value;}cell.disabled=room.status!=='RUNNING'||f.status!=='PLAYING'||busy||!own||(transport!=='local'&&turn!==me())||!legal.has(b*9+c);cell.setAttribute('aria-label',G.NAMES[b]+' board, '+G.NAMES[c]+', '+(value||'empty'));}const claim=$('.claim',mini);claim.hidden=!state.mini[b];if(state.mini[b]){claim.className='claim '+state.mini[b].toLowerCase();claim.innerHTML=state.mini[b]==='DRAW'?'<span>DRAW</span>':mark(state.mini[b]);}}
 ['X','O'].forEach((p,i)=>{const el=$('#party'+p);el.classList.toggle('active',f.status==='PLAYING'&&state.turn===p);el.innerHTML='<span class="player-glyph '+p.toLowerCase()+'">'+p+'</span><div><b>'+esc(player(f.players?.[i]))+'</b><small>'+state.mini.filter(v=>v===p).length+' Mini Boards</small></div><strong data-clock="'+p+'"></strong>';});
 $('#partyTurn').textContent=f.status==='READY'?'Ready for '+f.label:f.status==='DONE'?(f.winner?player(f.winner)+' wins':'Draw'):player(turn)+"'s turn";
 $('#partySend').textContent=state.required===null?'Free Move - choose any open board':'Play in '+G.NAMES[state.required];
 if(room.status==='PAUSED'){$('#partyTurn').textContent='Tournament paused';$('#partySend').textContent='The host can resume from the lobby.';}else if(room.status==='VOID'||room.status==='REVIEW'){$('#partyTurn').textContent=room.status==='VOID'?'Tournament cancelled':'Tournament under review';$('#partySend').textContent='Return to the lobby for details.';}else if(f.status==='READY'&&f.attempt>0){$('#partyTurn').textContent='Draw - replay with sides swapped';}
 const actions=$('#partyGameActions');actions.innerHTML=(room.status==='RUNNING'&&f.status==='READY'&&own?button(Date.now()+offset<f.opens?'Starts in '+Math.ceil((f.opens-Date.now()-offset)/1000)+'s':f.ready.includes(me())?'Waiting for opponent':'Ready to play','gameReady','data-fixture="'+f.id+'" '+((Date.now()+offset<f.opens||f.ready.includes(me()))?'disabled':'')):'')+button('Back to lobby','room','',true)+(room.status==='RUNNING'&&f.status==='PLAYING'&&own?button('Resign this game','resign','data-fixture="'+f.id+'"',true):'');clock();I?.refresh?.();}
function clock(){if(viewName!=='game'||!room)return;const f=room.fixtures.find(f=>f.id===activeFixture);if(!f)return;for(const [i,p] of ['X','O'].entries()){const el=$('[data-clock="'+p+'"]');if(el)el.textContent=!room.clock?'\u221e':f.status!=='PLAYING'?fmt(room.clock):fmt(p===f.state.turn?T.remaining(room,f,Date.now()+offset):f.banks[f.players[i]]);}}
function clearHover(){body?.querySelectorAll('.cell-hover').forEach(el=>el.classList.remove('cell-hover','hover-x','hover-o'));body?.querySelectorAll('.mini.preview').forEach(el=>el.classList.remove('preview'));}
function hover(b,c){clearHover();const cell=$('[data-pb="'+b+'"][data-pc="'+c+'"]',body),f=room.fixtures.find(f=>f.id===activeFixture);if(!cell||cell.disabled||!f.state)return;cell.classList.add('cell-hover','hover-'+f.state.turn.toLowerCase());if(!f.state.mini[c])$('[data-mini="'+c+'"]',body).classList.add('preview');$('#partyHint').textContent=f.state.mini[c]?'This gives the next player a Free Move.':'Next board: '+G.NAMES[c]+'.';}
function route(m,next){if(next===null||!$('#partyRoute'))return;const overlay=$('#partyRoute'),wrap=$('#partyBoardWrap').getBoundingClientRect(),a=$('[data-pb="'+m.b+'"][data-pc="'+m.c+'"]',body).getBoundingClientRect(),b=$('[data-mini="'+next+'"]',body).getBoundingClientRect();overlay.setAttribute('viewBox','0 0 '+wrap.width+' '+wrap.height);overlay.innerHTML='<line x1="'+(a.x+a.width/2-wrap.x)+'" y1="'+(a.y+a.height/2-wrap.y)+'" x2="'+(b.x+b.width/2-wrap.x)+'" y2="'+(b.y+b.height/2-wrap.y)+'"/><circle cx="'+(b.x+b.width/2-wrap.x)+'" cy="'+(b.y+b.height/2-wrap.y)+'" r="5"/>';setTimeout(()=>{if(overlay.isConnected)overlay.innerHTML='';},700);}
async function play(b,c){if(busy)return;const f=room.fixtures.find(f=>f.id===activeFixture);if(f.status!=='PLAYING')return;busy=true;try{room=await command({type:'move',fixture:f.id,actor:f.players[f.state.turn==='X'?0:1],revision:f.state.moves.length,move:{b,c}});paint();const next=room.fixtures.find(g=>g.id===f.id);if(next.state)route({b,c},next.state.required);}catch(e){message(errorText(e));}finally{busy=false;paint();}}
function startPolling(){clearInterval(poll);poll=setInterval(async()=>{if(!screen||!room||busy)return;try{const previous=room.fixtures.find(f=>f.id===activeFixture)?.state?.moves.length||0;if(transport==='local'){T.tick(room,Date.now());persist();}else{const update=await request('rooms/'+room.id+'?revision='+room.revision);offset=update.serverNow-Date.now();if(!update.unchanged)room=update;}if(viewName==='room'&&lastRevision!==room.revision)drawRoom();if(viewName==='game'){paint();const f=room.fixtures.find(f=>f.id===activeFixture);if(f?.state?.moves.length>previous)route(f.state.moves.at(-1),f.state.required);}}catch{message('Connection lost. Reconnecting; the match clock may still be running.');}},900);}
function rules(){shell('Tournament rules');viewName='rules';setBody('<div class="tutorial-cards"><div class="tutorial-card"><span class="step-number">1</span><div><b>League</b><p>Everyone plays everyone once. Ten players means 9 rounds and 45 games, with up to 5 games at once. Win = 2 points, draw = 1, loss = 0.</p></div></div><div class="tutorial-card"><span class="step-number">2</span><div><b>Knockout</b><p>Lose and you leave the title bracket, but placement games decide your final position. Ten players have two play-ins, quarter-finals, semi-finals and finals.</p></div></div><div class="tutorial-card"><span class="step-number">3</span><div><b>Groups + Knockout</b><p>At ten players: two groups of five. The top two in each group enter cross-group semi-finals. Everyone else plays their equal-position opponent for places 5/6, 7/8 or 9/10. Semi-final losers play for third.</p></div></div></div><div class="note">Ties: points, head-to-head, opponent-strength score, Mini Board differential, then fewer forfeits. Still tied? Play placement tie-breaks. Drawn knockout games replay with starters swapped. Three drawn attempts pause a private event; a public event refunds all entries. Placements are decided by play, never a coin toss.</div><p class="caption">Public events have a 2-hour safety limit and 2 min + 1 sec clocks. Ready within 45 seconds of your opponent or forfeit that game. If neither appears within 2 minutes, a private event pauses; a public event is voided and refunded. Clocks keep running through network loss.</p>'+button(room?'Back to lobby':'Back','room','',true));}
const errorText=e=>({SERVICE_UNAVAILABLE:'The room service is unavailable.',AUTH_REQUIRED:'Sign in to use online rooms.',ENTER_NAME:'Enter your name first.',ENTER_2_TO_10_NAMES:'Enter between 2 and 10 player names.',NOT_ENOUGH_PLAYERS:'Mixed needs at least four players. Public tables need ten.',PLAYERS_NOT_READY:'Wait for every player to ready.',PAID_ENTRY_UNAVAILABLE:'Entry tournaments are unavailable in this service.',INELIGIBLE:'This table requires an eligible account and completed placements.',MATCH_NOT_READY:'Wait for the round countdown, then ready up.',ROOM_FULL:'This room already has ten players.',ALREADY_QUEUED:'You already have a table seat.',RULES_CHANGED:'The host changed the rules. Review and ready again.',TIME_EXPIRED:'Time ran out; the server will update the result.'}[e.message]||e.message.replaceAll('_',' ').toLowerCase());
document.addEventListener('click',async e=>{
 const start=e.target.closest('[data-action="start"]');if(start&&$('.mode.active[data-value="private"]')){e.preventDefault();e.stopImmediatePropagation();hub();return;}
 const el=e.target.closest('[data-party]');if(!el||el.disabled)return;e.preventDefault();e.stopImmediatePropagation();const action=el.dataset.party;
 try{switch(action){case 'tables':tables();break;case 'table':table(el.dataset.table);break;case 'hub':hub();break;case 'back':if(viewName==='hub'||viewName==='tables')hide();else if(viewName==='room')hide();else if(room&&['game','rules'].includes(viewName))showRoom();else hub();break;case 'room':room?showRoom():hub();break;case 'local':transport='local';setup();break;case 'lan':await connect('lan');break;case 'online':await connect('online');await ensureOnlineActor();break;case 'createForm':setup(false);break;case 'joinForm':setup(true);break;case 'createRoom':await createRoom();break;case 'joinRoom':await joinRoom();break;case 'continue':transport='local';room=saved();session={actor:room.owner};showRoom();startPolling();break;
 case 'joinPublic':transport='online';await ensureOnlineActor();room=await command({type:'publicJoin',table:el.dataset.table});showRoom();startPolling();break;
 case 'ready':room=await command({type:'ready',value:!room.players.find(p=>p.id===me())?.ready,rulesVersion:room.rulesVersion});drawRoom();break;case 'start':room=await command({type:'start'});drawRoom();startPolling();break;
 case 'transfer':case 'kick':room=await command({type:action,target:el.dataset.player});drawRoom();break;
 case 'leaveRoom':await command({type:'leave'});room=null;localStorage.removeItem('mega_party_network_room');clearInterval(poll);hub();break;
 case 'reconnect':{const savedRoom=networkSaved();if(!savedRoom)break;transport=savedRoom.transport;if(transport==='lan')session=JSON.parse(localStorage.getItem('mega_party_session')||'null');else await ensureOnlineActor();room=await request('rooms/'+savedRoom.id);offset=room.serverNow-Date.now();showRoom();startPolling();break;}case 'pause':room=await command({type:'pause'});drawRoom();break;case 'resume':room=await command({type:'resume'});drawRoom();break;
 case 'copy':{const invite=location.origin+location.pathname+'#party='+room.code;try{await navigator.clipboard.writeText(invite);message('Invite copied.');}catch{message(invite);}break;}
 case 'game':game(el.dataset.fixture);break;case 'gameReady':{const f=room.fixtures.find(f=>f.id===el.dataset.fixture);if(transport==='local'){for(const actor of f.players)room=await command({type:'matchReady',fixture:f.id,actor});}else room=await command({type:'matchReady',fixture:f.id});paint();break;}
 case 'resign':if(confirm('Resign this tournament game? This counts as a loss.')){const f=room.fixtures.find(f=>f.id===el.dataset.fixture);room=await command({type:'resign',fixture:f.id,actor:f.players[f.state.turn==='X'?0:1]});showRoom();}break;
 case 'rules':rules();break;case 'friends':hide();$('#navigation [data-value="friends"]').click();break;
 }}catch(error){message(errorText(error));}
},true);
setInterval(clock,200);
if(location.hash.startsWith('#party=')){const code=location.hash.slice(7);request('capabilities').then(c=>connect(c.lan?'lan':'online')).then(async()=>{if(viewName==='create'){if(transport==='online')await ensureOnlineActor();setup(true);$('#partyCode').value=code;}}).catch(()=>{hub();message('Open the invite on the room host address.');});}
window.MegaParties=Object.freeze({open:hub,tables,version:'3.3.4'});
})();
